### PR TITLE
defense in depth against goroutine leak

### PR DESCRIPTION
**Pull request by majewsky**
For #1977. As explained over there (and also in the code comment in this PR's diff), I do not see any evidence for an actual problem, but given the general gnarliness of this code, I think it makes sense to be a bit more explicit here (esp. to reduce the chance of a later refactoring accidentally introducing a goroutine leak).

### CODE REVIEW

**Comment by majewsky** [comment]
@pamburus @kayrus FYI

**Comment by pamburus** [comment]
@majewsky 
Did you see this issue?
 https://github.com/golang/go/issues/19702

**Comment by pamburus** [comment]
This pull request does not fix leaks.

**Comment by majewsky** [comment]
You're right (as discussed in #1977).

**Pull request closed without merging**
