### PR TITLE
support context.Context for outgoing HTTP requests

### LINKED ISSUE #1476: Feature request: support context.Context to cancel/time-out requests
IMHO it would be neat if one could pass an existing `context.Context` that would be propagated to the outgoing HTTP requests. Concrete example: Prometheus uses gophercloud for its [OpenStack service discovery](https://github.com/prometheus/prometheus/tree/master/discovery/openstack) (aka SD) which lists OpenStack instances at regular intervals. The SD goroutine gets a context that is canceled when it needs to exit (because the program stops or the configuration gets reloaded). Right now it means that when a request to the Nova API is in progress and the context is canceled, we need to wait for the request completion before effectively returning.

Implementation-wise, I could see it as an additional `Context` field to the [`gophercloud.ProviderClient`](https://godoc.org/github.com/gophercloud/gophercloud#ProviderClient) struct. If not nil, the context would be injected in the constructed [`http.Request`](https://github.com/gophercloud/gophercloud/blob/307b801773c3c1018ca059dd511b9a08714e97d6/provider_client.go#L313).

If this is something that is found helpful, I'm willing to start a PR.

### PR DESCRIPTION
**Pull request by simonpasquier**
Closes #1476

cc @jtopjian

### CODE REVIEW

**Comment by jtopjian** [comment]
@simonpasquier In general, this looks good to me. Before I sign-off on it, I wanted to make sure the same thing couldn't be done in a similar way as what we have outlined in the [FAQ](https://github.com/gophercloud/gophercloud/blob/master/docs/FAQ.md#implementing-default-logging-and-re-authentication-attempts)?

**Comment by simonpasquier** [comment]
@jtopjian I thought about using a custom `RoundTripper` injecting a crafted context but it wouldn't apply to the TCP connection + TLS negotiation phases.

**Comment by jtopjian** [comment]
@simonpasquier Good point. Thank you for implementing this!

**Comment by simonpasquier** [comment]
Thanks for the quick feedback! It was a pleasure contributing :smiley:

**Pull request merged**
