### PR TITLE
Acc Tests: Skipping some tests on older OpenStack releases

### PR DESCRIPTION
**Pull request by jtopjian**
For #1976

### CODE REVIEW

**Comment by jtopjian** [comment]
recheck stable/queens

**Comment by jtopjian** [comment]
recheck stable/rocky

**Comment by jtopjian** [comment]
recheck stable/rocky

**Comment by jtopjian** [comment]
recheck stable/stein

**Comment by jtopjian** [comment]
recheck stable/queens

**Comment by jtopjian** [comment]
recheck stable/stein

**Comment by jtopjian** [comment]
recheck stable/ocata

**Comment by jtopjian** [comment]
recheck stable/ocata

**Comment by jtopjian** [comment]
recheck stable/pike

**Comment by jtopjian** [comment]
recheck stable/pike

**Comment by jtopjian** [comment]
recheck stable/pike

**Comment by jtopjian** [comment]
recheck stable/newton

**Comment by jtopjian** [comment]
recheck stable/ocata

**Comment by jtopjian** [comment]
recheck stable/train

**Comment by wangxiyuan** [comment]
recheck stable/train

**Comment by jtopjian** [comment]
recheck stable/train

**Comment by jtopjian** [comment]
recheck stable/ussuri

**Pull request merged**
