### PR TITLE
Prepare v2.0.0-beta.1

### PR DESCRIPTION
**Pull request by pierreprinetti**
* Update the changelog. Fetch all changes from `v1` from v1.5.0 to v1.9.0
* Bump the module name to `github.com/gophercloud/gophercloud/v2` in `go.mod` and in all internal imports
* Update the user agent string to `v2.0.0-beta.1` and add non-backported PRs to the changelog.

### CODE REVIEW

**Review by EmilienM — DISMISSED** [review]
Thanks for working on this Pierre, once CI is green I think we're ready.

**Comment by EmilienM** [comment]
I think all PRs we wanted for v2-beta have landed, if that's the case let's release this week!

**Comment by pierreprinetti** [comment]
Ok! Hold for rebase.

**Comment by EmilienM** [comment]
that's a lot of CI failures, let me see what's going on

**Comment by EmilienM** [comment]
The stable OpenStack jobs are broken, I'm working on it. This is not an issue for this PR though so I think we can go ahead.

**Review by EmilienM — APPROVED** [review]

**Pull request merged**
