### PR TITLE
support for sort new syntax

### PR DESCRIPTION
**Pull request by iaroslavscript**
Hi!

For #579 

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:
https://github.com/openstack/glance/blob/stable/pike/glance/api/v2/images.py#L683

Links to the docs:
https://specs.openstack.org/openstack/glance-specs/specs/api/v2/lists-image-api-v2.html

### CODE REVIEW

**Comment by jtopjian** [comment]
@iaroslavscript Thanks for submitting this. This patch looks useful and simple, which is always good :)

I recommend adding a little more detail to the field comment. Perhaps something like:

```
// Sort sorts the results using the new style of sorting. See the OpenStack
// Image API reference for the exact syntax.                         
//                                                                           
// Sort cannot be used with the classic sort options (sort_key and sort_dir).                
```

**Comment by iaroslavscript** [comment]
Hi @jtopjian thanks! I updated comments.

**Comment by jtopjian** [comment]
Looks good! Thank you for working on this.

**Comment by iaroslavscript** [comment]
thx :)

**Pull request merged**
