### PR TITLE
Add os-aggregates support

### PR DESCRIPTION
**Pull request by ildarsv**
For #690 

Add support for the Nova host aggregates to list host aggregates.

API reference:
https://developer.openstack.org/api-ref/compute/#list-aggregates

Implementation:
https://github.com/openstack/nova/blob/stable/pike/nova/api/openstack/compute/aggregates.py#L44

### CODE REVIEW

**Comment by ildarsv** [comment]
Hello @jaypipes, @jtopjian ! Please review this stuff, when you have time :)

**Comment by jtopjian** [comment]
@ildarsv Thank you for submitting this. I did a cursory scan and this looks good - thank you for limiting this to only List as well as including documentation.

There are three things missing, though, before I can do a full review:

1. Link to the Nova code that implements aggregates.
2. Unit tests
3. Acceptance test (even if the test returns no actual results)

Please let me know if you have any questions or need any help.

**Comment by ildarsv** [comment]
@jtopjian Thanks for the quick response! Sorry for the non-observance of rules.
I've added link to the Nova code and required tests. Please review when you have time.

**Comment by jtopjian** [comment]
@ildarsv Thanks!

In general this looks good. I have one item for discussion, though: the list of fields defined here:

https://github.com/openstack/nova/blob/09ed3b5626ac306e59856db89858eb7bee4daa0e/nova/objects/aggregate.py#L242-L250

shows a `metadata` field. I think we should include this in the `results.go` file. It should be a simple `map[string]string` type.

I think it should be safe to leave out the `deleted` field and the timestamp fields, at least for now. There's a comment in the `objects/aggregate.py` file that mentions `delete` and `deleted_at` being deprecated.

Let me know if you have any questions or see a reason not to include `metadata`.

**Comment by ildarsv** [comment]
@jtopjian Good point, thanks! I've added `metadata` field. Yes, let's skip the rest fields.

**Comment by jtopjian** [comment]
This looks good to me. Thank you for working on it :)

**Pull request merged**
