### PR TITLE
Feature/filestorage sharenetworks add securityservice

### PR DESCRIPTION
**Pull request by ehdou**
Add support for Share Network Add security service
For #130

### CODE REVIEW

**Comment by ehdou** [comment]
[Add security service function](https://github.com/openstack/manila/blob/16c522bf5e5c3d37018caef11dd7852462193327/manila/api/v1/share_networks.py#L295) for share network

**Comment by ehdou** [comment]
@jrperritt This PR is ready for review. It's based on [PR#136](https://github.com/gophercloud/gophercloud/pull/136) and adds support for share network Add security service

**Comment by ehdou** [comment]
@jtopjian Hi, this PR is rebased and ready for review.

**Comment by jtopjian** [comment]
Looks good to me - thanks!

**Pull request merged**
