### PR TITLE
Identity V3: Add ExtractDomain method for the identity/v3/tokens package

### LINKED ISSUE #1711: Identity V3: Add ExtractDomain method for the identity/v3/tokens package
When the auth is domain scoped, then there should be an option to extract the token's domain scope. See https://docs.openstack.org/api-ref/identity/v3/?expanded=password-authentication-with-scoped-authorization-detail#domain-scoped-example for example

### PR DESCRIPTION
**Pull request by kayrus**
Resolves #1711

### CODE REVIEW

**Comment by jtopjian** [comment]
@kayrus Thanks! 

Can you include a unit test with a domain-scoped fixture? Please don't copy and paste from the API docs, though - it should be a new fixture generated from a running OpenStack environment or devstack.

**Comment by kayrus** [comment]
@jtopjian I issued the token response from my environment as a base, then I copy-pasted the catalog and userids from the initial fixtures. I hope it is fine.

**Comment by kayrus** [comment]
@jtopjian @huangtianhua looks like the `OS_SUBNET_ID` environment variable disappeared from the openlab landscape:

```
2019-09-18 12:02:26.714328 | ubuntu-xenial | +++ openrc:source:117                        :   export OS_SUBNET_ID=
2019-09-18 12:02:26.717761 | ubuntu-xenial | +++ openrc:source:117                        :   OS_SUBNET_ID=
```

**Comment by jtopjian** [comment]
Good find. I think this test has made more progress than previous ones - prior test failures haven't gotten to the point of running any tests.

There might be an issue with devstack creating the subnet:

```
2019-09-18 19:13:50.869488 | ubuntu-xenial | +++ ./script/stackenv:source:10              :   openstack subnet show private_subnet -c id -f value
2019-09-18 19:13:54.007126 | ubuntu-xenial | No Subnet found for private_subnet
```

**Pull request merged**
