### PR TITLE
Support storage policy on container create

### LINKED ISSUE #2074: Support storage policy on container create
Add support for the `X-Storage-Policy` header in `containers.CreateOpts`. https://docs.openstack.org/api-ref/object-store/?expanded=create-container-detail#create-container

Example usage.

```go
createOpts := containers.CreateOpts{
	ContentType:   "application/json",
	StoragePolicy: "nz-hlz-1--o1--sr-r3",
}

result := containers.Create(swiftClient, "go-test-2", createOpts)
```

Inspection of the StoragePolicy attribute of a container is already supported without modification via the `containers.Get` method

```go
containerDetails := containers.Get(swiftClient, container.Name, nil)
fmt.Printf("%v+\n\n", containerDetails)

// {{{<nil> map[Accept-Ranges:[bytes] Content-Length:[0] Content-Type:[application/json; charset=utf-8] Date:[Thu, 17 Dec 2020 12:43:59 GMT] Server:[nginx/1.16.0] X-Container-Bytes-Used:[0] X-Container-Object-Count:[0] X-Storage-Policy:[nz-hlz-1--o1--sr-r3] X-Timestamp:[1608206959.71870] X-Trans-Id:[txcc5852ecf7134117bfdc4-005fdb528f]] <nil>}}}+
```

### PR DESCRIPTION
**Pull request by iokiwi**
For #2074 
Fixes #2074

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

 * https://github.com/openstack/swift/blob/ed990999170e7789dc6e32f299c0a3818636d9ea/swift/proxy/controllers/container.py#L64

### CODE REVIEW

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
Something seems wonky with OpenLab. I'm inclined to go ahead ad merge this anyway, though. Is this ready for review/merge?

**Comment by iokiwi** [comment]
@jtopjian yep I am happy for it to be merged if you are fine with the state of the build. I tested manually

**Review by jtopjian — APPROVED** [review]
LGTM - thank you!

**Pull request merged**
