### PR TITLE
Add missing fields in Objectstorage and compute API

### PR DESCRIPTION
**Pull request by pdesgarets**
Fixes https://github.com/gophercloud/gophercloud/issues/2386 and https://github.com/gophercloud/gophercloud/issues/1958

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

https://docs.openstack.org/api-ref/compute/?expanded=show-server-details-detail#:~:text=security%20group%20name.-,locked,-body
https://docs.openstack.org/api-ref/object-store/?expanded=create-container-detail#:~:text=X%2DContainer%2DSync%2DTo%20(Optional)

### CODE REVIEW

**Comment by EmilienM** [comment]
bonjour @pdesgarets [pdesgarets](https://github.com/pdesgarets) :-)

Thanks for your pull request.
Usually, we do one pull request per issue. But I'm not sure, so I'll be ok with the way it is now, just keep in mind for the next ones ;-)

For this PR, I see it has unit tests, thanks. It'll be great to also have acceptance coverage. Let me know if you need help for that.

Thanks!

**Comment by pdesgarets** [comment]
OK, thanks for the review, I'll try to add acceptance tests, that may require some additional time

**Comment by CloudCourierStation** [comment]
Hello, may I ask if you are willing to further improve this PR? Now I have some requirements for Server Lock Status @pdesgarets

**Comment by pdesgarets** [comment]
Hi, I currently lack of free time, feel free to start from by branch and add the needed acceptance tests

**Review by pierreprinetti — APPROVED** [review]

**Pull request merged**
