### PR TITLE
Network v2: FWaaS v1 Router Updates

### PR DESCRIPTION
**Pull request by jtopjian**
For #291

### CODE REVIEW

**Comment by jtopjian** [comment]
@jrperritt Let me know if you'd like this broken up into two PRs. They seemed small enough to roll into 1.

Ready for review.

**Comment by fatmcgav** [comment]
@jtopjian Cheers for the quick turn-around on this one... 😆

**Comment by fatmcgav** [comment]
@jrperritt Any chance of getting this one merged? I've tested locally and confirm the changes work as expected. 

Cheers

**Comment by fatmcgav** [comment]
@jtopjian Any chance of a merge on this one?

**Comment by jtopjian** [comment]
@fatmcgav Yep. Give me a few days. I've been tied up with preparing for the OpenStack Summit last week, attending this week, and will now be catching up on things :)

**Comment by fatmcgav** [comment]
Heh, no worries... Just spotted you'd started merging stuff, so thought I'd nudge this one :) 

Tangent, any ideas where jrperritt has gone?

**Comment by jtopjian** [comment]
Yeah, I've been merging some low-hanging-fruit as well as working from the back of the queue to the front. 

He is still around :) See https://github.com/gophercloud/gophercloud/issues/328 for more details.

**Comment by fatmcgav** [comment]
Ah, cool... Well if I can ever assist in the future just holla :)

**Comment by jtopjian** [comment]
Yeah, definitely. Feel free to start tackling anything. I'd be happy with a queue of feature PRs.

**Comment by jrperritt** [comment]
LGTM

**Pull request merged**
