### PR TITLE
FWaaSv2 Get & List firewall-groups

### PR DESCRIPTION
**Pull request by codemanufaktur**
For #514

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

https://github.com/openstack/neutron-fwaas/blob/stable/ussuri/neutron_fwaas/db/firewall/v2/firewall_db_v2.py#L85-L103
https://github.com/openstack/neutron-fwaas/blob/stable/ussuri/neutron_fwaas/db/firewall/v2/firewall_db_v2.py#L307:L322

**this PR:
FWaaSv2 Get & List firewall-groups**

next PRs:
FWaaSv2 Create firewall-groups
FWaaSv2 Update & Delete firewall-groups
Acceptance test for fwaasv2 firewall groups

kind regards, 
Georg

<sub>Georg Schreiber georg.g.schreiber@daimler.com, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Comment by codemanufaktur** [comment]
Hi @jtopjian, can you please take a look at my PRs? :-)

**Comment by jtopjian** [comment]
@codemanufaktur Yes, I should be able to take a look within a few days. Sorry for the delay.

**Comment by jtopjian** [comment]
@codemanufaktur 

> Links to the line numbers/files in the OpenStack source code that support the
code in this PR:
>
> https://github.com/openstack/neutron-fwaas/blob/27906d0acff349c9e5ac7955d203fb2233c295db/neutron_fwaas/db/firewall/v2/firewall_db_v2.py#L85-L103

I think there's more code that needs researched here. For example, the above link shows that the database table has `port_associations` field, but none of the structs use this field. Instead, the structs and the test fixtures all have a `ports` field. Where is the `ports` field coming from?

**Comment by codemanufaktur** [comment]
@jtopjian 
please see this for the `ports` field:
https://github.com/openstack/neutron-fwaas/blob/stable/ussuri/neutron_fwaas/db/firewall/v2/firewall_db_v2.py#L319
https://github.com/openstack/neutron-fwaas/blob/stable/ussuri/neutron_fwaas/services/firewall/fwaas_plugin_v2.py#L317

I will update the links in the description.

**Comment by jtopjian** [comment]
Superseded by #2050

**Pull request closed without merging**
