### PR TITLE
Fix incorrect variable name

### PR DESCRIPTION
**Pull request by TommyLike**
TrivialFix
For #683

### CODE REVIEW

**Comment by jtopjian** [comment]
@TommyLike Thanks!

**Comment by jtopjian** [comment]
@TommyLike Actually, this needs a corresponding issue. This is indeed a trivial fix, but each PR must correspond to an issue.

**Comment by TommyLike** [comment]
@jtopjian  sure

**Comment by jtopjian** [comment]
@TommyLike Thank you :)

**Pull request merged**
