### PR TITLE
Create dependabot.yaml

### PR DESCRIPTION
**Pull request by EmilienM**
Get our dependencies automatically updates by Dependabot. It's free and easy to setup, let's just use it.

### CODE REVIEW

**Comment by EmilienM** [comment]
cc @pierreprinetti 
any thoughts?

**Comment by EmilienM** [comment]
cc @mandre

**Comment by mandre** [comment]
I'm OK giving it a try, but I'm a bit worried we'll get spammed with low value PRs bumping micro versions of libraries.

**Comment by pierreprinetti** [comment]
I have mixed feelings WRT dependabot, but I have no strong arguments against.

/approve

**Comment by EmilienM** [comment]
@mandre we don't have much libraries:

https://github.com/gophercloud/gophercloud/blob/master/go.mod#L6-L8

**Comment by EmilienM** [comment]
@pierreprinetti :

> I have mixed feelings WRT dependabot, but I have no strong arguments against.

please elaborate, discussion is open.

**Comment by jtopjian** [comment]
In my experience, dependabot for Go projects has had a really good signal/noise ratio. Combined with the low amount of external packages that Gophercloud needs, I don't think this is going to cause any problems.

**Comment by mandre** [comment]
LGTM :+1:

**Pull request merged**
