### PR TITLE
Acceptance: add Identity V3 Trusts CRUD test

### PR DESCRIPTION
**Pull request by ozerovandrei**
Add TestTrustCRUD acceptance test with some helpers to create and delete
trusts.

For #1642 

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

https://github.com/openstack/keystone/blob/stable/stein/keystone/api/trusts.py
https://github.com/openstack/keystone/blob/stable/stein/keystone/trust/core.py

### CODE REVIEW

**Comment by ozerovandrei** [comment]
There is following error:
``
2019-07-15 18:38:47.304606 | ubuntu-xenial |     convenience.go:35: [1;31mFailure in trusts_test.go, line 52: unexpected error [0m[1;33m"Request forbidden: [POST http://192.168.0.9/identity/v3/OS-TRUST/trusts], error message: {\"error\":{\"code\":403,\"message\":\"You are not authorized to perform the requested action: identity:create_trust.\",\"title\":\"Forbidden\"}}\n"[0m[1;31m[0m
```

But I required admin privilegies 🤔:
```
func TestTrustCRUD(t *testing.T) {
	clients.RequireAdmin(t)
```

**Comment by jtopjian** [comment]
@ozerovandrei It's possible that Identity trusts are not enabled in the OpenLab configuration. 

@kiwik @huangtianhua Can you confirm if the Keystone/Identity `OS-TRUST` extension is enabled?

**Comment by huangtianhua** [comment]
@jtopjian @ozerovandrei I looked the code of keystone, the api 'create_trust' required the rule: RULE_TRUST_OWNER(RULE_TRUST_OWNER = 'user_id:%(trust.trustor_user_id)s') 
https://github.com/openstack/keystone/blob/master/keystone/common/policies/trust.py#L20 
https://github.com/openstack/keystone/blob/master/keystone/common/policies/base.py#L32

Seems the test you added doesn't follow this rule, could you check this?

**Comment by ozerovandrei** [comment]
Implemented in #1818

**Pull request closed without merging**
