### PR TITLE
Orchestration v1: Doc updates, Time fixes, and Acceptance Tests

### PR DESCRIPTION
**Pull request by jtopjian**
For #949 
For #185 
For #818 

Supersedes #1177

### CODE REVIEW

**Comment by jtopjian** [comment]
recheck stable/mitaka

**Comment by jtopjian** [comment]
@scott-chaney this PR should fix the issue you confirmed in #185. Would you be able to test it and verify it works? It looks like the OpenLab Mitaka test suite isn't working.

**Comment by scott-chaney** [comment]
@jtopjian pulled down your jtopjian:fix-orchestration-stack2 branch, the changes appear to be working well for both Queens and Mitaka.  I only checked on the listed stack but I will do a bit more testing tomorrow.
Thanks!

**Comment by scott-chaney** [comment]
I did some more testing for events, resources, and the various stack retrieval types.  All appear to be working fine in both Queens and Mitaka.

**Comment by jtopjian** [comment]
@scott-chaney awesome - thank you so much for testing this out.

**Comment by jtopjian** [comment]
@ricolin Thank you for your work on this! It is very much appreciated!

**Comment by liu-sheng** [comment]
recheck stable/mitaka

**Pull request merged**
