### PR TITLE
[DO NOT MERGE] Test openlab config

### PR DESCRIPTION
**Pull request by hongbin**
Depends-On: https://github.com/theopenlab/openlab-zuul-jobs/pull/142

Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #[PUT ISSUE NUMBER HERE]

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[PUT URLS HERE]

### CODE REVIEW

**Comment by mrhillsman** [comment]
recheck

**Comment by hongbin** [comment]
This PR "depends-on" a change in the job's config. However, it looks the CI doesn't pick up the change.

From the logs (https://github.com/gophercloud/gophercloud/pull/927#issuecomment-380917196), it looks the job was started with the old config, then during the execution of the job, it downloads the version that this PR "depends-on", which seems to be too late so don't have any effect.

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
recheck

**Comment by hongbin** [comment]
@mrhillsman let's do a revert, then we can give another try tomorrow.

**Comment by mrhillsman** [comment]
recheck

**Comment by hongbin** [comment]
recheck

**Comment by hongbin** [comment]
Tested pull request: https://github.com/theopenlab/openlab-zuul-jobs/pull/159

**Comment by hongbin** [comment]
recheck

**Comment by hongbin** [comment]
recheck

**Comment by hongbin** [comment]
recheck

**Comment by hongbin** [comment]
recheck

**Comment by hongbin** [comment]
recheck

**Comment by hongbin** [comment]
recheck

**Comment by hongbin** [comment]
recheck

**Pull request closed without merging**
