### PR TITLE
BGP Dynamic Routing

### PR DESCRIPTION
**Pull request by shhgs**
# Adding features for [BGP Dynamic Routing](https://github.com/gophercloud/gophercloud/issues/2208)

The issue number is: #[2208]

The URL of the pull request branch is [https://github.com/shhgs/gophercloud/tree/dev]

### CODE REVIEW

**Comment by jtopjian** [comment]
@shhgs Thank you for submitting this, but I think this is too big of a PR to review. I recommend reading our [contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial) for guidelines. In the majority of cases, PRs should be limited to one request (For example `ListBGPSpeakers`). Once an author has submitted a few PRs and understands the review workflow, then submitting a PR for a single extension is okay to do.

Please let me know if you have any questions.

**Comment by jtopjian** [comment]
> Sure. I will isolate the ListBGPSpeakers first.

Thank you 🙂 

> By the way, we've tested this branch on our lab and preprod env

That's great. Can you please add these tests as acceptance tests to your code? For `ListBGPSpeakers`, it may have to wait until you implement the Create function unless there are existing BGP resources that exist by default in OpenStack.

**Comment by shhgs** [comment]
@jtopjian ListBGPSpeakers  assumes the speaker is already created and added to the agents. Therefore I have to delay the implementation. But sure, I will add acceptance tests.

**Comment by EmilienM** [comment]
@shhgs bonjour :)

Please let us know if you need any help rebasing/updating the PR with addressed comments.
I think this would be a really nice addition to have!

Thanks

**Comment by shhgs** [comment]
I am going to close this one and substitute it with a series of PRs.

**Pull request closed without merging**
