### PR TITLE
Messaging Queue Acceptance Tests

### PR DESCRIPTION
**Pull request by problemv**
For #836

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

https://github.com/openstack/zaqar/blob/8e0dd9763aba67bb7094cf92312daeba8d087866/zaqar/transport/wsgi/v2_0/queues.py#L43

### CODE REVIEW

**Comment by jtopjian** [comment]
@problemv One additional change to the client function is to add:

```go
client = configureDebug(client)
```

See the other client functions and how it's used there.

This allows you to run the acceptance tests with `OS_DEBUG=1` set and you'll see the full API traffic. It's really helpful for debugging.

**Comment by problemv** [comment]
@jtopjian I also cleaned up the commits for all of these, sorry I let that get out of hand. Too used to working in Gerrit... hopefully this new approach makes things easier for you.

**Comment by jtopjian** [comment]
> FYI the Senlin client is missing it too.

Yeah, this feature was added around the same time Zaqar and Senlin PRs started, so it's understandable that they're missing. Not a big problem.

> I also cleaned up the commits for all of these, sorry I let that get out of hand

No problem at all :)

**Comment by problemv** [comment]
@jtopjian this is ready for review again.

**Pull request merged**
