### PR TITLE
compute/v2: Hypervisors List API

### PR DESCRIPTION
**Pull request by jtopjian**
For #179
Supersedes #178

### CODE REVIEW

**Comment by jtopjian** [comment]
@jrperritt Quick question: SinglePage returns still follow the same `EachPage` and `AllPage` patterns as other page types, right? Other SinglePage returns in Gophercloud are doing this, just want to explicitly ask :)

**Comment by jrperritt** [comment]
Yes. `AllPages` returns immediately for `SinglePage`s (with the first (and only) page).

**Comment by jtopjian** [comment]
This looks good to me. I'm going to go ahead and merge it. @spjmurray Thank you for your work on this :)

**Comment by jtopjian** [comment]
Ping @majewsky - This might be useful for Limes (which I'm looking at because we have a similar in-house quota management system 😄 )

**Comment by majewsky** [comment]
Thanks for pinging. @auhlig Do you want to adjust the Nova capacity plugin to take advantage of this?

Re Limes, I'd be delighted to see someone outside SAP use it. If you have any questions or requirements, feel free to open an issue over in our repo.

**Comment by auhlig** [comment]
Sure. Thanks for the hint @majewsky

**Pull request merged**
