### PR TITLE
Add container dict, host, status_reason field to capsule

### PR DESCRIPTION
**Pull request by kevin-zhaoshuai**
For #700 

Container: https://review.openstack.org/565085
Host: https://review.openstack.org/564695
Status_reason is already inside the return value before.

### CODE REVIEW

**Comment by jtopjian** [comment]
Looks like Travis is flagging some `gofmt` issues. If possible, it's usually easiest to configure your editor to run `gofmt` upon saving.

**Comment by kevin-zhaoshuai** [comment]
@jtopjian  Thanks I’ve modified. 
I will address your comments to the editor

**Comment by jtopjian** [comment]
Sounds good :)

Let me know if/when this is ready for review as well as any other Zun PRs that are ready, too.

**Comment by kevin-zhaoshuai** [comment]
@jtopjian Thanks! Ping for review

**Pull request merged**
