### PR TITLE
Feature/filestorage sharenetworks get

### PR DESCRIPTION
**Pull request by ehdou**
Add support for Share Network Get
For #130

### CODE REVIEW

**Comment by ehdou** [comment]
[Get function](https://github.com/openstack/manila/blob/16c522bf5e5c3d37018caef11dd7852462193327/manila/api/v1/share_networks.py#L50) from the Manila code

**Comment by ehdou** [comment]
@jrperritt This PR is ready for review. It's based on [PR#124](https://github.com/gophercloud/gophercloud/pull/124) and add support for get

**Comment by mvalkon** [comment]
@ehdou please replace #114 with #130 in the PR description.

**Comment by ehdou** [comment]
@jrperritt This PR has been rebased and is ready for review

**Comment by jrperritt** [comment]
+2

**Pull request merged**
