### PR TITLE
update live migrate api with microversion 2.25

### PR DESCRIPTION
**Pull request by snigle**
For #2197

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

https://github.com/gophercloud/gophercloud/blob/master/openstack/compute/v2/extensions/migrate/requests.go#L30

https://docs.openstack.org/api-ref/compute/?expanded=live-migrate-server-os-migratelive-action-detail#live-migrate-server-os-migratelive-action

### CODE REVIEW

**Review by EmilienM — APPROVED** [review]

**Review by mandre — APPROVED** [review]
LGTM.
@EmilienM is there anything we're waiting for to merge this patch?

**Comment by pierreprinetti** [comment]
Type change is a breaking change.
cf.: https://go.dev/play/p/b4su08crVCn

**Comment by EmilienM** [comment]
could you please rebase it so we can run the CI jobs for Compute. Thanks

**Comment by snigle** [comment]
> could you please rebase it so we can run the CI jobs for Compute. Thanks

Hello rebase is done, should be ready to merge \o/ :)

**Comment by pierreprinetti** [comment]
@snigle If you were to redesign the `BlockMigration` field from scratch, what type would it be?

**Comment by snigle** [comment]
Could be an enum ?

**Comment by mohammadne** [comment]
Any progress?

**Comment by EmilienM** [comment]
This PR has been staled for a very long time, I'll close it. Feel free to re-open!

**Comment by snigle** [comment]
Hello for what are you waiting for ? You don't want breaking change so put interface, but you want an enum ? Just as a constant for auto ?

**Pull request closed without merging**
