### PR TITLE
Identity V3: List Policies

### PR DESCRIPTION
**Pull request by zhangzujian**
For #972 

API reference:
[Identity API v3 - List Policies](https://developer.openstack.org/api-ref/identity/v3/#list-policies)

Python source code:
https://github.com/openstack/keystone/blob/master/keystone/policy/routers.py#L21
https://github.com/openstack/keystone/blob/master/keystone/policy/controllers.py#L51
https://github.com/openstack/keystone/blob/master/keystone/policy/core.py#L57
https://github.com/openstack/python-keystoneclient/blob/master/keystoneclient/v3/policies.py#L82

Acceptance testing will be added after other policy APIs are supported.

### CODE REVIEW

**Comment by zhangzujian** [comment]
Ready for review.

**Comment by jtopjian** [comment]
@zhangzujian This looks perfect - nice work :)

Would it be possible to include an acceptance test?

**Comment by jtopjian** [comment]
err - sorry, I just read this note:

> Acceptance testing will be added after other policy APIs are supported.

It's OK if no policies are returned. The test will simply verify the List call works without error. Later when it's possible to create policies, we can redo the List test.

**Comment by jtopjian** [comment]
@zhangzujian Thank you :)

I'll wait until the OpenLab tests are done. If it fails, that's OK -- it's a separate issue. I've tested this myself and it works.

**Pull request merged**
