### PR TITLE
Containers v1: Implement Capsules Microversion 1.32

### PR DESCRIPTION
**Pull request by jtopjian**
For #1468 
Supersedes #1456

### CODE REVIEW

**Comment by jtopjian** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by jtopjian** [comment]
@hongbin I'm having some issues with this.

It seems that no matter what microversion I specify, the microversion 1.32 version of Capsule is always being returned:

```
=== RUN   TestCapsule
2019/02/23 06:28:09 [DEBUG] OpenStack Request URL: POST http://zun:9517/v1/capsules
2019/02/23 06:28:09 [DEBUG] OpenStack request Headers:
Accept: application/json
Content-Type: application/json
Openstack-Api-Version: container 1.1
User-Agent: gophercloud/2.0.0
X-Auth-Token: ***
2019/02/23 06:28:09 [DEBUG] OpenStack Request Body: {
  "template": "\n\t{\n\t\t\"capsuleVersion\": \"beta\",\n\t\t\"kind\": \"capsule\",\n\t\t\"metadata\": {\n\t\t\t\"labels\": {\n\t\t\t\t\"app\": \"web\",\n\t\t\t\t\"app1\": \"web1\"\n\t\t\t},\n\t\t\t\"name\": \"t
emplate\"\n\t\t},\n\t\t\"spec\": {\n\t\t\t\"restartPolicy\": \"Always\",\n\t\t\t\"containers\": [\n\t\t\t\t{\n\t\t\t\t\t\"command\": [\n\t\t\t\t\t\t\"sleep\",\n\t\t\t\t\t\t\"1000000\"\n\t\t\t\t\t],\n\t\t\t\t\t\"
env\": {\n\t\t\t\t\t\t\"ENV1\": \"/usr/local/bin\",\n\t\t\t\t\t\t\"ENV2\": \"/usr/bin\"\n\t\t\t\t\t},\n\t\t\t\t\t\"image\": \"ubuntu\",\n\t\t\t\t\t\"imagePullPolicy\": \"ifnotpresent\",\n\t\t\t\t\t\"ports\": [\n
\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\"containerPort\": 80,\n\t\t\t\t\t\t\t\"hostPort\": 80,\n\t\t\t\t\t\t\t\"name\": \"nginx-port\",\n\t\t\t\t\t\t\t\"protocol\": \"TCP\"\n\t\t\t\t\t\t}\n\t\t\t\t\t],\n\t\t\t\t\t\"resour
ces\": {\n\t\t\t\t\t\t\"requests\": {\n\t\t\t\t\t\t\t\"cpu\": 1,\n\t\t\t\t\t\t\t\"memory\": 1024\n\t\t\t\t\t\t}\n\t\t\t\t\t},\n\t\t\t\t\t\"workDir\": \"/root\"\n\t\t\t\t}\n\t\t\t]\n\t\t}\n\t}\n"
}
2019/02/23 06:28:11 [DEBUG] OpenStack Response Code: 202
2019/02/23 06:28:11 [DEBUG] OpenStack Response Headers:
Content-Length: 641
Content-Type: application/json
Date: Sat, 23 Feb 2019 06:28:11 GMT
Location: http://zun:9517/v1/capsules/e3b5e87e-8326-46df-83e9-deb5ab50a1e2
Openstack-Api-Maximum-Version: container 1.32
Openstack-Api-Minimum-Version: container 1.1
Openstack-Api-Version: container 1.1
Vary: OpenStack-API-Version
X-Openstack-Request-Id: req-121edf99-7b03-4993-9a07-4719e30d03a6
2019/02/23 06:28:11 [DEBUG] OpenStack Response Body: {
  "addresses": null,
  "cpu": 1,
  "created_at": "2019-02-23 06:28:10.135901",
  "host": null,
  "labels": {
    "app": "web",
    "app1": "web1"
  },
  "links": [
    {
      "href": "http://zun:9517/v1/capsules/e3b5e87e-8326-46df-83e9-deb5ab50a1e2",
      "rel": "self"
    },
    {
      "href": "http://zun:9517/capsules/e3b5e87e-8326-46df-83e9-deb5ab50a1e2",
      "rel": "bookmark"
    }
  ],
  "memory": "1024",
  "name": "template",
  "project_id": "20c6b343b2b8453d92018a8654343589",
  "restart_policy": {
    "MaximumRetryCount": "0",
    "Name": "always"
  },
  "status": "Creating",
  "status_reason": null,
  "updated_at": null,
  "user_id": "5c70d99f4a8641c38f8084b32b5e5c0e",
  "uuid": "e3b5e87e-8326-46df-83e9-deb5ab50a1e2"
}
--- FAIL: TestCapsule (2.00s)
panic: interface conversion: interface {} is *capsules.CapsuleV132, not capsules.Capsule [recovered]
        panic: interface conversion: interface {} is *capsules.CapsuleV132, not capsules.Capsule
```

Unless I explicitly specify microversion 1.32+, I would expect `restart_policy` to only be a string.

**Comment by jtopjian** [comment]
I've temporarily disabled Zun/Container acceptance testing in master so that we can begin looking at test results again. I've re-enabled the acceptance tests in this PR so functionality/fixes can be verified.

**Comment by hongbin** [comment]
> @hongbin I'm having some issues with this.
> 
> It seems that no matter what microversion I specify, the microversion 1.32 version of Capsule is always being returned:
> 
> ```
> === RUN   TestCapsule
> 2019/02/23 06:28:09 [DEBUG] OpenStack Request URL: POST http://zun:9517/v1/capsules
> 2019/02/23 06:28:09 [DEBUG] OpenStack request Headers:
> Accept: application/json
> Content-Type: application/json
> Openstack-Api-Version: container 1.1
> User-Agent: gophercloud/2.0.0
> X-Auth-Token: ***
> 2019/02/23 06:28:09 [DEBUG] OpenStack Request Body: {
>   "template": "\n\t{\n\t\t\"capsuleVersion\": \"beta\",\n\t\t\"kind\": \"capsule\",\n\t\t\"metadata\": {\n\t\t\t\"labels\": {\n\t\t\t\t\"app\": \"web\",\n\t\t\t\t\"app1\": \"web1\"\n\t\t\t},\n\t\t\t\"name\": \"t
> emplate\"\n\t\t},\n\t\t\"spec\": {\n\t\t\t\"restartPolicy\": \"Always\",\n\t\t\t\"containers\": [\n\t\t\t\t{\n\t\t\t\t\t\"command\": [\n\t\t\t\t\t\t\"sleep\",\n\t\t\t\t\t\t\"1000000\"\n\t\t\t\t\t],\n\t\t\t\t\t\"
> env\": {\n\t\t\t\t\t\t\"ENV1\": \"/usr/local/bin\",\n\t\t\t\t\t\t\"ENV2\": \"/usr/bin\"\n\t\t\t\t\t},\n\t\t\t\t\t\"image\": \"ubuntu\",\n\t\t\t\t\t\"imagePullPolicy\": \"ifnotpresent\",\n\t\t\t\t\t\"ports\": [\n
> \t\t\t\t\t\t{\n\t\t\t\t\t\t\t\"containerPort\": 80,\n\t\t\t\t\t\t\t\"hostPort\": 80,\n\t\t\t\t\t\t\t\"name\": \"nginx-port\",\n\t\t\t\t\t\t\t\"protocol\": \"TCP\"\n\t\t\t\t\t\t}\n\t\t\t\t\t],\n\t\t\t\t\t\"resour
> ces\": {\n\t\t\t\t\t\t\"requests\": {\n\t\t\t\t\t\t\t\"cpu\": 1,\n\t\t\t\t\t\t\t\"memory\": 1024\n\t\t\t\t\t\t}\n\t\t\t\t\t},\n\t\t\t\t\t\"workDir\": \"/root\"\n\t\t\t\t}\n\t\t\t]\n\t\t}\n\t}\n"
> }
> 2019/02/23 06:28:11 [DEBUG] OpenStack Response Code: 202
> 2019/02/23 06:28:11 [DEBUG] OpenStack Response Headers:
> Content-Length: 641
> Content-Type: application/json
> Date: Sat, 23 Feb 2019 06:28:11 GMT
> Location: http://zun:9517/v1/capsules/e3b5e87e-8326-46df-83e9-deb5ab50a1e2
> Openstack-Api-Maximum-Version: container 1.32
> Openstack-Api-Minimum-Version: container 1.1
> Openstack-Api-Version: container 1.1
> Vary: OpenStack-API-Version
> X-Openstack-Request-Id: req-121edf99-7b03-4993-9a07-4719e30d03a6
> 2019/02/23 06:28:11 [DEBUG] OpenStack Response Body: {
>   "addresses": null,
>   "cpu": 1,
>   "created_at": "2019-02-23 06:28:10.135901",
>   "host": null,
>   "labels": {
>     "app": "web",
>     "app1": "web1"
>   },
>   "links": [
>     {
>       "href": "http://zun:9517/v1/capsules/e3b5e87e-8326-46df-83e9-deb5ab50a1e2",
>       "rel": "self"
>     },
>     {
>       "href": "http://zun:9517/capsules/e3b5e87e-8326-46df-83e9-deb5ab50a1e2",
>       "rel": "bookmark"
>     }
>   ],
>   "memory": "1024",
>   "name": "template",
>   "project_id": "20c6b343b2b8453d92018a8654343589",
>   "restart_policy": {
>     "MaximumRetryCount": "0",
>     "Name": "always"
>   },
>   "status": "Creating",
>   "status_reason": null,
>   "updated_at": null,
>   "user_id": "5c70d99f4a8641c38f8084b32b5e5c0e",
>   "uuid": "e3b5e87e-8326-46df-83e9-deb5ab50a1e2"
> }
> --- FAIL: TestCapsule (2.00s)
> panic: interface conversion: interface {} is *capsules.CapsuleV132, not capsules.Capsule [recovered]
>         panic: interface conversion: interface {} is *capsules.CapsuleV132, not capsules.Capsule
> ```
> Unless I explicitly specify microversion 1.32+, I would expect `restart_policy` to only be a string.

I just merged a fix for that: https://review.openstack.org/#/c/638856/ . Let me know if it works.

**Comment by hongbin** [comment]
recheck

**Comment by hongbin** [comment]
Before the fix [1], the CI failed with this error:

  2019-02-23 18:28:34.276048 | ubuntu-xenial | panic: interface conversion: interface {} is *capsules.CapsuleV132, not capsules.Capsule [recovered]
  2019-02-23 18:28:34.276159 | ubuntu-xenial | 	panic: interface conversion: interface {} is *capsules.CapsuleV132, not capsules.Capsule

After the fix, the CI failed with this error:

  2019-02-24 01:00:49.441023 | ubuntu-xenial | panic: interface conversion: interface {} is *capsules.Capsule, not capsules.Capsule [recovered]
  2019-02-24 01:00:49.441191 | ubuntu-xenial | 	panic: interface conversion: interface {} is *capsules.Capsule, not capsules.Capsule

Will look into why.

[1] https://review.openstack.org/#/c/638856/

**Comment by jtopjian** [comment]
The new error is most likely an error in the test. I can look into this
shortly.

Thank you so much for looking into this!

**Comment by hongbin** [comment]
NP. As always. Just let me know if anything I can help.

**Comment by jtopjian** [comment]
@hongbin Looks like everything is working 🙂 

I extended the implementation a little. If you use the `Extract` method and `ExtractCapsules` function, they will now return an `interface{}` which you can cast to a specific type:

```go
		if capsule, ok := v.(*capsules.Capsule); ok {
			newStatus = capsule.Status
		}

		if capsule, ok := v.(*capsules.CapsuleV132); ok {
			newStatus = capsule.Status
		}
```

Or you can use the `ExtractBase` / `ExtractV132` methods and `ExtractCapsulesBase` / `ExtractCapsulesV132` functions to directly gain access to one capsule format or the other.

Let me know what you think and/or if you have any questions/concerns.

**Comment by hongbin** [comment]
@jtopjian Cool. The change look pretty good to me.

I like the idea of having Extract* handle two microversion and returning a generic interface. It is better than having two Extract* methods IMO.

Thanks for your nice work on this PR.

**Comment by jtopjian** [comment]
Sounds good. Thank you for your help with this!

**Pull request merged**
