### PR TITLE
[neutron]: introduce Stateful argument for the security groups

### LINKED ISSUE #3091: Add stateful argument to security groups
https://docs.openstack.org/api-ref/network/v2/?expanded=create-port-detail#create-security-group

required by https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1735

### PR DESCRIPTION
**Pull request by kayrus**
Prior to starting a PR, please make sure you have read our
[contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial).

Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

Fixes #3091 

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

https://github.com/openstack/neutron-lib/blob/47e1736c10ffd6f1850eba9970acdc00373f9de7/neutron_lib/api/definitions/stateful_security_group.py#L36-L42

### CODE REVIEW

**Comment by EmilienM** [comment]
Since this is a breaking API change, I wonder if we shouldn't document it right away and explain the migration in MIGRATING.md or something cc @stephenfin @pierreprinetti

**Comment by kayrus** [comment]
@EmilienM hm, this is not a breaking change. The change is absolutely backwards compatible.

**Comment by mandre** [comment]
> @EmilienM hm, this is not a breaking change. The change is absolutely backwards compatible.

We changed the signature of `List()` to take a `ListOptsBuilder` rather than a `ListOpts`.

You can check [the output of `go-apidiff`](https://github.com/gophercloud/gophercloud/actions/runs/9862825141/job/27234249856?pr=3092#step:7:54), with what seems like a small reporting issue:
```
github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/security/groups
  Incompatible changes:
  - ListOpts: changed from ListOpts to ListOpts
  Compatible changes:
  - CreateOpts.Stateful: added
  - ListOptsBuilder: added
  - SecGroup.Stateful: added
  - UpdateOpts.Stateful: added'
```

**Comment by kayrus** [comment]
@mandre since `ListOpts` completely satisfies the new `ListOptsBuilder`, from my perspective this is backwards compatible. So new dependency will compile with the app, which was previously compiled with an old dependency.

**Comment by mandre** [comment]
> @mandre since `ListOpts` completely satisfies the new `ListOptsBuilder`, from my perspective this is backwards compatible. So new dependency will compile with the app, which was previously compiled with an old dependency.

Right, so this could be a bug in [go-apidiff](https://github.com/joelanford/go-apidiff).

**Comment by pierreprinetti** [comment]
Merging this PR means that we now need a `v2` branch and the related backport machinery! :sweat_smile: 
@mandre @EmilienM @kayrus

**Comment by pierreprinetti** [comment]
@kayrus 

> @mandre since `ListOpts` completely satisfies the new `ListOptsBuilder`, from my perspective this is backwards compatible. So new dependency will compile with the app, which was previously compiled with an old dependency.

You changed a function signature, which means that you're breaking a statement like this one:
```Go
var myFunc func(*gophercloud.ServiceClient, secgroup.ListOpts) = secgroup.List
```

**Comment by kayrus** [comment]
@pierreprinetti haven't thought about this, but fair enough. However it's not clear in how many places you can see such patterns.

**Comment by kayrus** [comment]
@pierreprinetti shall I revert this PR?

**Comment by pierreprinetti** [comment]
>it's not clear in how many places you can see such patterns

What do you mean?

**Comment by kayrus** [comment]
@pierreprinetti I'm going to create a v2 branch with a corresponding backport automation.

**Pull request merged**
