### PR TITLE
Add empty strings update acceptance tests

### PR DESCRIPTION
**Pull request by kayrus**
Due to [#1343](https://github.com/gophercloud/gophercloud/pull/1343#discussion_r239680996) it appeared that some tests are not executed in devstack environment. Thus code changes from #1341 were not reflected in acceptance tests. Though we made a decision to perform empty strings tests in terraform, I started to fix tests and decided to put empty strings tests as well.

Additionally this PR covers #1344

### CODE REVIEW

**Comment by jtopjian** [comment]
recheck

**Comment by kayrus** [comment]
@jtopjian No need to recheck. The initial test output gave me an overview about devstack capabilities. I'll update the commit soon reflecting the [job-output.txt.gz](http://logs.openlabtesting.org/logs/47/1347/37127b984e8e04504b64547f03d0994e2391041a/check/gophercloud-acceptance-test/6c1cc98/job-output.txt.gz)

**Comment by jtopjian** [comment]
@kayrus ah! Yes, I now see there were changes made to `script/acceptancetest`. If you're able to enable new services for testing, that's great, but let's have separate PRs for that rather than go down a rabbit hole.

**Comment by kayrus** [comment]
@jtopjian That was the purpose for initial test: to identify the pain points. I disabled them. Let's see new test results.

**Comment by jtopjian** [comment]
@kayrus Sounds good. Feel free to poke around with the testing infrastructure and let me know if you need any help 😄

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
Ready for review/merge.

**Comment by jtopjian** [comment]
Even though this failed, I think it's OK. It was due to not being able to do a `go get` on the yaml package. Looks to be a temporary issue.

**Pull request merged**
