### PR TITLE
Acc Tests: Modify some tests to skip some releases

### PR DESCRIPTION
**Pull request by jtopjian**
For https://github.com/theopenlab/openlab/issues/305

### CODE REVIEW

**Comment by jtopjian** [comment]
recheck stable/mitaka

**Comment by jtopjian** [comment]
recheck stable/newton

**Comment by jtopjian** [comment]
recheck stable/pike

**Comment by jtopjian** [comment]
recheck stable/queens

**Comment by jtopjian** [comment]
recheck

**Comment by huangtianhua** [comment]
recheck stable/rocky

**Comment by huangtianhua** [comment]
recheck stable/ocata

**Comment by jtopjian** [comment]
recheck stable/ocata

**Comment by jtopjian** [comment]
recheck stable/pike

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
recheck stable/ocata

**Comment by jtopjian** [comment]
recheck stable/pike

**Comment by jtopjian** [comment]
recheck stable/newton

**Comment by jtopjian** [comment]
recheck stable/queens

**Comment by jtopjian** [comment]
recheck stable/queens

**Comment by jtopjian** [comment]
@huangtianhua Do you know why tests for Queens and Newton are failing so quickly?

**Comment by huangtianhua** [comment]
@jtopjian, sorry to reply so late, for queens there is a bug of octavia, the devstack can not be installed successful. And these days I am trying to fix the problem of devstack installing for mitaka and newton, if octavia enabled, devstack can't be install success.  But seems it's not easy, there are too many problems and maybe it would not have supported it. So why you enable octavia for all stable branches? Can we only to enable octavia for stein and master?

**Comment by jtopjian** [comment]
> Can we only to enable octavia for stein and master?

Yes, let's do that :)

**Comment by jtopjian** [comment]
recheck stable/ocata

**Comment by jtopjian** [comment]
recheck stable/queens

**Comment by jtopjian** [comment]
@huangtianhua Is there something that needs to be done on OpenLab's side to disable Octavia for Queens?

**Comment by huangtianhua** [comment]
@jtopjian sorry reply so late. Yes, we have to modify the role in OpenLab site, and I will propose a pr to do this.

**Comment by huangtianhua** [comment]
Waiting https://github.com/theopenlab/openlab-zuul-jobs/pull/585 merged.

**Comment by huangtianhua** [comment]
theopenlab/openlab-zuul-jobs#585  merged.

**Comment by huangtianhua** [comment]
recheck stable/queens

**Comment by huangtianhua** [comment]
recheck stable/mitaka

**Comment by huangtianhua** [comment]
recheck stable/newton

**Comment by huangtianhua** [comment]
recheck stable/rocky

**Comment by huangtianhua** [comment]
@jtopjian There are many barbican tests failed, now we enable barbican plugin only if lbaas or octavia enabled, it seems a problem for the branches that unsupport ocatavia tests, so I proposed a pr https://github.com/theopenlab/openlab-zuul-jobs/pull/593 to enable barbican individually, after it merged, you have to add barbican in enable_services in your pr:  https://github.com/gophercloud/gophercloud/blob/master/.zuul/playbooks/gophercloud-acceptance-test/run.yaml#L7

**Comment by huangtianhua** [comment]
@jtopjian  Are you around? https://github.com/theopenlab/openlab-zuul-jobs/pull/593 has been merged, so could you please to add 'barbican' to 'enable_services' in https://github.com/gophercloud/gophercloud/blob/master/.zuul/playbooks/gophercloud-acceptance-test/run.yaml#L7, then we can recheck for m,n and q branches. Thank you.

**Comment by jtopjian** [comment]
@huangtianhua I'm so sorry for the delay. I'll take a look at this now. Thank you so much!

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
@huangtianhua I tried to enable Barbican but am getting the following error:

```
[ERROR] /opt/stack/new/devstack/functions-common:1653 Plugin attempted to be enabled twice: barbican https://opendev.org/openstack/barbican masternon-zero return code
```

I will remove it from `run.yaml` and see if tests begin to pass.

**Comment by jtopjian** [comment]
recheck stable/mitaka

**Comment by jtopjian** [comment]
recheck stable/newton

**Comment by jtopjian** [comment]
recheck stable/mitaka

**Comment by jtopjian** [comment]
recheck stable/mitaka

**Comment by jtopjian** [comment]
recheck stable/newton

**Comment by jtopjian** [comment]
recheck stable/newton

**Comment by jtopjian** [comment]
recheck stable/ocata

**Comment by jtopjian** [comment]
recheck stable/ocata

**Comment by jtopjian** [comment]
recheck stable/pike

**Comment by jtopjian** [comment]
recheck stable/queens

**Comment by jtopjian** [comment]
recheck stable/pike

**Comment by jtopjian** [comment]
recheck stable/queens

**Comment by jtopjian** [comment]
recheck stable/queens

**Comment by jtopjian** [comment]
recheck stable/queens

**Comment by jtopjian** [comment]
recheck stable/queens

**Comment by jtopjian** [comment]
recheck stable/rocky

**Comment by jtopjian** [comment]
recheck stable/stein

**Comment by jtopjian** [comment]
recheck stable/stein

**Pull request merged**
