### PR TITLE
Acc Tests: Removing Trusty

### PR DESCRIPTION
**Pull request by jtopjian**
For #1831

### CODE REVIEW

**Comment by bzhaoopenstack** [comment]
recheck

**Comment by bzhaoopenstack** [comment]
recheck

**Comment by bzhaoopenstack** [comment]
recheck

**Comment by bzhaoopenstack** [comment]
recheck

**Comment by bzhaoopenstack** [comment]
gophercloud has not a protect branch. So here miss https://github.com/gophercloud/gophercloud/blob/zun-exp/.zuul.yaml  need to be change also

**Comment by bzhaoopenstack** [comment]
recheck

**Comment by wangxiyuan** [comment]
> gophercloud has not a protect branch. So here miss https://github.com/gophercloud/gophercloud/blob/zun-exp/.zuul.yaml need to be change also

@jtopjian how about remove the .zuul.yml on zun-exp branch? there is no update from 7th Mar 2018

**Comment by jtopjian** [comment]
@wangxiyuan Done!

**Comment by bzhaoopenstack** [comment]
recheck

**Comment by bzhaoopenstack** [comment]
recheck

**Comment by bzhaoopenstack** [comment]
recheck

**Comment by bzhaoopenstack** [comment]
recheck

**Comment by bzhaoopenstack** [comment]
@jtopjian Hi, this part is ready to merge now. ;-). Thanks for your patience and kind help.

**Pull request merged**
