### PR TITLE
Compute V2: Display error message when 400 Bad Request.

### PR DESCRIPTION
**Pull request by takaishi**
For #243

- https://github.com/openstack/nova/blob/015870d05d7e0848a6d0d9d275370890ee3b9829/nova/api/openstack/wsgi.py#L1010
- https://github.com/openstack/nova/blob/015870d05d7e0848a6d0d9d275370890ee3b9829/nova/api/openstack/wsgi.py#L1035-L1045

### CODE REVIEW

**Comment by takaishi** [comment]
@jtopjian This PR is ready to review.

**Comment by jtopjian** [comment]
I'll defer this one to @jrperritt for when he has time.

**Comment by jrperritt** [comment]
After skimming the code, it looks good, but this what you're trying to achieve here is what I intended the default behaviour to be. That is, you shouldn't need create many custom errors. If it's not already doing that, the problem is further up in the error handling. I'll take a look at it within the next week.

**Comment by databus23** [comment]
@jrperritt Any chance we can proceed on this? not sure what you mean with solving this *further up* in the error handling. getting the actual error message from a server create call is very helpful because otherwise without access to the nova logs there is no way of telling what was rejected by the service.

**Comment by databus23** [comment]
@jrperritt Any chance to get some feedback on this PR? How can we proceed on this?

**Comment by jtopjian** [comment]
This was resolved in #703

**Pull request closed without merging**
