### PR TITLE
[Neutron][Network] updated_at/created_at fields

### PR DESCRIPTION
**Pull request by naumvd95**
for: #1655

* time.Time object
* mapped to existing json fields

General API reference:https://docs.openstack.org/api-ref/network/v2/?expanded=show-network-details-detail#show-network-details

that fields defined in standard_attr.py , that means that it should be applied to all neutron-resources though decorator:
https://github.com/openstack/neutron/blob/041203f1bb1a9cb814ab58c6088d0229cfe9d9bb/neutron/db/standard_attr.py#L181
https://github.com/openstack/neutron/blob/041203f1bb1a9cb814ab58c6088d0229cfe9d9bb/neutron/db/models_v2.py#L253

### CODE REVIEW

**Comment by naumvd95** [comment]
@jtopjian  ready for review. Faced with acceptance test failures, again
`task name   “name”: “Install devstack on master branch”`

```
2019-07-28 12:51:42.626901 | ubuntu-xenial | + /tmp/ansible/bin/ansible primary -f 5 -i /home/zuul/workspace/inventory -m shell -a 'cd '\''/opt/stack/new/devstack'\'' && sudo -H -u stack DSTOOLS_VERSION=0.4.0 stdbuf -oL -eL ./stack.sh 2>&1 executable=/bin/bash'
2019-07-28 12:52:03.608756 | ubuntu-xenial | ERROR: the main setup script run by this job failed - exit code: 2
2019-07-28 12:52:03.609147 | ubuntu-xenial |     please look at the relevant log files to determine the root cause
2019-07-28 12:52:03.609204 | ubuntu-xenial | Running devstack worlddump.py
2019-07-28 12:52:03.665293 | ubuntu-xenial | /bin/sh: 1: brctl: not found
2019-07-28 12:52:04.398642 | ubuntu-xenial | Cleaning up host
2019-07-28 12:52:04.398770 | ubuntu-xenial | ... this takes 3 - 4 minutes (logs at logs/devstack-gate-cleanup-host.txt.gz)
2019-07-28 12:52:31.012983 | ubuntu-xenial |  [WARNING]: Could not match supplied host pattern, ignoring: subnodes
2019-07-28 12:52:31.013420 | ubuntu-xenial |  [WARNING]: No hosts matched, nothing to do
2019-07-28 12:52:34.611988 | ubuntu-xenial | Done.
2019-07-28 12:52:36.041992 | ubuntu-xenial | *** FAILED with status: 2
2019-07-28 12:52:46.350400 | ubuntu-xenial | ERROR
2019-07-28 12:52:46.351084 | ubuntu-xenial | {
2019-07-28 12:52:46.351205 | ubuntu-xenial |   "delta": "0:04:35.980983",
2019-07-28 12:52:46.351303 | ubuntu-xenial |   "end": "2019-07-28 12:52:36.045609",
2019-07-28 12:52:46.351394 | ubuntu-xenial |   "msg": "non-zero return code",
2019-07-28 12:52:46.351512 | ubuntu-xenial |   "rc": 2,
2019-07-28 12:52:46.351602 | ubuntu-xenial |   "start": "2019-07-28 12:48:00.064626"
2019-07-28 12:52:46.351687 | ubuntu-xenial | }
2019-07-28 12:52:46.388804 | 
2019-07-28 12:52:46.389119 | PLAY RECAP
2019-07-28 12:52:46.389278 | ubuntu-xenial | ok: 16 changed: 13 unreachable: 0 failed: 1
```
seems it does not correlate with my changes, can anybody take a look and advice?
thanks in advance!!!

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Comment by naumvd95** [comment]
@jtopjian seems everything is ok?

**Pull request merged**
