### PR TITLE
Feature/filestorage securityservices get

### PR DESCRIPTION
**Pull request by ehdou**
Add support for Security Service Get
For #131

### CODE REVIEW

**Comment by ehdou** [comment]
[Show function](https://github.com/openstack/manila/blob/16c522bf5e5c3d37018caef11dd7852462193327/manila/api/v1/security_service.py#L41) for security services

**Comment by ehdou** [comment]
@jrperritt This PR is ready for review. It's based on [PR#134](https://github.com/gophercloud/gophercloud/pull/134) and adds support for security service Get

**Comment by ehdou** [comment]
@jrperritt This PR is ready for review

**Comment by jtopjian** [comment]
This looks good to me :)

**Pull request merged**
