### PR TITLE
Fwaasv2 firewall groups acc tests (depends on #2049)

### PR DESCRIPTION
**Pull request by codemanufaktur**
For #514

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

https://github.com/openstack/neutron-fwaas/blob/stable/ussuri/neutron_fwaas/db/firewall/v2/firewall_db_v2.py#L85-L103
https://github.com/openstack/neutron-fwaas/blob/stable/ussuri/neutron_fwaas/db/firewall/v2/firewall_db_v2.py#L307:L322
https://github.com/openstack/neutron-fwaas/blob/stable/ussuri/neutron_fwaas/services/firewall/fwaas_plugin_v2.py#L313-L369

**this PR:
Acceptance test for fwaasv2 firewall groups**

kind regards, 
Georg

<sub>Georg Schreiber georg.g.schreiber@daimler.com, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Comment by codemanufaktur** [comment]
fixing...

**Comment by jtopjian** [comment]
@codemanufaktur Unfortunately the testing environment is not configured for FWaaS v2. Are you able to provide the output of these unit tests with the `OS_DEBUG=1` environment variable set? Please make sure to censor/sanitize any important information.

The output might be long, so perhaps a GitHub Gist is the best method of sharing.

Please let me know if you have any questions or problems.

**Comment by codemanufaktur** [comment]
@jtopjian sure, here is the output of acceptance/openstack/networking/v2/extensions/fwaas_v2/groups_test.go: [gist](https://gist.github.com/codemanufaktur/effb57448405407a8b5c0d71b730a312)

**Comment by jtopjian** [comment]
@codemanufaktur Thanks!

As far as I can tell, the whole series of PRs is good and we can look at just squashing and merging this one. Thank you for your work with all of the API calls.

The last thing I'd like to confirm is if paging is working correctly. Unfortunately I don't have a FWaaSv2 environment available and since the testing environment doesn't support FWaaSv2, would you mind testing this? I apologize for the extra work - this is something I usually do myself with PRs.

The easiest way to test this is if you create a few groups and then list them using a `ListOpts.Limit` of 1. Something like:

```go
listOpts := groups.ListOpts{
  Limit: 1,
}

allPages, err := groups.List(client, listOpts).AllPages()
```

In the debug output, you should be able to see multiple GET requests. For example, if you create 3 groups, then there should be 3 GET requests, the first two having links for the next page.

**Comment by codemanufaktur** [comment]
> @codemanufaktur Thanks!
> 
> As far as I can tell, the whole series of PRs is good and we can look at just squashing and merging this one. Thank you for your work with all of the API calls.
> 
> The last thing I'd like to confirm is if paging is working correctly. Unfortunately I don't have a FWaaSv2 environment available and since the testing environment doesn't support FWaaSv2, would you mind testing this? I apologize for the extra work - this is something I usually do myself with PRs.
> 
> The easiest way to test this is if you create a few groups and then list them using a `ListOpts.Limit` of 1. Something like:
> 
> ```go
> listOpts := groups.ListOpts{
>   Limit: 1,
> }
> 
> allPages, err := groups.List(client, listOpts).AllPages()
> ```
> 
> In the debug output, you should be able to see multiple GET requests. For example, if you create 3 groups, then there should be 3 GET requests, the first two having links for the next page.

I have 1 default firewall group, created 4 additional firewall groups and listed them with `Limit: 1`. I see 5 GET requests in the [debug-output](https://gist.github.com/codemanufaktur/0c3092222ff1b701d11a5eb3de958674). I think paging is working as expected.

**Comment by codemanufaktur** [comment]
@jtopjian paging looks ok imho. I squashed my 4 commits to one, hope the commit message looks OK :-)

**Review by jtopjian — APPROVED** [review]
LGTM - thank you for your patience and help with this.

**Pull request merged**
