### PR TITLE
Vpnaas: Delete service

### PR DESCRIPTION
**Pull request by simonre**
For #723 

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L512

API:
https://developer.openstack.org/api-ref/network/v2/#remove-vpn-service

### CODE REVIEW

**Comment by jtopjian** [comment]
@simonre This will need to be rebased with master when you have a moment. I did a quick glance and it looks fine, but I'll review it again once it's ready to go.

Thanks again for working on this series.

**Comment by simonre** [comment]
@jtopjian I think this is ready. I'm not too familiar with rebasing so please tell me if I did something wrong.

**Comment by jtopjian** [comment]
@simonre 

> I'm not too familiar with rebasing so please tell me if I did something wrong.

Ah, no problem.

The first thing to try would be this:

```shell
$ git checkout master
$ git pull
$ git checkout vpnaas-service-delete
$ git rebase -i master
```

You'll then be prompted with a list of commits. You want to make sure that only the commits for this PR are chosen and remove any other commits from other PRs / merges.

If you want to practice, doing this should work:

```shell
$ git checkout master
$ git pull
$ git checkout vpnaas-service-delete
$ git checkout -b vpnaas-service-delete-rebase-practice
$ git rebase -i master
```

Let me know if you need help and I'll rebase this on my side and provide the steps to walk you through it.

**Comment by simonre** [comment]
@jtopjian This should do it. Thanks for the in-depth answers and explanations. Really appreciate it!

**Comment by jtopjian** [comment]
@simonre Yes, perfect - nice work :smile:

**Pull request merged**
