### PR TITLE
Trove: Support to return Trove instance addresses

### PR DESCRIPTION
**Pull request by lingxiankong**
Closes: #2178

- API response example for getting trove instance :
  https://docs.openstack.org/api-ref/database/?expanded=show-database-instance-details-detail#id52
- Trove code for getting instance addresses:
  https://github.com/openstack/trove/blob/b050996b9f6df738a0f68ac36a5b5f17f8bb2bc2/trove/instance/models.py#L170

### CODE REVIEW

**Comment by jtopjian** [comment]
@lingxiankong This looks good to me. Let me know when you're ready to have it merged.

**Comment by lingxiankong** [comment]
@jtopjian I've no idea why the job `Unit Testing / test (1.15) (pull_request)` failed, but the PR is actually ready for merge unless there is something I need to fix to pass the CI.

**Comment by lingxiankong** [comment]
> @jtopjian I've no idea why the job `Unit Testing / test (1.15) (pull_request)` failed, but the PR is actually ready for merge unless there is something I need to fix to pass the CI.

Never mind, found the problem

**Comment by lingxiankong** [comment]
@jtopjian Ready

**Comment by jtopjian** [comment]
@lingxiankong Good catch. I totally spaced on the unit test error :)

**Review by jtopjian — APPROVED** [review]
LGTM - thank you!

**Pull request merged**
