### PR TITLE
Fix X-Static-Large-Object json unmarshalling

### PR DESCRIPTION
**Pull request by yanndegat**
X-Static-Large-Object json is a string representation of a bool

For #735

### CODE REVIEW

**Comment by jtopjian** [comment]
@yanndegat Thank you for this PR as well, but you must create issues that describe the reasons for the PR as well as point out areas in the OpenStack code (in this case, Swift) which show that the code changes are valid.

**Comment by mrhillsman** [comment]
@yanndegat do you have an issue associated with this PR? If not, please proceed to close it, thank you for resolving.

**Comment by jtopjian** [comment]
This PR escaped me and I never followed up with @yanndegat on it. It looks like a legitimate issue that warrants some investigation, so I've opened #735 as a reference issue.

**Comment by mrhillsman** [comment]
@jtopjian awesome! Thanks for checking in on it.

**Comment by jtopjian** [comment]
Superseded by #945

**Pull request closed without merging**
