### PR TITLE
Fix ErrUnexpectedResponseCode expected OK codes

### PR DESCRIPTION
**Pull request by reenjii**
For #2172

### CODE REVIEW

**Comment by jtopjian** [comment]
@reenjii good catch 🙂 

Are you still working on this or is this ready for review/merge?

**Comment by reenjii** [comment]
> @reenjii good catch 
> 
> Are you still working on this or is this ready for review/merge?

It is ready for review/merge, nothing else to add it's quite straightforward :)

**Comment by jtopjian** [comment]
@reenjii I figured - I just don't like to assume anything 🙂

**Review by jtopjian — APPROVED** [review]
@reenjii LGTM - thank you!

**Pull request merged**
