### PR TITLE
Workflowv2 workflows delete

### PR DESCRIPTION
**Pull request by garbage-collector**
For #1199 

https://github.com/openstack/mistral/blob/master/mistral/api/controllers/v2/workflow.py#L177

### CODE REVIEW

**Comment by jtopjian** [comment]
@garbage-collector Looks like there are some merge conflicts that will need to be resolved here.

**Comment by garbage-collector** [comment]
Merge conflicts fixed, I will have to work on better understanding git next week :)

Thanks !

**Comment by jtopjian** [comment]
@garbage-collector With the above in mind, the best approach to fixing up this PR would be to rebase this branch off of a newly updated Gophercloud master branch and then do a force push:

```shell
$ git checkout master
$ git pull
$ git checkout workflowv2-workflows-delete
$ git rebase -i master
<modify the git history so that all 9 commits will be combined into 1 master "delete" commit>
$ git push -f <origin> workflowv2-workflows-delete
```

If you wanted to practice so you don't accidentally mess up `workflowv2-workflows-delete`:

```shell
$ git checkout master
$ git pull
$ git checkout workflowv2-workflows-delete
$ git checkout -b workflowv2-workflows-delete-practice
$ git rebase -i master
<modify the git history so that all 9 commits will be combined into 1 master "delete" commit>
$ git log
```

**Comment by garbage-collector** [comment]
I rebased and pushed everything regarding your comments, it looks like better now.

Thanks for the tips. I've got still some lack about rebase and squash but I'll try to practice it with the next PRs :)

I'm waiting the merge of this PR before working on workflow-get and workflow-list.

Thanks !

**Pull request merged**
