### PR TITLE
baremetal: add support for servicing

### PR DESCRIPTION
**Pull request by dtantsur**
Adds provision states and parametes for the new "service" provisioning
action. Adds hold states introduced as part of the same effort.

### CODE REVIEW

**Comment by jayofdoom** [comment]
LGTM from an Ironic perspective.

**Comment by elfosardo** [comment]
not enough powers to approve this, but it also looks good to me

**Comment by dtantsur** [comment]
/cc @mandre @mdbooth @pierreprinetti 

Please take a look when you have a minute.

**Review by EmilienM — APPROVED** [review]

**Comment by EmilienM** [comment]
> Labels `semver-major`, `semver-minor` and `semver-unknown` block backports to the legacy branch `v1`.

@pierreprinetti should we have that message only if the label `v1` was added here? In this PR, this is just noise IMO.

**Pull request merged**
