### PR TITLE
support pause/unpause for compute instance

### PR DESCRIPTION
**Pull request by zionwu**
Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #420

### CODE REVIEW

**Comment by jtopjian** [comment]
@zionwu Thanks for submitting this.

Per the PR template and [STYLEGUIDE](https://github.com/gophercloud/gophercloud/blob/master/STYLEGUIDE.md), you need to also include links to the OpenStack Python source code where this functionality is implemented.

**Comment by zionwu** [comment]
@jtopjian 

The following is the OpenStack source code:
pause: https://github.com/openstack/nova/blob/stable/newton/nova/compute/api.py#L3105
unpause: https://github.com/openstack/nova/blob/stable/newton/nova/compute/api.py#L3115

**Comment by jtopjian** [comment]
@zionwu Thanks! I was double checking and found this:

https://github.com/openstack/nova/blob/stable/ocata/nova/api/openstack/compute/pause_server.py

which defines `os-pause-server`, which is an extension.

This can also be seen by doing:

```shell
$ nova list-extensions
```

So I think this functionality is better suited in the `extensions` package. The good news is that you can use the `startstop` package as a template:

https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/extensions/startstop

Let me know if you have any questions.

**Comment by zionwu** [comment]
@jtopjian Thank you for your help and suggestion. I have made the change accordingly.

**Comment by jtopjian** [comment]
This looks good to me. Thank you for contributing this!

**Comment by jrperritt** [comment]
Er, why is there an entire package just for pause/unpause?

**Comment by jtopjian** [comment]
The same reason there's a package for stop/stop :)

It's a dedicated extension.

**Comment by jrperritt** [comment]
Hmm, yeah, looks like the precedent's been set

**Comment by jtopjian** [comment]
> Hmm, yeah, looks like the precedent's been set

Yeah. That was the deciding factor. I actually don't mind it, even though certain extensions are quite small. Being able to decisively put whatever the output of `nova list-extensions` is under `extensions` has some benefit.

**Pull request merged**
