### PR TITLE
do not merge: to test with ci system

### PR DESCRIPTION
**Pull request by animationzl**
This PR is to check if the ci system works correctly.

For #592

### CODE REVIEW

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by mrhillsman** [comment]
Build succeeded.

- gophercloud-unittest http://80.158.20.68/logs/95/595/a95b703398930e78e615a79c758098d3f355fc87/check/gophercloud-unittest/307ba16/ : SUCCESS in 2m 06s
- gophercloud-acceptance-test http://80.158.20.68/logs/95/595/a95b703398930e78e615a79c758098d3f355fc87/check/gophercloud-acceptance-test/6ac1ffa/ : SUCCESS in 29m 04s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build succeeded.

- gophercloud-unittest http://80.158.20.68/logs/95/595/a95b703398930e78e615a79c758098d3f355fc87/check/gophercloud-unittest/c75da2e/ : SUCCESS in 2m 03s
- gophercloud-acceptance-test http://80.158.20.68/logs/95/595/a95b703398930e78e615a79c758098d3f355fc87/check/gophercloud-acceptance-test/fefa71f/ : SUCCESS in 29m 38s

**Comment by kiwik** [comment]
recheck stable/pike

**Comment by mrhillsman** [comment]
Build succeeded.

- gophercloud-acceptance-test-pike http://80.158.20.68/logs/95/595/a95b703398930e78e615a79c758098d3f355fc87/recheck-pike/gophercloud-acceptance-test-pike/743df49/ : SUCCESS in 29m 14s

**Comment by animationzl** [comment]
recheck

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
recheck stable/pike

**Comment by kiwik** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck stable/pike

**Comment by animationzl** [comment]
recheck stable/mitaka

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck stable/pike

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck stable/pike

**Comment by animationzl** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by jrperritt** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by kiwik** [comment]
check

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
recheck stable/pike

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by mrhillsman** [comment]
recheck stable/mitaka

**Comment by mrhillsman** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by mrhillsman** [comment]
@animationzl Can this be closed and re-opened as needed. Github statistics suffer and work being done here is not properly calculated with perpetual PRs.

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck stable/mitaka

**Comment by liu-sheng** [comment]
recheck

**Comment by mrhillsman** [comment]
@liu-sheng is this still valid PR; if not let's go ahead and close it.

**Comment by jrperritt** [comment]
Since there was no response, I'm going to assume this is OK to close

**Pull request closed without merging**
