### PR TITLE
Require Go v1.20

### PR DESCRIPTION
**Pull request by pierreprinetti**
In order to upgrade golang.org/x/crypto, and to get support to the latest language features, upgrade to a newer version of the language and its toolchain.

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
We also have a bunch of acceptance tests where we install go 1.15, could you change that as well?

For example https://github.com/gophercloud/gophercloud/blob/157270b09bb3e14c233f313c8c6db7a9ebdb4c4a/.github/workflows/functional-basic.yaml#L45-L48

**Comment by EmilienM** [comment]
> We also have a bunch of acceptance tests where we install go 1.15, could you change that as well?
> 
> For example
> 
> https://github.com/gophercloud/gophercloud/blob/157270b09bb3e14c233f313c8c6db7a9ebdb4c4a/.github/workflows/functional-basic.yaml#L45-L48

done

**Review by EmilienM — APPROVED** [review]

**Comment by EmilienM** [comment]
I'll merge it once CI is green.

**Review by mandre — APPROVED** [review]
The clustering and messaging jobs are currently broken (https://github.com/gophercloud/gophercloud/issues/2701) and fail for unrelated reason. All the other jobs succeeded.

**Pull request merged**
