### PR TITLE
Add Field *Filters* into Struct roles.ListOpts

### PR DESCRIPTION
**Pull request by zhangzujian**
For #978

### CODE REVIEW

**Comment by zhangzujian** [comment]
recheck

**Comment by zhangzujian** [comment]
Ready for review.

**Comment by zhangzujian** [comment]
Ready for review.

**Comment by zhangzujian** [comment]
@jtopjian Ping for review.

**Comment by jtopjian** [comment]
@zhangzujian It's no problem. I highly recommend having a devstack (or similar) environment to validate tests on before submitting. We're trying to get an robust CI working but, as you've seen, we have occasional issues :)

https://github.com/gophercloud/gophercloud/tree/master/acceptance has some documentation on acceptance test environments.

If you need access to compute resources to do this work, send me an email.

**Comment by zhangzujian** [comment]
@jtopjian 

I wrote a function to test the logic of the acceptance test against my Keystone service (Pike). However, the test passed. I cannot determine where the problem is before I see the output of the acceptance test. So I'm going to wait until the OpenLab check goes back to normal.

**Comment by jtopjian** [comment]
@zhangzujian The following diff should get things working :)

```diff
diff --git a/acceptance/openstack/identity/v3/roles_test.go b/acceptance/openstack/identity/v3/roles_test.go
index 28e7b31..8aeb887 100644                                                                               
--- a/acceptance/openstack/identity/v3/roles_test.go                                                        
+++ b/acceptance/openstack/identity/v3/roles_test.go                                                        
@@ -56,8 +56,7 @@ func TestRolesCRUD(t *testing.T) {                                                        
        th.AssertNoErr(t, err)                                                                              
                                                                                                            
        createOpts := roles.CreateOpts{                                                                     
-               Name:     "testrole",                                                                       
-               DomainID: "default",                                                                        
+               Name: "testrole",                                                                           
                Extra: map[string]interface{}{                                                              
                        "description": "test role description",                                             
                },                                                                                          
@@ -89,7 +88,7 @@ func TestRolesCRUD(t *testing.T) {                                                        
                                                                                                            
        th.AssertEquals(t, found, true)                                                                     
                                                                                                            
-       listOpts := roles.ListOpts{DomainID: role.DomainID}                                                 
+       listOpts := roles.ListOpts{}                                                                        
        listOpts.Filters = map[string]string{                                                               
                "name__contains": "TEST",                                                                   
        }                                                                                                   
```

The root problem is that the created role is being created with a `DomainID` set. There are two ways of resolving this:

1. Change line 74 to have a `listOpts` with `DomainID`
2. Don't create the role with a `DomainID`.

I think 2 is better because the default openstack roles are created without a `DomainID`. This means when you're further testing the role, other roles are included in the results. This is usually better as it can uncover additional bugs.

**Comment by zhangzujian** [comment]
@jtopjian Thanks very much.

I checked the code again and figured out what I had lost sight of.

Function **roles.List()** are called threee three times and all of them should be passed a **roles.ListOpts** with **DomainID=role.DomainID** to. However, I did this only with the last two.

So I think another method to deal with the problem is:

```diff
diff --git a/acceptance/openstack/identity/v3/roles_test.go b/acceptance/openstack/identity/v3/roles_test.go
index 28e7b310..402992d4 100644
--- a/acceptance/openstack/identity/v3/roles_test.go
+++ b/acceptance/openstack/identity/v3/roles_test.go
@@ -71,7 +71,8 @@ func TestRolesCRUD(t *testing.T) {
        tools.PrintResource(t, role)
        tools.PrintResource(t, role.Extra)

-       allPages, err := roles.List(client, nil).AllPages()
+       listOpts := roles.ListOpts{DomainID: role.DomainID}
+       allPages, err := roles.List(client, listOpts).AllPages()
        th.AssertNoErr(t, err)

        allRoles, err := roles.ExtractRoles(allPages)
@@ -89,7 +90,6 @@ func TestRolesCRUD(t *testing.T) {

        th.AssertEquals(t, found, true)

-       listOpts := roles.ListOpts{DomainID: role.DomainID}
        listOpts.Filters = map[string]string{
                "name__contains": "TEST",
        }
```

**Comment by zhangzujian** [comment]
recheck

**Comment by zhangzujian** [comment]
recheck

**Comment by zhangzujian** [comment]
recheck

**Comment by zhangzujian** [comment]
recheck

**Comment by zhangzujian** [comment]
recheck

**Comment by zhangzujian** [comment]
@jtopjian ping for review

**Comment by jtopjian** [comment]
LGTM :)

**Pull request merged**
