### PR TITLE
Workflowv2 crontriggers delete

### PR DESCRIPTION
**Pull request by garbage-collector**
For #1199 

https://github.com/openstack/mistral/blob/master/mistral/api/controllers/v2/cron_trigger.py#L85

### CODE REVIEW

**Comment by garbage-collector** [comment]
Ready to review!

**Comment by garbage-collector** [comment]
Need rebase, waiting workflowv2-workflows-* branches to be accepted before rebasing it.

**Comment by garbage-collector** [comment]
Rebased and ready to review

**Comment by jtopjian** [comment]
The OpenLab failure can be ignored. It's a separate issue.

**Pull request merged**
