### PR TITLE
baremetal: support for virtual media attach/detach

### PR DESCRIPTION
**Pull request by dtantsur**
Requires:
- https://github.com/gophercloud/gophercloud/pull/2961

Closes: #2958

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
This looks good. Were you able to test this against a real environment?

It would probably be good to add acceptance tests as well with SkipReleasesBelow("master"). Please also add a comment about what version master will represent so that we can use a proper version name in the skip later on.

**Comment by dtantsur** [comment]
> This looks good. Were you able to test this against a real environment?

I was, yes.

Regarding acceptance tests... I need to see what the fake backend does on this API. Probably returns an error.

**Review by mandre — APPROVED** [review]
Thanks for adding the acceptance tests :rocket:

**Pull request merged**
