### PR TITLE
Service Client: add HEAD method

### PR DESCRIPTION
**Pull request by zhangzujian**
For #875

### CODE REVIEW

**Comment by jtopjian** [comment]
@jrperritt Thoughts on this?

There are currently a handful of places in Gophercloud that are issuing a `HEAD` by doing `client.Request("HEAD")`, so this would be a more convenient form.

**Comment by zhangzujian** [comment]
Ready for review.

**Comment by zhangzujian** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Comment by jrperritt** [comment]
I think this is OK, but we'd want to go through and change all the `HEAD` calls to use this new function and make sure all the tests still pass.

**Comment by jtopjian** [comment]
@zhangzujian per @jrperritt's comment, would you be able to replace all existing occurrences of `client.Request("HEAD", ...` with `client.Head(...`

This way we can see if anything would break in CI?

**Comment by zhangzujian** [comment]
@jtopjian Please review.

**Comment by jtopjian** [comment]
Looks good to me - thank you!

**Pull request merged**
