### PR TITLE
Acc Tests: Use Ubuntu Xenial for older releases

### PR DESCRIPTION
**Pull request by jtopjian**
For #818

### CODE REVIEW

**Comment by jtopjian** [comment]
recheck stable/ocata

**Comment by wangxiyuan** [comment]
It looks that the failure relates to the test itself.

**Comment by jtopjian** [comment]
@wangxiyuan Yes, looks like the core issue was having everything run on BIonic. I can begin looking into the individual test failures.

**Comment by jtopjian** [comment]
@elfosardo The way I've viewed this is that just because it's going to be in an unmaintained state doesn't mean that everyone currently running Ocata in production will immediately upgrade.

Personally, I wanted to keep testing as far back as Mitaka since Ubuntu officially supports it until April 2021, but there were some issues running it in OpenLab and so we decided to remove it.

The OpenStack APIs have been designed with backwards compatibility in mind (well, most of the time). I see no harm in continuing to support and test older releases as long as we're able to do so. 🙂

**Comment by jtopjian** [comment]
I'm going to merge this for now. This will help us move forward with #1973.

I've created #1976 to track fixing test failures with older releases.

**Comment by elfosardo** [comment]
@jtopjian if we're talking about LTS support, and strictly talking about packaged Openstack, then Ocata should not be supported, but Mitaka should be instead.
Ubuntu is not supporting Ocata anymore.

**Comment by jtopjian** [comment]
Right, I know. I was only highlighting that an older release such as Mitaka is still supported, but we're unable to use it in OpenLab.

To me, the status of support doesn't matter. There are numerous deployments of unsupported releases of OpenStack in production. I don't want to test as far back as, say Liberty or Icehouse or Diablo or all those nostalgic ones -- there's certainly a limit. 🙂

**Pull request merged**
