### PR TITLE
WIP: Add master_lb_enbabled to results

### PR DESCRIPTION
**Pull request by iokiwi**
Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For https://github.com/gophercloud/gophercloud/issues/2117
Closes https://github.com/gophercloud/gophercloud/issues/2117

### CODE REVIEW

**Comment by jtopjian** [comment]
@iokiwi Please let me know when this is ready for review/merge.

**Comment by brtknr** [comment]
Any updates on this?

**Comment by jtopjian** [comment]
@brtknr Please see the corresponding discussion at #2117

**Comment by EmilienM** [comment]
This PR has been staled for a very long time, I'll close it. Feel free to re-open!

**Pull request closed without merging**
