### PR TITLE
Compute v2: Update aggregate

### PR DESCRIPTION
**Pull request by dstdfx**
For #738 

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

API doc: 
- https://developer.openstack.org/api-ref/compute/#update-aggregate

Source code: 
- https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/aggregates.py#L101

### CODE REVIEW

**Comment by dstdfx** [comment]
@jtopjian This PR ready for review. I'm gonna add an acceptance test to #745 as well.

**Comment by jtopjian** [comment]
@dstdfx Let's merge #745 first so we can include acceptance tests with the PRs.

**Comment by dstdfx** [comment]
@jtopjian Done

**Comment by jtopjian** [comment]
@dstdfx Looks good to me! Thank you and nice work :)

**Pull request merged**
