### PR TITLE
[v1] identity: use AuthOptionsBuilder for v2 auth

### LINKED ISSUE #2651: use Identity v2 AuthOptionsBuilder
So for Identity v3, gophercloud takes in an `AuthOptionsBuilder` from the `token3` which ensures that the data to authenticate with will conform to the Identity v3 APIs. This allows people to implement their own custom auth mechanisms like exist in the Python ecosystem which is great. This same support/ecosystem exists for Identity v2. In fact gophercloud originated from https://github.com/rackspace/gophercloud which has their own Identity v2 auth mechanism using an "API key". When gophercloud moved from under the Rackspace umbrella it rightfully removed all the "Rackspace-isms", however there's no mechanism by which to add this back.

I'm proposing using `tokens2.AuthOptionsBuilder` similar to how the Identity v3 auth works in gophercloud. This would improve #1330. However I'm aware of #2577 wanting to remove Identity v2 support, however Rackspace is still using Identity v2. I'd like to get Rackspace contributing more to gophercloud and using it more in the future.

As a first attempt of getting Rackspace to use upstream gophercloud I implemented https://github.com/os-pc/cloud-provider-rackspace/commit/56cf8a12d36c0a039edade9ba42457d9adf33faf#diff-b5b02d252ffde072fea7841ee6419db056b027d7f365193f0d33fad8294ffedc but I've now seen how the interfaces can be used and implemented and will improve it.

### PR DESCRIPTION
**Pull request by cardoe**
Rather than creating a tokens2.AuthOptions inside the authentication flow for identity v2, allow any structure that implements the tokens2.AuthBuilderOptions interface to be used. The gophercloud.AuthOptions already implements this interface so there is no change to the API. To avoid any API change, add AuthenticateV2Ext() as a version of AuthenticateV2() accepting the interface. This will allow an out of tree identity v2 auth mechanism to be implemented, just like the v3. fixes #2651. ref #1330.

### CODE REVIEW

**Comment by cardoe** [comment]
I believe this is a compatible implementation of #2655 that is not a major version breaking change. The `CanReauth()` call is probably the better approach but that's a major break which I've left in #2655.

**Comment by cardoe** [comment]
I've implemented https://github.com/rackerlabs/goraxauth using this and verified that it works.

**Comment by EmilienM** [comment]
cc @pierreprinetti for double check on this one.

**Review by EmilienM — APPROVED** [review]

**Comment by pierreprinetti** [comment]
I'd rather not merge new features into the `v1` branch, now that `v2` is almost out.

**Pull request closed without merging**
