### PR TITLE
Configuration group time parsing error 

### PR DESCRIPTION
**Pull request by eugenetaranov**
For #647

Fixes time parsing error.

### CODE REVIEW

**Comment by jtopjian** [comment]
In order to correctly convert the time that the API server is sending back into a `time.Time` type, you'll need to implement a custom unmarshal method. 

It looks like this is already being done in the `instances` package, so you probably just have to make the appropriate changes to `configurations`:

https://github.com/gophercloud/gophercloud/blob/master/openstack/db/v1/instances/results.go#L71-L88

**Comment by eugenetaranov** [comment]
@jtopjian thank you for advice, makes sense indeed.
Applied, please review

**Comment by jrperritt** [comment]
@eugenetaranov Some feedback on this:
- "fix" is not a helpful title; please change it to be more descriptive. Matching the issue title would be fine.
- There needs to be an accompanying link to the OpenStack source code proving your change is correct

**Comment by jtopjian** [comment]
https://github.com/gophercloud/gophercloud/pull/196 had the fix for the `databases` resource. The updated relevant link is:

https://github.com/openstack/trove/blob/stable/pike/trove/common/base_wsgi.py#L453

Since it's in the base wsgi file, I think it's safe to assume it'll apply to all time fields in the DB service.

It wouldn't be fair of me to make @eugenetaranov hunt for the code when I knew where it was, but @jrperritt is correct: please remember to provide the relevant service-side code when submitting PRs.

**Comment by eugenetaranov** [comment]
thanks @jtopjian, you have saved my day :)

**Comment by jtopjian** [comment]
This looks good to me and I've confirmed it works. I will follow-up with an acceptance test for this.

**Pull request merged**
