### PR TITLE
Senlin: Test Parallel

### PR DESCRIPTION
**Pull request by JackKuei**
Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #[1412 [Add Parallel To Acceptance Test]](https://github.com/gophercloud/gophercloud/issues/1412)

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

N/A

### CODE REVIEW

**Review by ozerovandrei — DISMISSED** [review]
LGTM

**Comment by jtopjian** [comment]
I've been debating this one for a few days. I'd prefer to see how OpenLab handles this before it's merged. It's possible that so much parallel activity crushes the node running the tests.

**Comment by JackKuei** [comment]
I'm not familiar with how OpenLab execute the tests. But running "go test" will not invoke running tests in parallel, only when using the parallel flag will it take effect such as "go test -parallel XX"

**Comment by jtopjian** [comment]
It appears `t.Parallel()` and `-parallel XX` are two different ways to enable parallel execution and are independent of each other.

Once a test has `t.Parallel()`, all parallel tests will run in parallel without any additional test flags - I just confirmed this.

**Comment by JackKuei** [comment]
I think this is a more complete explanation for parallel tests marked with t.Parallel(). ```Parallel tests are run in a number of goroutines. This number is defaulted to GOMAXPROCS, but can be set by passing the -parallel flag to go test.```

**Comment by jtopjian** [comment]
Right, so the concern is that if/when Senlin is tested in OpenLab (which is on my list to do), would this PR cause the tests to crush the environment?

**Comment by JackKuei** [comment]
Yeah, that's something you need to test on your side when you get a chance. Also a side note, those test cases might not execute in order when ran in parallel.

**Comment by EmilienM** [comment]
This PR has been staled for a very long time, I'll close it. Feel free to re-open!

**Pull request closed without merging**
