### PR TITLE
keystone: add v3 limits GetEnforcementModel operation

### PR DESCRIPTION
**Pull request by emilmaruszczak**
For #2289

[docs](https://docs.openstack.org/api-ref/identity/v3/#get-enforcement-model)
[code](https://github.com/openstack/keystone/blob/stable/yoga/keystone/api/limits.py#L131)

### CODE REVIEW

**Comment by nikParasyr** [comment]
@emilmaruszczak this partially implements #2289. dont close it as there are more apis that need to be implemented. thanks

**Comment by mandre** [comment]
Hi @emilmaruszczak, thanks for the PR. Could you also add acceptance tests, so that we verify the code works against real OpenStack environments?

**Comment by emilmaruszczak** [comment]
> Hi @emilmaruszczak, thanks for the PR. Could you also add acceptance tests, so that we verify the code works against real OpenStack environments?
Hello, sure, will do.

**Review by mandre — APPROVED** [review]
Thanks for adding the tests. This LGTM. Are you still planning on updating the PR or is it ready to merge?

**Comment by emilmaruszczak** [comment]
It's ready to be merged.

**Comment by mandre** [comment]
> It's ready to be merged.

Great, let's go then! :shipit:

**Pull request merged**
