### PR TITLE
[CI-v2] Add functional-basic job

### PR DESCRIPTION
**Pull request by EmilienM**
This runs a Github Action to:

* Deploy Devstack with defaults (minimum services)
* Run acceptance/openstack which is a minimal set of tests
* Post logs if we encounter a failure

### CODE REVIEW

**Comment by EmilienM** [comment]
@mandre @pierreprinetti ready for review, please

**Comment by mandre** [comment]
Should we perhaps upload the artifacts for the unit tests in any cases? Otherwise it's hard to know which tests were run as part of the jobs.

**Comment by EmilienM** [comment]
> Should we perhaps upload the artifacts for the unit tests in any cases? Otherwise it's hard to know which tests were run as part of the jobs.

Yeah I need to investigate that but for now we can rely on the logs that are in the Github actions, we can see which tests fail and not

**Comment by mandre** [comment]
> > Should we perhaps upload the artifacts for the unit tests in any cases? Otherwise it's hard to know which tests were run as part of the jobs.
> 
> Yeah I need to investigate that but for now we can rely on the logs that are in the Github actions, we can see which tests fail and not

Sure, we can iterate on that. No objection from me for merging your PR as is.

**Pull request merged**
