### PR TITLE
Glance: hide images from public list

### PR DESCRIPTION
**Pull request by fitbeard**
For #2093

Link to OpenStack code, Commit with explanation: https://github.com/openstack/glance/commit/a308c444065307e99f18b521ed8d95714be24da7

### CODE REVIEW

**Comment by jtopjian** [comment]
@fitbeard Thank you for working on this. 

This PR adds support to create images that are hidden as well as adds the `Hidden` to the result struct. Did you also want to add `Hidden` to the `ListOpts` struct in this PR in order to list hidden images?

**Comment by fitbeard** [comment]
@jtopjian Both. Starting Rocky release every image after upload has _os_hidden_ option with default value _false_ . Listing is useful when you want to change image status. Frankly speaking I'm trying add this functionality to use later in OpenStack terraform provider.

**Comment by jtopjian** [comment]
@fitbeard Right, what I meant was that the PR you have submitted adds `Hidden` to `CreateOpts` but currently does not add the field to `ListOps`. Do you want to amend this PR to do that prior to review/merge?

**Comment by fitbeard** [comment]
@jtopjian you're right. Thank you. I forgot `ListOpts`:) Updated my pull request with a missing `ListOpts` piece.

**Review by jtopjian — APPROVED** [review]
LGTM - thank you!

**Pull request merged**
