### PR TITLE
Enable versioning with X-History-Location

### PR DESCRIPTION
**Pull request by cryptobioz**
For #1317

### CODE REVIEW

**Comment by jtopjian** [comment]
@cryptobioz Thank you for working on this. Per our [contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial) (Step 3), would you be able to provide the Swift API code which shows that these are valid headers? Please let me know if you need any help.

**Comment by cryptobioz** [comment]
Yes, I think the header is used here: https://github.com/openstack/swift/blob/master/swift/common/middleware/versioned_writes.py

**Comment by kiwik** [comment]
recheck

**Comment by cryptobioz** [comment]
@jtopjian I'm sorry, I can't figure out why the acceptance tests are failing, is it a problem on your side or something wrong with my code?

**Comment by jtopjian** [comment]
recheck

**Comment by cryptobioz** [comment]
Thanks @jtopjian !

**Pull request merged**
