### PR TITLE
Baremetal: support deploy_steps for the provisioning API

### PR DESCRIPTION
**Pull request by dtantsur**
For: #2119

### CODE REVIEW

**Review by elfosardo — APPROVED** [review]

**Comment by jtopjian** [comment]
@dtantsur I took a stab at doing the [code hunting](https://github.com/gophercloud/gophercloud/blob/master/docs/contributor-tutorial/step-03-code-hunting.md) requirement and came up with:

* https://github.com/openstack/ironic/blob/766d8f11b4101570829788ed11b2ab3fef85e3f8/ironic/conductor/steps.py#L234
* https://github.com/openstack/ironic/blob/766d8f11b4101570829788ed11b2ab3fef85e3f8/ironic/conductor/steps.py#L264
* https://github.com/openstack/ironic/blob/766d8f11b4101570829788ed11b2ab3fef85e3f8/ironic/conductor/steps.py#L600
* https://github.com/openstack/ironic/blob/766d8f11b4101570829788ed11b2ab3fef85e3f8/ironic/conductor/steps.py#L538-L554

If this is correct, please let me know if this is ready for review.

**Comment by dtantsur** [comment]
HI @jtopjian! Yeah, you're on the right track. This feature was added in https://opendev.org/openstack/ironic/commit/3138acc836c933aa179b9a92c14a226a8b903fe5, its API part starts in https://opendev.org/openstack/ironic/src/commit/6ae5bc4642c4619946a48512501b4ae37246f7ff/ironic/api/controllers/v1/node.py#L850 and progresses further ending up in the code you've found. Note that there is a related concept of deploy templates which makes code hunting somewhere more complicated. This change does not implement deploy templates, only the smaller API addition from the above mentioned commit.

**Comment by dtantsur** [comment]
Tested with the following code:
```go
    client.Microversion = "1.69"

    updates := nodes.UpdateOpts {
        nodes.UpdateOperation {
            Op: nodes.AddOp,
            Path: "/instance_info/image_source",
            Value: "file:///httpboot/centos8.qcow2",
        },
    }

    _, err = nodes.Update(client, "testvm1", updates).Extract()
    if err != nil {
        panic(fmt.Sprintf("Cannot update: %s", err))
    }

    files := []struct {
        Path string `json:"path"`
        Content string `json:"content"`
    } {
        {
            Path: "/etc/motd",
            Content: "SGVsbG8gSXJvbmljIFdvcmxkIQo=",
        },
    }

    opts := nodes.ProvisionStateOpts {
        Target: nodes.TargetActive,
        DeploySteps: []nodes.DeployStep {
            nodes.DeployStep {
                Step: "inject_files",
                Interface: "deploy",
                Priority: 50,
                Args: map[string]interface{}{
                    "files": files,
                },
            },
        },
    }

    err = nodes.ChangeProvisionState(client, "testvm1", opts).ExtractErr()
    if err != nil {
        panic(fmt.Sprintf("Cannot provision: %s", err))
    }
```

(Note that I'm using a deploy step that [has not merged yet](https://review.opendev.org/c/openstack/ironic-python-agent/+/775428))

**Comment by jtopjian** [comment]
@dtantsur Thanks! Those links helped. Notably:

https://opendev.org/openstack/ironic/src/commit/3138acc836c933aa179b9a92c14a226a8b903fe5/ironic/api/controllers/v1/utils.py#L125-L141

which defines the data model being added in this PR. I just needed to see something that showed the fields of the `DeployStep` struct are defined somewhere and `DeployStep` shouldn't be a generic `map[string]interface`.

It looks like the `Interface` field is an [enum](https://opendev.org/openstack/ironic/src/commit/3138acc836c933aa179b9a92c14a226a8b903fe5/ironic/api/controllers/v1/utils.py#L129-L132), with values defined [here](https://github.com/openstack/ironic/blob/766d8f11b4101570829788ed11b2ab3fef85e3f8/ironic/conductor/steps.py#L39-L51) (sorry for linking to GitHub, I wasn't getting any results when using the "search" function in opendev). 

If you wanted, you could create a custom string type called `DeployStepInterfaceType` (or something similar). It would then look like:

```go

type DeployStepInterfaceType string

const (
  InterfaceDeploy DeployStepInterfaceType = "deploy"
  ...
)

    ....

    opts := nodes.ProvisionStateOpts {
        Target: nodes.TargetActive,
        DeploySteps: []nodes.DeployStep {
            nodes.DeployStep {
                Step: "inject_files",
                Interface: nodes.InterfaceDeploy,
                Priority: 50,
                Args: map[string]interface{}{
                    "files": files,
                },
            },
        },
    }
```

This is up to you, though. There are areas in Gophercloud that implement this and other areas that use a generic "string". If you prefer to use a `string`, let me know and I'll go ahead and merge this PR as-is.

**Comment by dtantsur** [comment]
> It looks like the Interface field is an enum, with values defined here

Good call, I completely forgot that we limit the interfaces supported for deploy steps (I also forgot *why* we do that, but that's a different conversation). Will change.

**Comment by dtantsur** [comment]
@jtopjian updated and applied the same change to clean steps.

**Review by EmilienM — APPROVED** [review]
:+1 LGTM

**Review by jtopjian — APPROVED** [review]
LGTM - thank you!

**Pull request merged**
