### PR TITLE
Compute v2: Add host to aggregate

### PR DESCRIPTION
**Pull request by dstdfx**
For #738 

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

API doc: 

- https://developer.openstack.org/api-ref/compute/#add-host

Source code:

- https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/aggregates.py#L141

### CODE REVIEW

**Comment by dstdfx** [comment]
@jtopjian This is ready to review.

**Comment by jtopjian** [comment]
@dstdfx The acceptance test is failing for this (note that OpenLab only runs a small subset of tests at this time. It checks the syntax for all tests, though).

The host being added to the aggregate has to be a real compute node. When the acceptance test runs, you're using `new-cmp` which, unless is the name of the hypervisor, will return an error.

The best way around this would be to use the `hypervisors.List` request to get a list of all hypervisors, check if the result length is greater than 0, then use the first result.

**Comment by dstdfx** [comment]
@jtopjian Done

**Comment by jtopjian** [comment]
@dstdfx Thanks. This looks good. The acceptance test is failing, but that's due to the aggregate still containing hosts. It'll pass once `DeleteHost` is implemented.

**Comment by dstdfx** [comment]
@jtopjian I'll implement it next PR.

**Pull request merged**
