### PR TITLE
Extensions Refactor

### PR DESCRIPTION
**Pull request by jtopjian**
For #300

### CODE REVIEW

**Comment by jtopjian** [comment]
I'm not sure if this PR could be broken up into separate ones. I believe a change in any of these will cause tests to fail in other areas.

**Comment by jrperritt** [comment]
Thanks for digging into this! After skimming it, the first thing I'd like to see are several pass/fail scenarios run via unit tests for `extractIntoPtr` (located in a yet-to-be-created `/testing/results_test.go`). Having the `networking` unit tests that run through the function are a bonus, but really we want to know if the function itself stands up to all the things we want it to.

**Comment by jtopjian** [comment]
> After skimming it, the first thing I'd like to see are several pass/fail scenarios run via unit tests for extractIntoPtr

Ah, yeah, that's a good point. I'll look at this sometime this weekend.

I think the Travis error is with Travis itself. All tests pass locally.

**Comment by jrperritt** [comment]
From Travis:

`acceptance/openstack/networking/v2/extensions/extensions.go:24: undefined: external.CreateOpts`

**Comment by jtopjian** [comment]
You have a better eye than me!

**Comment by jtopjian** [comment]
@jrperritt Let me know if there are any other scenarios you had in mind.

**Comment by jtopjian** [comment]
Yay! Thanks!

**Pull request merged**
