### PR TITLE
Fix use with deployment having a path in the Keystone URL

### PR DESCRIPTION
**Pull request by MatMaul**
For #424

### CODE REVIEW

**Comment by jtopjian** [comment]
@MatMaul Thanks for submitting this.

Per the PR template and [STYLEGUIDE](https://github.com/gophercloud/gophercloud/blob/master/STYLEGUIDE.md), can you also open an Issue to describe the problem? If this change involves communicating with an OpenStack API service, you'll also need to include links to the OpenStack Python source code to validate the change.

**Comment by MatMaul** [comment]
I'll open a bug. I can't pinpoint code server side, it is a bug in the client logic that just don't deal correctly with a Keystone URL that include a path (other than the version postfix).

**Comment by jtopjian** [comment]
@MatMaul No problem, that makes sense.

**Comment by jtopjian** [comment]
@MatMaul Just wanted to touch base about this. It looks like Travis is throwing an error. Might be as simple as running `gofmt` against the changes.

**Comment by MatMaul** [comment]
Indeed thanks I didn't see it. gofmt should be happy now, let's see if I broke a test.

**Comment by jtopjian** [comment]
oh boy... talk about uncovering a rabbit hole.

Thank you for identifying this and raising it as an issue :)

I tested this out with a devstack build and I can confirm that Keystone is now listening on `http://<ip>/identity` - an endpoint with no version. Similarly, `OS_AUTH_URL` is now set to that URL, too, which means that will eventually be the standard. I can also confirm that you are correct about Gophercloud stripping away the `/identity/` portion of the URL.

However, I'm unable to get acceptance tests to work with this patch. Even if I set `OS_AUTH_URL` to `http://<ip>/identity/v3`, tests still aren't working. You can try this yourself by doing:

```shell
source /path/to/openrc
export OS_TENANT_NAME=$OS_PROJECT_NAME
export OS_DOMAIN_NAME=default
go test -v -tags "fixtures acceptance" -run "TestKeypairsList" github.com/gophercloud/gophercloud/acceptance/openstack/compute/v2
```

When I run the above, I get:

```
=== RUN   TestKeypairsList
--- FAIL: TestKeypairsList (0.02s)
        keypairs_test.go:19: Unable to create a compute client: No supported version available from endpoint http://10.1.11.33/identity/
FAIL
exit status 1
FAIL    github.com/gophercloud/gophercloud/acceptance/openstack/compute/v2      0.032s
```

If I change `OS_AUTH_URL` to `http://<ip>/identity/v3/`, I get the same error.

The reason this error is happening is because you're not setting `IdentityEndpoint` in your patch. If this was set to match `OS_AUTH_URL`, then [this](https://github.com/gophercloud/gophercloud/blob/2804b72cf099b41d2e25c8afcca786f9f962ddee/openstack/utils/choose_version.go#L54-L59) piece of code would be triggered and all would probably work correctly.

However, I think we have a more long-term issue. I started digging into this and I found that Keystone is now replying with version `v3.8` instead of `v3.0`:

```
$ curl http://10.1.11.33/identity | python -mjson.tool                          
{                                                                               
    "versions": {                                                               
        "values": [                                                             
            {                                                                   
                "id": "v3.8",                                                   
                "links": [                                                      
                    {                                                           
                        "href": "http://10.1.11.33/identity/v3/",               
                        "rel": "self"                                           
                    }                                                           
                ],                                                              
                "media-types": [                                                
                    {                                                           
                        "base": "application/json",                             
                        "type": "application/vnd.openstack.identity-v3+json"    
                    }                                                           
                ],                                                              
                "status": "stable",                                             
                "updated": "2017-02-22T00:00:00Z"                               
            },                                                                  
            {                                                                   
                "id": "v2.0",                                                   
                "links": [                                                      
                    {                                                           
                        "href": "http://10.1.11.33/identity/v2.0/",             
                        "rel": "self"                                           
                    },                                                          
                    {                                                           
                        "href": "https://docs.openstack.org/",                  
                        "rel": "describedby",                                   
                        "type": "text/html"                                     
                    }                                                           
                ],                                                              
                "media-types": [                                                
                    {                                                           
                        "base": "application/json",                             
                        "type": "application/vnd.openstack.identity-v2.0+json"  
                    }                                                           
                ],                                                              
                "status": "deprecated",                                         
                "updated": "2016-08-04T00:00:00Z"                               
            }                                                                   
        ]                                                                       
    }                                                                           
}                                                                               
```

This means that [`utils.ChooseVersion`](https://github.com/gophercloud/gophercloud/blob/2804b72cf099b41d2e25c8afcca786f9f962ddee/openstack/utils/choose_version.go) will become less and less relevant as time goes on, to the point where `OS_AUTH_URL` will always need explicitly set to a version for authentication to work in Gophercloud. Gophercloud can't work with a versionless Keystone endpoint.

I started working on a more long-term fix and came up with [this](https://github.com/jtopjian/gophercloud/commit/d73f672536cf3ceff82d3f91e986941b6a4f20df). It works for all services except, ironically enough, Identity services, since the `ServiceURL` needs fixed. I thought I'd stop for now before I got too deep.

@jrperritt Thoughts on what's going on?

**Comment by MatMaul** [comment]
Let's go down the hole :)
So I am not at ease with the semantic difference between IdentityBase and IdentityEndpoint.
Base is without the version and endpoint the full path ?
I'll do some tests with the acceptance suite.

For the version I don't think we really care actually. If I understand correctly it is v3.8 since now it supports micro-versioning but the base API is still v3 compatible. We just need to change a bit the code in ChooseVersion to handle correctly this use case and we can safely ignore the .8 part, at least while we don't depend on a micro version change/addition. In this use case we probably have to add some headers.
So I think that the approach in your patch is fine.

**Comment by jtopjian** [comment]
> So I am not at ease with the semantic difference between IdentityBase and IdentityEndpoint.
> Base is without the version and endpoint the full path ?

That's correct

> For the version I don't think we really care actually.

Yes and no. If the `OS_AUTH_URL` setting in the `openrc` file bundled with devstack retained the `/v3`, I could see ignoring parsing of the Keystone version. But since `OS_AUTH_URL` is becoming versionless, too, this will become a larger usability issue within the next year as more and more deployments move to this format.

I consider sourcing an `openrc` file to be standard practice when working with any OpenStack-compatible application, so whatever the values are considered de-facto standard need to be considered here.

I believe that patching `NewClient` is acceptable in the short-term. I just sort of amended this issue with the long-term issue :)

**Comment by jrperritt** [comment]
> Thoughts on what's going on?

Yes, see https://github.com/gophercloud/gophercloud/issues/106 and my response there. Unless there is more to this?

**Comment by jtopjian** [comment]
Ah, I remember that Issue.

> Unless there is more to this?

I don't think so. This is similar to #106. The difference is that Keystone is now publishing a versionless endpoint which increases the likelihood that `NewClient` and `ChooseVersion` will fail.

With regard to a solution, is the progress I made [here](https://github.com/jtopjian/gophercloud/commit/d73f672536cf3ceff82d3f91e986941b6a4f20df) going in the right direction?

**Comment by MatMaul** [comment]
@jtopjian can you push a PR with your WIP ? Seems fine to me.

**Comment by jrperritt** [comment]
> is the progress I made here going in the right direction?

Yes, that looks like the right direction, with the caveat that, unless there's a compelling reason to use regexes, since we know what format to expect, I'd prefer to just parse the version string.

**Comment by jtopjian** [comment]
> Yes, that looks like the right direction, with the caveat that, unless there's a compelling reason to use regexes, since we know what format to expect, I'd prefer to just parse the version string.

regexes are being used in two places. The first is in `NewClient` which is to detect a wide range of version endpoints (anything from `v2.0/` to `v2.0` to `v3` to `v3.8/`). I think a regex makes sense here given the range. Thoughts?

The second place they're used is in the `ChooseVersion` function. I can see replacing them with simple `strings.Contains`, looking for generic `v2` and `v3` strings.

**Comment by jtopjian** [comment]
Each time I thought I've had this sorted out, I stumble upon another issue :)

I've updated my branch [here](https://github.com/jtopjian/gophercloud/commits/identity-versionless-endpoint) with a working solution. This branch has two commits:

The first commit fixes the issue you've reported about Gophercloud not working with versionless identity URLs or URLs that contain a path. It enables the client to successfully authenticate to a wider range of identity URLs. The client can then proceed to work with various OpenStack services.

Except for Identity Services. The reason is because of how Gophercloud parses the service catalog. Currently, if a service is publishing a versionless endpoint, Gophercloud attaches the well-known version suffix to the end of the published URL. For example, [here](https://github.com/gophercloud/gophercloud/blob/3172ddf2336933bc38b355df89cb015e0954df67/openstack/client.go#L248).

It's not doing this for Identity because Identity has, until recently, published a versioned URL.

The work done in the first commit should also be done during creation of the Identity ServiceClient (technically _all_ clients) [here](https://github.com/gophercloud/gophercloud/blob/3172ddf2336933bc38b355df89cb015e0954df67/openstack/endpoint_location.go), but that's a much larger issue that ties into another discussion happening about microversion discovery. 

These two commits _should_ be a good solution. The work in the second commit will most likely change down the road.

@MatMaul Would you be able to test this and see if it resolves the problem you ran into which caused you to report this issue?

If @jrperritt is OK with the use of the regex in the first commit, I can either submit a PR to you or just open a new PR here.

**Comment by MatMaul** [comment]
I don't have something to test right now but the code LGTM.
@jrperritt can we move on ?

**Comment by MatMaul** [comment]
@jtopjian you should probably send a new PR and reference this one. Thanks for the work.

**Comment by jtopjian** [comment]
@MatMaul I apologize - this slipped my inbox. I just opened #508.

**Comment by jrperritt** [comment]
superseded by #508

**Pull request closed without merging**
