### PR TITLE
Ensure StorageURL ends in a slash

### PR DESCRIPTION
**Pull request by jtopjian**
For #182 

Not sure if this is the best way of doing this.

### CODE REVIEW

**Comment by jtopjian** [comment]
@jrperritt ping for review. Let me know if there's a better way to handle this (some existing means in Gophercloud) as well as if there's a test I can add.

**Comment by jrperritt** [comment]
> Not sure if this is the best way of doing this.

use [`gophercloud.NormalizeURL`](https://github.com/gophercloud/gophercloud/blob/master/util.go#L41)

**Comment by jtopjian** [comment]
@jrperritt Does this look OK?

```go
	swiftClient := &gophercloud.ServiceClient{
		ProviderClient: pc,
		Endpoint:       gophercloud.NormalizeURL(auth.StorageURL),
	}
```

**Comment by jrperritt** [comment]
yeah, that looks fine

**Comment by jtopjian** [comment]
@jrperritt Thank you for the help. Ping for review.

**Comment by jrperritt** [comment]
+2

**Pull request merged**
