### PR TITLE
Octavia: Failover Loadbalancer

### PR DESCRIPTION
**Pull request by lingxiankong**
For #1219

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:
- Doc: 
  https://developer.openstack.org/api-ref/load-balancer/v2/index.html#failover-a-load-balancer
- Source Code:
  https://github.com/openstack/octavia/blob/96b9450e6032e65923df9216763b98a1bd2d74c5/octavia/api/v2/controllers/load_balancer.py#L633

### CODE REVIEW

**Comment by jtopjian** [comment]
@lingxiankong Most likely. All tests have been giving the `POST_FAILURE` error for a few days now. However, keep in mind that OpenLab isn't testing Octavia, so you can ignore the failure.

@kiwik @liu-sheng @yongfengdu we've been seeing this error in both Gophercloud and Terraform for the past few days. Any ideas?

**Comment by kiwik** [comment]
@jtopjian @lingxiankong all of tests failed when zuul upload logs to log server (logs.openlabtesting.org), seems this domain broken in the morning and Sunday, we did not know why the domain gone, still struggle in the issue, but I saw the latest periodic jobs success, let's recheck this PR now.

**Comment by kiwik** [comment]
recheck

**Comment by lingxiankong** [comment]
@jtopjian Yeah, I know the Octavia related acceptance tests are not covered in CI, but I've already tested in my own deployment.

**Comment by lingxiankong** [comment]
@kiwik  thanks for help

**Comment by lingxiankong** [comment]
recheck

**Comment by lingxiankong** [comment]
@jtopjian Hi, this PR is ready for review, thanks

**Pull request merged**
