### PR TITLE
Identity V3: add field Filters to policies.ListOpts

### PR DESCRIPTION
**Pull request by zhangzujian**
For #978

### CODE REVIEW

**Comment by zhangzujian** [comment]
@jtopjian ping for review

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
@zhangzujian The logs are showing a test failure:

```
2018-05-15 02:53:21.952979 | ubuntu-xenial | === RUN   TestPoliciesCRUD
2018-05-15 02:53:22.234182 | ubuntu-xenial | --- FAIL: TestPoliciesCRUD (0.28s)
2018-05-15 02:53:22.234241 | ubuntu-xenial | 	tools.go:72: {
2018-05-15 02:53:22.234287 | ubuntu-xenial | 		  "id": "4c617a82a5fd40e0bfbcec7e840d0dcb",
2018-05-15 02:53:22.234334 | ubuntu-xenial | 		  "blob": "{'foobar_user': 'role:compute-user'}",
2018-05-15 02:53:22.234368 | ubuntu-xenial | 		  "type": "application/json",
2018-05-15 02:53:22.234391 | ubuntu-xenial | 		  "links": {
2018-05-15 02:53:22.234470 | ubuntu-xenial | 		    "self": "http://192.168.0.14/identity/v3/policies/4c617a82a5fd40e0bfbcec7e840d0dcb"
2018-05-15 02:53:22.234498 | ubuntu-xenial | 		  }
2018-05-15 02:53:22.234523 | ubuntu-xenial | 		}
2018-05-15 02:53:22.234547 | ubuntu-xenial | 	tools.go:72: {
2018-05-15 02:53:22.234587 | ubuntu-xenial | 		  "description": "policy for foobar_user"
2018-05-15 02:53:22.234602 | ubuntu-xenial | 		}
2018-05-15 02:53:22.234625 | ubuntu-xenial | 	tools.go:72: {
2018-05-15 02:53:22.234668 | ubuntu-xenial | 		  "id": "4c617a82a5fd40e0bfbcec7e840d0dcb",
2018-05-15 02:53:22.234713 | ubuntu-xenial | 		  "blob": "{'foobar_user': 'role:compute-user'}",
2018-05-15 02:53:22.234745 | ubuntu-xenial | 		  "type": "application/json",
2018-05-15 02:53:22.234767 | ubuntu-xenial | 		  "links": {
2018-05-15 02:53:22.234834 | ubuntu-xenial | 		    "self": "http://192.168.0.14/identity/v3/policies/4c617a82a5fd40e0bfbcec7e840d0dcb"
2018-05-15 02:53:22.234853 | ubuntu-xenial | 		  }
2018-05-15 02:53:22.234868 | ubuntu-xenial | 		}
2018-05-15 02:53:22.234891 | ubuntu-xenial | 	tools.go:72: {
2018-05-15 02:53:22.234929 | ubuntu-xenial | 		  "description": "policy for foobar_user"
2018-05-15 02:53:22.234945 | ubuntu-xenial | 		}
2018-05-15 02:53:22.234967 | ubuntu-xenial | 	tools.go:72: {
2018-05-15 02:53:22.235007 | ubuntu-xenial | 		  "id": "4c617a82a5fd40e0bfbcec7e840d0dcb",
2018-05-15 02:53:22.235063 | ubuntu-xenial | 		  "blob": "{'foobar_user': 'role:compute-user'}",
2018-05-15 02:53:22.235096 | ubuntu-xenial | 		  "type": "application/json",
2018-05-15 02:53:22.235119 | ubuntu-xenial | 		  "links": {
2018-05-15 02:53:22.235197 | ubuntu-xenial | 		    "self": "http://192.168.0.14/identity/v3/policies/4c617a82a5fd40e0bfbcec7e840d0dcb"
2018-05-15 02:53:22.235214 | ubuntu-xenial | 		  }
2018-05-15 02:53:22.235263 | ubuntu-xenial | 		}
2018-05-15 02:53:22.235291 | ubuntu-xenial | 	tools.go:72: {
2018-05-15 02:53:22.235331 | ubuntu-xenial | 		  "description": "policy for foobar_user"
2018-05-15 02:53:22.235346 | ubuntu-xenial | 		}
2018-05-15 02:53:22.235446 | ubuntu-xenial | 	convenience.go:35: [1;31mFailure in policies_test.go, line 115: expected [0m[1;32mfalse[0m[1;31m but got [0m[1;33mtrue[0m[1;31m[0m
```

Running the tests again to see if it was a one-time error.

**Comment by zhangzujian** [comment]
@jtopjian I will track the error.

Does the acceptance test succeed on error now ?

**Comment by jtopjian** [comment]
Still saying success. I think it's due to the color codes in the acceptance test error:

```
unable to parse /home/zuul/workspace/test_results.xml
```

@yongfengdu @liu-sheng Just a heads up on this - not sure if this is a fixable bug?

**Comment by zhangzujian** [comment]
@jtopjian ping for review

**Pull request merged**
