### PR TITLE
add code formatting check for travis ci

### PR DESCRIPTION
**Pull request by dixudx**
For #335

### CODE REVIEW

**Comment by dixudx** [comment]
@jtopjian This CI failed due to pr #334. It just proves that this PR is quite important to guarantee the code format for every commit.

When #334 is merged, this CI will pass.

**Comment by jtopjian** [comment]
This seems reasonable to me.  

@jrperritt (since this involves modifying Travis): any objections?

**Comment by jrperritt** [comment]
Agree. It's something I've mentioned before, but never got around to doing. I think running `go fmt` as part of the CI is a good idea.

**Comment by jtopjian** [comment]
@jrperritt `go fmt` to actually rewrite the incoming files?

**Comment by jrperritt** [comment]
Well, a `go fmt` check is fine, too.

**Comment by jtopjian** [comment]
Ah, sorry. This tripped me up, too. `goimports` does everything `go fmt` does plus handles import formatting. That's why I assumed you were looking for _more_ than just a format report :)

**Comment by jtopjian** [comment]
@dixudx Thanks for putting this together :)

**Pull request merged**
