### PR TITLE
Compute v2: Get Hypervisor Details

### PR DESCRIPTION
**Pull request by dstdfx**
For #721

The same for Openstack CLI:

- `openstack hypervisor show <hypervisor-id>`
- `nova hypervisor-show hypervisor-show <hypervisor-id>` 

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

API doc:
- [https://developer.openstack.org/api-ref/compute/#show-hypervisor-details](https://developer.openstack.org/api-ref/compute/#show-hypervisor-details)

Source code:
- [https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/hypervisors.py#L302](https://github.com/openstack/nova/blob/master/nova/api/openstack/compute/hypervisors.py#L302)

### CODE REVIEW

**Comment by jtopjian** [comment]
@dstdfx This looks good overall, but I'm running into a strange issue with the acceptance test:

```
=== RUN   TestHypervisorsGet                                                          
--- FAIL: TestHypervisorsGet (2.84s)                                                  
        hypervisors_test.go:49: Unable to get hypervisor: Resource not found          
FAIL                                                                                  
exit status 1                                                                         
FAIL    github.com/gophercloud/gophercloud/acceptance/openstack/compute/v2      2.895s
```

If I make the following change, it works:

```go
// Get makes a request against the API to get details for specific hypervisor.
func Get(client *gophercloud.ServiceClient, hypervisorID int) (r HypervisorResult) {
  v := strconv.Itoa(hypervisorID)
  _, r.Err = client.Get(hypervisorsGetURL(client, v), &r.Body, &gophercloud.RequestOpts{
    OkCodes: []int{200},
  })
  return
}
```

(As well as update `urls.go` to accept a string instead of an int).

Are you seeing the same behavior? I notice the unit tests are passing which is also strange.

**Comment by dstdfx** [comment]
@jtopjian Hmm, it's double strange because the unit and acceptance tests had passed for me above. But it's my bad, `strconv.Itoa` is the best way to convert string->int.

**Comment by dstdfx** [comment]
@jtopjian Should I send a completely new PR from new branch? 
What I've done before to avoid conflict:
`$ git fetch upstream`
`$ git checkout master`  
`$ git rebase upstream/master`
`$ git push origin master`
`$ git checkout os-hypervisor-details`
`$ git rebase master`
`$ git push origin os-hypervisor-details --force`
Current branch os-hypervisor-details is up to date.

**Comment by kiwik** [comment]
Hi @dstdfx, comment "recheck" can trigger merge-check and openlab-ci manually, like this

**Comment by kiwik** [comment]
recheck

**Comment by dstdfx** [comment]
@kiwik Thank you so much mate!

**Comment by jtopjian** [comment]
LGTM - thank you for working on this.

**Pull request merged**
