### PR TITLE
Containerinfra: Allow setting floating_ip_enabled for creating cluster

### PR DESCRIPTION
**Pull request by lingxiankong**
For #1673

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

https://github.com/openstack/magnum/blob/04fd0470ad3b35c4af5212eee82431b1be43d64c/magnum/api/controllers/v1/cluster.py#L183

### CODE REVIEW

**Comment by lingxiankong** [comment]
@jtopjian How can I retrigger the job?

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
@lingxiankong It looks like some git diff text was accidentally merged in. For example: https://github.com/gophercloud/gophercloud/pull/1677/files#diff-58f1d20ea9e591802d022af1b5956176R150

**Comment by lingxiankong** [comment]
@jtopjian thanks for the review, diff text was removed.

**Pull request merged**
