### PR TITLE
Octavia: Support insert_headers for creating listener

### PR DESCRIPTION
**Pull request by lingxiankong**
For #1513

- [API doc](https://developer.openstack.org/api-ref/load-balancer/v2/index.html#create-listener)
- [Source code](https://github.com/openstack/octavia/blob/68b9d06dae65c20b26aa63b78884f94b6642c542/octavia/api/v2/types/listener.py#L123)

### CODE REVIEW

**Comment by lingxiankong** [comment]
Hi @jtopjian, how can i retrigger the CI?

**Comment by jtopjian** [comment]
You can comment with `recheck`, but you can probably safely ignore the ironic failures.

**Comment by jtopjian** [comment]
@lingxiankong Oh, my apologize. Currently Octavia tests are disabled. I'm working on re-enabling them now. Once that's done, you'll have to rebase this PR. I'll let you know when that's ready to go.

**Comment by lingxiankong** [comment]
> @lingxiankong Oh, my apologize. Currently Octavia tests are disabled. I'm working on re-enabling them now. Once that's done, you'll have to rebase this PR. I'll let you know when that's ready to go.

OK, no problem. Thanks!

**Comment by jtopjian** [comment]
@lingxiankong All set. If you rebase this PR with master, Octavia will now run in the acceptance tests.

**Comment by lingxiankong** [comment]
@jtopjian hi bro, this PR is ready for review :-)

**Pull request merged**
