### PR TITLE
tests: Remove service update integration test

### PR DESCRIPTION
**Pull request by stephenfin**
Go runs tests in parallel for different packages in parallel. The service update test was disabling and re-enabling all compute services, and if this ran at the same time as another test that created a server then the server creation (and therefore the test) would fail. There does not appear to be any way to resolve this. We could run all integration tests serially instead, but this would be a backwards steps that will massively increase test run time. We could also rewrite the test to only disable 1 of N nova-compute services, but that would require us to fence off this compute node in all other tests using non-default parameters to server create. Given the lack of better options, we simply remove the test and assume our testing to date on this method has been good enough and unit tests will be enough to carry us forward.

Signed-off-by: Stephen Finucane <stephenfin@redhat.com>

### CODE REVIEW

**Review by EmilienM — APPROVED** [review]
I'm fine with it

**Comment by pierreprinetti** [comment]
I wanted to test the new "hold" label, but Github is excruciatingly slow at running jobs today...

**Comment by stephenfin** [comment]
Got another example of this here https://github.com/gophercloud/gophercloud/pull/3120

**Comment by pierreprinetti** [comment]
@stephenfin Do we need a backport here=

**Comment by mandre** [comment]
According to [our CI history](https://github.com/gophercloud/gophercloud/actions?query=event%3Aschedule+workflow%3Afunctional-compute), it started failing between May 22th and May 25th.

**Comment by stephenfin** [comment]
> According to [our CI history](https://github.com/gophercloud/gophercloud/actions?query=event%3Aschedule+workflow%3Afunctional-compute), it started failing between May 22th and May 25th.

Nothing stands out for me from the two weeks prior to this.

```
❯ git log --since "2024-05-12" --until "2024-05-26" --oneline                                                                                                                                                                                                                                                                                                                                                                               
bded279a00 Merge "docs: Add more information about unified limits"
c7e49dfa16 docs: Follow up for persistent mdevs
d7d2fb1edd Merge "scheduler: AggregateMultitenancyIsolation to support unlimited tenant"
4e3a41f0a4 Merge "Stop using split UEC image (mostly)"
3a53d715cd Merge "[doc] Improve description for nova-manage db purge"
ac8729ac87 [doc] Improve description for nova-manage db purge
4bc5ff1c99 Merge "fix py312 tox definitions"
ee581a5c9d add functional repoducer for bug 2065927
c60b81fa4b Merge "tox: Drop envdir"
7ff24958ee fix py312 tox definitions
61ad4f1f27 Merge "Enable virtio-scsi in nova-next"
eed3e2b47f Stop using split UEC image (mostly)
84b0a481fe Enable OCaaS for several nova jobs
d45379c6b4 docs: Add more information about unified limits
ab3ca1e205 Merge "Make python 3.12 unit and functional voting"
b6a846c6c8 Merge "Fix hacking test with syntax error"
fa44978141 Merge "Fix notification object hashes for python 3.12"
bfd3525863 Fix formatting issues in extra-specs docs
d467edac49 Merge "do not use str(url) to stringify a URL for subsequent use"
50b180023f Make python 3.12 unit and functional voting
3f0879ccc3 Fix hacking test with syntax error
6ee938fd22 Fix notification object hashes for python 3.12
2e6041a76e Merge "Remove SQLAlchemy tips jobs"
acbe3e28e5 do not use str(url) to stringify a URL for subsequent use
5095336689 Merge "Upload glance image with --file in ceph job"
```

**Pull request merged**
