### PR TITLE
Acc Tests: Moving to Ubuntu Focal

### PR DESCRIPTION
**Pull request by jtopjian**
For #2168

### CODE REVIEW

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
@zaneb I'm trying to get the acceptance tests working in OpenLab and have been able to get the non-ironic test suites to pass. I'm not sure about the Ironic side, though. Since you were able to figure out the last test issue, would you happen to know what's going on here? From the logs in the link above, I think this is the error:

```
2021-06-03 18:10:14.875 | venv-tempest create: /opt/stack/new/tempest/.tox/tempest
2021-06-03 18:10:15.106 | ERROR: invocation failed (exit code 1), logfile: /opt/stack/new/tempest/.tox/tempest/log/venv-tempest-0.log
2021-06-03 18:10:15.107 | ================================== log start ===================================
2021-06-03 18:10:15.107 | ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'
2021-06-03 18:10:15.107 | 
2021-06-03 18:10:15.107 | =================================== log end ====================================
2021-06-03 18:10:15.107 | ERROR: InvocationError for command /usr/bin/python3.8 -m virtualenv --no-download --python /usr/bin/python3.8 tempest (exited with code 1)
2021-06-03 18:10:15.108 | ___________________________________ summary ____________________________________
2021-06-03 18:10:15.108 | ERROR:   venv-tempest: InvocationError for command /usr/bin/python3.8 -m virtualenv --no-download --python /usr/bin/python3.8 tempest (exited with code 1)
```

Though I'm not sure if that's just a red herring?

**Comment by zaneb** [comment]
From [what I can gather](https://github.com/pypa/virtualenv/issues/1873) it seems to happen when you have conflicting versions of virtualenv installed (built in + via pip). No idea why that would only happen in the ironic case though.

**Comment by zaneb** [comment]
The difference seems to be that only the ironic job is installing tempest, event though INSTALL_TEMPEST is false for both.

**Comment by jtopjian** [comment]
@zaneb Thanks! I've removed tempest from the ironic devstack configuration... let's see if that helps at all.

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
@zaneb Thanks so much for your help with this - it's really appreciated.

**Comment by zaneb** [comment]
No worries, not sure that I contributed anything useful but feel free to ping me about stuff like this any time :wink:

**Pull request merged**
