### PR TITLE
[wip] Add senlin clustering support. Need to beef up unit test. Need to add acceptance tests.

### PR DESCRIPTION
**Pull request by JackKuei**
Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #[wip Add senlin clustering support]

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[PUT URLS HERE]

### CODE REVIEW

**Comment by jtopjian** [comment]
@JackKuei Thank you for submitting this.

While this work is definitely appreciated, this is a very large PR and cannot be accepted like this. PRs should only include one API action at a time. Please see the recent work done with vpnaas as an example:

https://github.com/gophercloud/gophercloud/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+vpnaas

Also note that all features for Gophercloud must have a corresponding issue (as mentioned in the Github PR template shown above):

> Prior to a PR being reviewed, there needs to be a Github issue that the PR addresses. Replace the brackets and text below with that issue number.

If you'd like to add support for all of Senlin, you can house all PRs for it under a single issue like what is being done here:

https://github.com/gophercloud/gophercloud/issues/723

There's also our [STYLEGUIDE](https://github.com/gophercloud/gophercloud/blob/master/STYLEGUIDE.md) and [CONTRIBUTING](https://github.com/gophercloud/gophercloud/blob/master/.github/CONTRIBUTING.md) guide which will also be helpful.

Your work here _is_ appreciated and we'd love to help get it included into Gophercloud. In order to help code review on our side more manageable, we have a certain process.

Please let me know if you have any questions or need any help!

**Comment by JackKuei** [comment]
Hi Joe,

Thanks for the template. Will work on submitting section by section. The contribution guide for new feature wasn’t too clear about open an issue, since it stated “or”.
It's always useful to open an issue or submit a pull request early on to indicate your intent to a core contributor
But will start to make changes to conform to the guidelines.

Thanks,
Jack

**Comment by jtopjian** [comment]
> The contribution guide for new feature wasn’t too clear about open an issue, since it stated “or”.

I completely agree and I'll get that fixed. Thank you for pointing that out. We regularly review the contributing guide but somehow that was missed... a few times, even!

Do let me know if you've found any other areas that could be worded better or presented better.

**Comment by JackKuei** [comment]
Please be patient with me since still new to the process. I’ve now created the issue.
https://github.com/gophercloud/gophercloud/issues/823
Will work on breaking apart into sections for PR.

**Comment by jtopjian** [comment]
> Please be patient with me since still new to the process.

Absolutely.

From other contributors, we've historically seen the first couple of PRs require a few iterations. Any code review comments and questions are to help ensure the implementation is correct. At the same time, please feel free to ask about the best way to handle something.

Once a few PRs have been merged, you'll get the hang of things and code should be merged fairly quickly. :)

**Comment by JackKuei** [comment]
Closed. Going to break it down to smaller commits

**Comment by JackKuei** [comment]
Hi Joe,

Going to break it down the big commits to smaller pieces. Here is the webhook trigger PR. https://github.com/gophercloud/gophercloud/pull/824

Thanks,
Jack

**Comment by jtopjian** [comment]
@JackKuei Sounds good!

Also, I wrote a document up over the weekend which might help with the PR process: https://github.com/jtopjian/gophercloud/tree/docs-tutorial/docs/contributor-tutorial

**Pull request closed without merging**
