### PR TITLE
Senlin: Clusters CompleteLifecycle

### PR DESCRIPTION
**Pull request by JackKuei**
Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #[823 [Add support for Senlin clustering]](https://github.com/gophercloud/gophercloud/issues/823)

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[[clusters:completelifecycle]](https://github.com/openstack/senlin/blob/master/senlin/api/openstack/v1/clusters.py#L232)

### CODE REVIEW

**Comment by JackKuei** [comment]
@jtopjian This PR is ready for review.

**Comment by dkt26111** [comment]
This API was missing from the official Senlin API docs.  I have created a patch set to add:
https://review.openstack.org/#/c/581907/

You can review the output of the doc build here:
http://logs.openstack.org/07/581907/1/check/build-openstack-api-ref/6c97e95/html/#complete-lifecycle-on-a-cluster-action

**Comment by JackKuei** [comment]
@jtopjian let's keep the convention following the python source code then. Will change it to CompleteLifecycle

**Comment by JackKuei** [comment]
@jtopjian Will do more prod testing for this API. Will open bug if there is problem.

**Pull request merged**
