### PR TITLE
[neutron]: introduce Description argument for the portforwarding

### LINKED ISSUE #3093: Add description argument to portforwarding
API reference: https://github.com/openstack/neutron-lib/blob/47e1736c10ffd6f1850eba9970acdc00373f9de7/neutron_lib/api/definitions/fip_pf_description.py

### PR DESCRIPTION
**Pull request by kayrus**
Prior to starting a PR, please make sure you have read our
[contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial).

Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

Fixes #3093 
Backport of the #3094

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[PUT URLS HERE]

### CODE REVIEW

**Comment by EmilienM** [comment]
can't we submit the backports with the bot? Add the `backport-v1` label to the original PR and the bot will submit a PR. Unless this is not a clean cherry-pick, this is the right way to do.

**Comment by kayrus** [comment]
@EmilienM never used this label. Let me try.

**Comment by kayrus** [comment]
@EmilienM  didn't work

**Review by EmilienM — APPROVED** [review]

**Comment by kayrus** [comment]
I'm merging this PR, since this backport doesn't break the API.

**Pull request merged**
