### PR TITLE
nova: introduce servers.ListDetails along with a simple servers.List

### LINKED ISSUE #2553: nova: List request always uses detailed server listing
There is no way to list servers without details, see https://docs.openstack.org/api-ref/compute/#list-servers vs https://docs.openstack.org/api-ref/compute/#list-servers-detailed
https://github.com/gophercloud/gophercloud/blob/49ee5b4f954aa1b1693feef63d3e841923a2685f/openstack/compute/v2/servers/requests.go#L98-L99

A simple comparison for 1k servers listing:

```
$ time curl -s https://nova:443/v2.1/servers -H "X-Auth-Token: ${OS_AUTH_TOKEN}" | jq -r '.servers|length'
985

real    0m1,907s
user    0m0,097s
sys     0m0,015s
$ time curl -s https://nove:443/v2.1/servers/detail -H "X-Auth-Token: ${OS_AUTH_TOKEN}" | jq -r '.servers|length'
985

real    0m20,425s
user    0m0,117s
sys     0m0,039s
```

simple servers listing takes 10 times faster results.

Proposal:

1) implement a NEW `ListNoDetail` function to list servers using `listURL(client)` call, keeping the backward compatibility for gophercloud
2) rename current `List` func to `ListDetail` and implement a new `List` func using NO-detail URL. This will break backward compatibility. Nevertheless I prefer this solution, since other API calls do have `ListDetail` functions, e.g. nova images, flavors, manila shares and baremetals.

see also: https://github.com/kubernetes/cloud-provider-openstack/issues/2089

### PR DESCRIPTION
**Pull request by kayrus**
Fixes #2553

### CODE REVIEW

**Comment by pierreprinetti** [comment]
Can you think of a way of adding this functionality in a non-breaking fashion?

**Comment by kayrus** [comment]
@pierreprinetti I'd like to, but it won't be aligned with other services... See my thoughts in the original ticket.

**Comment by pierreprinetti** [comment]
I don't think it's reasonable to merge a fix that breaks existing users for efficiency. If it's not possible to achieve what you need in a backwards-compatible manner, I'd say it's a wontfix.

**Comment by kayrus** [comment]
I know it's a breaking change. But it's breaks for good reasons: align with other `ListDetails` functions in a project:
```
$ grep -rl 'func ListDetail(' openstack/
openstack/compute/v2/servers/requests.go
openstack/compute/v2/images/requests.go
openstack/compute/v2/flavors/requests.go
openstack/compute/v2/extensions/availabilityzones/requests.go
openstack/sharedfilesystems/v2/schedulerstats/requests.go
openstack/sharedfilesystems/v2/sharenetworks/requests.go
openstack/sharedfilesystems/v2/shares/requests.go
openstack/sharedfilesystems/v2/snapshots/requests.go
openstack/baremetal/v1/ports/requests.go
openstack/baremetal/v1/nodes/requests.go
openstack/blockstorage/extensions/backups/requests.go
openstack/containerinfra/v1/clusters/requests.go
```
It's not the first time gophercloud introduces breaking changes, see https://github.com/gophercloud/gophercloud/blob/master/CHANGELOG.md

**Comment by pierreprinetti** [comment]
>It's not the first time gophercloud introduces breaking changes

I am not against breaking changes. However they have a cost. Increased efficiency is rarely going to balance that cost.

**Comment by kayrus** [comment]
@pierreprinetti ok. I appreciate if you can suggest a name for a _simple_ list function.

**Comment by pierreprinetti** [comment]
ehr... ListSimple?

I hope you are more creative than I am :grimacing:

**Comment by kayrus** [comment]
@pierreprinetti done

**Review by EmilienM — APPROVED** [review]

**Comment by mandre** [comment]
I renamed the PR to reflect the latest code change.

**Pull request merged**
