### PR TITLE
Manila share errors

### PR DESCRIPTION
**Pull request by kayrus**
Part of #1345

### CODE REVIEW

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
Rebased, errors were detect successfully.

**Comment by kayrus** [comment]
Let's keep it open. We can trigger a test whenever we want.

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
Latest error message:

> create: Driver does not expect share-network to be provided with current configuration.

Removed shared network dependency.

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
Commented out manila share shrinking. Manila tests are fine now, but lbaas CRUD timed out. Could be ignored.
@jtopjian ready for review

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Pull request merged**
