### PR TITLE
Handle nova api version > 2.87 for hypervisor

### LINKED ISSUE #3026: Nova API > 2.87 breaks fetching cpu_info from hypervisor
Please see discussion at https://github.com/openstack-exporter/openstack-exporter/issues/268.

The root of the error is at https://github.com/gophercloud/gophercloud/blob/51f24691da0f2fa5c3a339a7b1053915655713fc/openstack/compute/v2/extensions/hypervisors/results.go#L166-L176 

Here, with Nova API > 2.87, CPUInfo is nil, causing the error.

### PR DESCRIPTION
**Pull request by samuelallan72**
NOTE: this is based on and tested with v1.5.0 (I'm testing for https://github.com/openstack-exporter/openstack-exporter/issues/268 ).  Please let me know if this should be rebased, targeted to v1 branch, etc.?  Help appreciated for testing this. :)

Fixes #3026

### CODE REVIEW

**Comment by EmilienM** [comment]
nice addition, please rebase

**Comment by stephenfin** [comment]
Would it be possible to get a unit test for this? You can base it on the `TestGetHypervisorEmptyCPUInfo` test in `openstack/compute/v2/hypervisors/testing/requests_test.go`, though obviously you will need a different request handler that returns a v2.87-like response (i.e. no `cpu_info` field, among other things). Otherwise, this looks good to me. The functional test failure is unrelated (the test was broken and has been removed https://github.com/gophercloud/gophercloud/pull/3114)

**Comment by samuelallan72** [comment]
@stephenfin sure of course, thanks for the reminder. :)  Added.

**Review by stephenfin — APPROVED** [review]
Assuming CI is happy, LGTM

**Comment by samuelallan72** [comment]
@EmilienM @stephenfin hi, is there anything else you need from me before this can be landed? :)

**Comment by samuelallan72** [comment]
Thanks @stephenfin :smile:

**Comment by stephenfin** [comment]
I think that's more of an question for @pierreprinetti. I'm not sure if we're still doing backports to v1?

**Comment by samuelallan72** [comment]
Thanks, also do you know if this will be released to v2? I'm not sure what your release process looks like - which release should we target to get this patch? Thanks.

**Comment by kayrus** [comment]
In theory this can be backported to v2.
Regarding the changes, this looks similar to #3159

**Pull request merged**
