### PR TITLE
add AllProjects LitsOps on ServerGroups

### PR DESCRIPTION
**Pull request by clementblaise**
Prior to starting a PR, please make sure you have read our
[contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial).

Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #[2069]

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[https://docs.openstack.org/api-ref/compute/?expanded=list-server-groups-detail#server-groups-os-server-groups]

### CODE REVIEW

**Comment by jtopjian** [comment]
@clementblaise This is a good start - thanks!

Travis is reporting an error with the unit tests. You can reproduce this locally by doing:

```shell
$ cd openstack/compute/v2/extensions/servergroups
$ go test -v ./testing
```

The files in the `testing` directory will need updated for the new parameter.

On the topic of the new parameter, instead of the API documentation, we need to see the actual Nova Python code that implements this feature. This is described [here](https://github.com/gophercloud/gophercloud/blob/master/docs/contributor-tutorial/step-03-code-hunting.md). This is a pretty hard step for new contributors, so I've dug up the references for you:

* https://github.com/openstack/nova/blob/8af40c844f664007910b9b3e316944682d6180fe/nova/api/openstack/compute/server_groups.py#L161
* https://github.com/openstack/nova/blob/8a33066b258a748ffbb0ba202c7fd56c16565879/nova/api/openstack/compute/schemas/server_groups.py#L81

No further work is needed for these links - it just "proves" that a parameter called `all_projects` really does exist.

Please let me know if you have any questions or need any help with getting the unit tests to pass.

**Comment by clementblaise** [comment]
@jtopjian Thanks for helping out on finding the references, indeed not trivial, I will know for the next time.

I had forgotten the test I just pushed the modification.

**Comment by clementblaise** [comment]
@jtopjian Acceptance test failed while setting up I am not sure what I am supposed to do, could you have a look ?

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
@clementblaise Is this ready for review/merge?

**Comment by clementblaise** [comment]
@jtopjian Yes you can go ahead

**Review by jtopjian — APPROVED** [review]
LGTM - thank you!

**Pull request merged**
