### PR TITLE
Enable OpenLab periodic check

### PR DESCRIPTION
**Pull request by kiwik**
Periodic check will be triggered at UTC-0 0:00 and 12:00 of everyday
automatically, unit and acceptance tests will be executed, results will
be shown in OpenLab CI dashboard http://status.openlabtesting.org/t/openlab/builds.html

For theopenlab/openlab#63

### CODE REVIEW

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by jtopjian** [comment]
@kiwik This looks good to me. Is this something you're ready to have merged?

**Comment by mrhillsman** [comment]
@kiwik is this ready for merging?

**Comment by kiwik** [comment]
@mrhillsman @jtopjian yes, this patch is ready to merge, sorry, I miss your comments

**Pull request merged**
