### PR TITLE
Acc tests: update Compute V2 Tags test

### PR DESCRIPTION
**Pull request by ozerovandrei**
Add Delete and DeletAll checks into TestServersTags.

For #1669

### CODE REVIEW

**Comment by ozerovandrei** [comment]
```
2019-09-15 15:01:36.601152 | ubuntu-xenial | ERROR: the main setup script run by this job failed - exit code: 2
2019-09-15 15:01:36.622525 | ubuntu-xenial |     please look at the relevant log files to determine the root cause
2019-09-15 15:01:36.623015 | ubuntu-xenial | Running devstack worlddump.py
2019-09-15 15:01:39.156761 | ubuntu-xenial | neutron-dhcp-agent: no process found
2019-09-15 15:01:39.193962 | ubuntu-xenial | neutron-l3-agent: no process found
2019-09-15 15:01:39.261869 | ubuntu-xenial | neutron-metadata-agent: no process found
2019-09-15 15:01:39.302820 | ubuntu-xenial | neutron-openvswitch-agent: no process found
2019-09-15 15:01:39.367147 | ubuntu-xenial | Cleaning up host
2019-09-15 15:01:39.367316 | ubuntu-xenial | ... this takes 3 - 4 minutes (logs at logs/devstack-gate-cleanup-host.txt.gz)
2019-09-15 15:02:51.531363 | ubuntu-xenial |  [WARNING]: Could not match supplied host pattern, ignoring: subnodes
2019-09-15 15:02:51.531558 | ubuntu-xenial |  [WARNING]: No hosts matched, nothing to do
2019-09-15 15:02:57.242145 | ubuntu-xenial | Done.
2019-09-15 15:02:59.055967 | ubuntu-xenial | *** FAILED with status: 2
2019-09-15 15:03:10.039488 | ubuntu-xenial | ERROR
2019-09-15 15:03:10.040239 | ubuntu-xenial | {
2019-09-15 15:03:10.040378 | ubuntu-xenial |   "delta": "1:11:26.195356",
2019-09-15 15:03:10.040481 | ubuntu-xenial |   "end": "2019-09-15 15:02:59.182150",
2019-09-15 15:03:10.040586 | ubuntu-xenial |   "msg": "non-zero return code",
2019-09-15 15:03:10.040683 | ubuntu-xenial |   "rc": 2,
2019-09-15 15:03:10.040760 | ubuntu-xenial |   "start": "2019-09-15 13:51:32.986794"
2019-09-15 15:03:10.040865 | ubuntu-xenial | }
```

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
```
2019-09-17 10:31:32.781253 | ubuntu-xenial | === RUN   TestShareNetworkCreateDestroy
2019-09-17 10:31:33.401886 | ubuntu-xenial | --- FAIL: TestShareNetworkCreateDestroy (0.62s)
2019-09-17 10:31:33.402150 | ubuntu-xenial |     sharenetworks.go:25: Attempting to create share network: ACPTTESTF4fHmIi9Bd6d2oWb
2019-09-17 10:31:33.402810 | ubuntu-xenial |     sharenetworks_test.go:21: Unable to create share network: Bad request with: [POST http://192.168.0.19/share/v2/0b0181c751364265976ab1a8b65b88e6/share-networks], error message: {"badRequest": {"message": "When creating a new share network subnet you need to specify both neutron_net_id and neutron_subnet_id or none of them.", "code": 400}}
2019-09-17 10:31:33.402897 | ubuntu-xenial | === RUN   TestShareNetworkUpdate
2019-09-17 10:31:35.553036 | ubuntu-xenial | --- FAIL: TestShareNetworkUpdate (2.15s)
2019-09-17 10:31:35.553384 | ubuntu-xenial |     sharenetworks.go:25: Attempting to create share network: ACPTTESTPlaLqpbe2692OhBf
2019-09-17 10:31:35.554088 | ubuntu-xenial |     sharenetworks_test.go:52: Unable to create share network: Bad request with: [POST http://192.168.0.19/share/v2/0b0181c751364265976ab1a8b65b88e6/share-networks], error message: {"badRequest": {"message": "When creating a new share network subnet you need to specify both neutron_net_id and neutron_subnet_id or none of them.", "code": 400}}
2019-09-17 10:31:35.554192 | ubuntu-xenial | === RUN   TestShareNetworkListDetail
2019-09-17 10:31:37.897020 | ubuntu-xenial | --- PASS: TestShareNetworkListDetail (2.34s)
2019-09-17 10:31:37.897189 | ubuntu-xenial | === RUN   TestShareNetworkListFiltering
2019-09-17 10:31:38.103125 | ubuntu-xenial | --- FAIL: TestShareNetworkListFiltering (0.21s)
2019-09-17 10:31:38.103404 | ubuntu-xenial |     sharenetworks.go:25: Attempting to create share network: ACPTTESTQkduMJpHmUpwOnhy
2019-09-17 10:31:38.104071 | ubuntu-xenial |     sharenetworks_test.go:121: Unable to create share network: Bad request with: [POST http://192.168.0.19/share/v2/0b0181c751364265976ab1a8b65b88e6/share-networks], error message: {"badRequest": {"message": "When creating a new share network subnet you need to specify both neutron_net_id and neutron_subnet_id or none of them.", "code": 400}}
2019-09-17 10:31:38.104187 | ubuntu-xenial | === RUN   TestShareNetworkListPagination
2019-09-17 10:31:38.298353 | ubuntu-xenial | --- FAIL: TestShareNetworkListPagination (0.19s)
2019-09-17 10:31:38.298602 | ubuntu-xenial |     sharenetworks.go:25: Attempting to create share network: ACPTTESTyrAnLgIsLGZS4CvA
2019-09-17 10:31:38.299299 | ubuntu-xenial |     sharenetworks_test.go:161: Unable to create share network: Bad request with: [POST http://192.168.0.19/share/v2/0b0181c751364265976ab1a8b65b88e6/share-networks], error message: {"badRequest": {"message": "When creating a new share network subnet you need to specify both neutron_net_id and neutron_subnet_id or none of them.", "code": 400}}
2019-09-17 10:31:38.299427 | ubuntu-xenial | === RUN   TestShareNetworkAddRemoveSecurityService
2019-09-17 10:31:38.554306 | ubuntu-xenial | --- FAIL: TestShareNetworkAddRemoveSecurityService (0.26s)
2019-09-17 10:31:38.554470 | ubuntu-xenial |     securityservices.go:20: Attempting to create security service: ACPTTESTiWk260mR2l24DzV0
2019-09-17 10:31:38.554576 | ubuntu-xenial |     sharenetworks.go:25: Attempting to create share network: ACPTTEST69SMMVsyQO9p7MHe
2019-09-17 10:31:38.554948 | ubuntu-xenial |     sharenetworks_test.go:207: Unable to create share network: Bad request with: [POST http://192.168.0.19/share/v2/0b0181c751364265976ab1a8b65b88e6/share-networks], error message: {"badRequest": {"message": "When creating a new share network subnet you need to specify both neutron_net_id and neutron_subnet_id or none of them.", "code": 400}}
2019-09-17 10:31:38.555092 | ubuntu-xenial |     securityservices.go:44: Deleted security service: 0bf62bcc-f5b1-4ce3-9790-94885d63330e
```

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
I'm going to merge this since `TestServersTags` is passing and openlab is only failing at the following tests:
```
2019-09-19 19:50:38.332537 | ubuntu-xenial | === RUN   TestShareNetworkCreateDestroy
2019-09-19 19:50:39.088437 | ubuntu-xenial | --- FAIL: TestShareNetworkCreateDestroy (0.76s)
2019-09-19 19:50:39.088651 | ubuntu-xenial |     sharenetworks.go:25: Attempting to create share network: ACPTTESTQngxwwKw7M7XusoR
2019-09-19 19:50:39.089176 | ubuntu-xenial |     sharenetworks_test.go:21: Unable to create share network: Bad request with: [POST http://192.168.0.10/share/v2/d38eb8d50d5c4111988889b4ddb1636e/share-networks], error message: {"badRequest": {"message": "When creating a new share network subnet you need to specify both neutron_net_id and neutron_subnet_id or none of them.", "code": 400}}
2019-09-19 19:50:39.089281 | ubuntu-xenial | === RUN   TestShareNetworkUpdate
2019-09-19 19:50:41.435756 | ubuntu-xenial | --- FAIL: TestShareNetworkUpdate (2.35s)
2019-09-19 19:50:41.436081 | ubuntu-xenial |     sharenetworks.go:25: Attempting to create share network: ACPTTESTPVXrKXhBU41GVpTI
2019-09-19 19:50:41.436474 | ubuntu-xenial |     sharenetworks_test.go:52: Unable to create share network: Bad request with: [POST http://192.168.0.10/share/v2/d38eb8d50d5c4111988889b4ddb1636e/share-networks], error message: {"badRequest": {"message": "When creating a new share network subnet you need to specify both neutron_net_id and neutron_subnet_id or none of them.", "code": 400}}
2019-09-19 19:50:41.436652 | ubuntu-xenial | === RUN   TestShareNetworkListDetail
2019-09-19 19:50:44.818134 | ubuntu-xenial | --- PASS: TestShareNetworkListDetail (3.38s)
2019-09-19 19:50:44.818250 | ubuntu-xenial | === RUN   TestShareNetworkListFiltering
2019-09-19 19:50:44.991688 | ubuntu-xenial | --- FAIL: TestShareNetworkListFiltering (0.17s)
2019-09-19 19:50:44.991885 | ubuntu-xenial |     sharenetworks.go:25: Attempting to create share network: ACPTTESTSZvuM63Py4Fssj5u
2019-09-19 19:50:44.992204 | ubuntu-xenial |     sharenetworks_test.go:121: Unable to create share network: Bad request with: [POST http://192.168.0.10/share/v2/d38eb8d50d5c4111988889b4ddb1636e/share-networks], error message: {"badRequest": {"message": "When creating a new share network subnet you need to specify both neutron_net_id and neutron_subnet_id or none of them.", "code": 400}}
2019-09-19 19:50:44.992340 | ubuntu-xenial | === RUN   TestShareNetworkListPagination
2019-09-19 19:50:45.282592 | ubuntu-xenial | --- FAIL: TestShareNetworkListPagination (0.29s)
2019-09-19 19:50:45.282723 | ubuntu-xenial |     sharenetworks.go:25: Attempting to create share network: ACPTTESTV3oVcWsLmd7ki0Vf
2019-09-19 19:50:45.282989 | ubuntu-xenial |     sharenetworks_test.go:161: Unable to create share network: Bad request with: [POST http://192.168.0.10/share/v2/d38eb8d50d5c4111988889b4ddb1636e/share-networks], error message: {"badRequest": {"message": "When creating a new share network subnet you need to specify both neutron_net_id and neutron_subnet_id or none of them.", "code": 400}}
2019-09-19 19:50:45.283039 | ubuntu-xenial | === RUN   TestShareNetworkAddRemoveSecurityService
2019-09-19 19:50:45.587682 | ubuntu-xenial | --- FAIL: TestShareNetworkAddRemoveSecurityService (0.30s)
2019-09-19 19:50:45.587866 | ubuntu-xenial |     securityservices.go:20: Attempting to create security service: ACPTTESThgWT5KBLR2FrEm6L
2019-09-19 19:50:45.587991 | ubuntu-xenial |     sharenetworks.go:25: Attempting to create share network: ACPTTESTmplBaxAEVsyfzJQz
2019-09-19 19:50:45.588448 | ubuntu-xenial |     sharenetworks_test.go:207: Unable to create share network: Bad request with: [POST http://192.168.0.10/share/v2/d38eb8d50d5c4111988889b4ddb1636e/share-networks], error message: {"badRequest": {"message": "When creating a new share network subnet you need to specify both neutron_net_id and neutron_subnet_id or none of them.", "code": 400}}
2019-09-19 19:50:45.588587 | ubuntu-xenial |     securityservices.go:44: Deleted security service: 40e1d650-be87-4879-a068-47c084602336
```

**Pull request merged**
