### PR TITLE
Zun: fix Fatalf(): format %v reads arg #1, but call has only 0 args

### PR DESCRIPTION
**Pull request by jtopjian**
For #700

### CODE REVIEW

**Comment by kevin-zhaoshuai** [comment]
@jtopjian Another interesting thing I also meet is the same error with Travis-ci we meet here.
https://travis-ci.org/gophercloud/gophercloud/jobs/365920694
The gofmt check error.

**Comment by jtopjian** [comment]
Ah, yes. That was fixed in https://github.com/gophercloud/gophercloud/pull/892. Unfortunately #892 also fixed some VPNaaS code that had the same problem, so I can't easily cherry-pick the commits of that PR.

Fortunately that's just a Travis failure. We should be able to still leverage OpenLab testing, though.

The OpenLab tests are showing some other failures that I'll try to fix.

**Comment by jtopjian** [comment]
OK, that's going to be difficult, too, since the errors being reported were fixed in https://github.com/gophercloud/gophercloud/pull/820 which has 27 commits :)

I think it's safe to say that Option 2 described in #700 isn't going to be practical.

**Comment by jtopjian** [comment]
Closing this in favor of #944

**Pull request closed without merging**
