### PR TITLE
Add External network flag into "ListOpts"

### PR DESCRIPTION
**Pull request by kayrus**
This commit adds possibility to filter private/public networks.

### CODE REVIEW

**Comment by jtopjian** [comment]
@kayrus Thank you for submitting this! Can you please read over the New Contributor Tutorial?

https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial

**Comment by kayrus** [comment]
@jtopjian done + #1009. Not sure whether tests are required for the `ListOpts`.

**Comment by jtopjian** [comment]
@kayrus I've merged #1010 which added this functionality to the "external" Neutron API extension. Please let me know if you have any questions.

**Comment by kayrus** [comment]
@jtopjian thank you for your cooperation.

**Pull request closed without merging**
