### PR TITLE
[rfr] Adding Vip port ID for loadbalancer

### PR DESCRIPTION
**Pull request by dagnello**
For #9 

Vip port ID is actually being returned by the lbaas api although
documentation does not reference it (Issue #9).  This PR exposes this important
attribute when creating or listing loadbalancers.

REQ: curl -g -i --cacert "/home/sabhaya/ipc/cacert.cer" -X POST
https://10.243.189.6:9696/v2.0/lbaas/loadbalancers.json -H "User-Agent:
python-neutronclient" -H "Content-Type: application/json" -H "Accept:
application/json" -H "X-Auth-Token:
{SHA1}197d9453ec40aa1453b88ed2fd31dc22ee9bb6d3" -d '{"loadbalancer":
{"vip_subnet_id": "6cfcd316-6060-42e3-95a7-fe5dd7ba6f46", "description":
"vipul-test", "admin_state_up": true}}'
DEBUG: keystoneauth.session RESP: [201] Content-Type: application/json
Content-Length: 430 X-Openstack-Request-Id:
req-c38d6086-77d6-4f91-94d1-b6f233cf90c0 Date: Thu, 07 Jul 2016 00:13:58
GMT Connection: keep-alive
RESP BODY: {"loadbalancer": {"description": "vipul-test",
"admin_state_up": true, "tenant_id": "4c45f9757fce480c875e096fba3e254e",
"provisioning_status": "PENDING_CREATE", "listeners": [], "vip_address":
"10.0.2.31", "vip_port_id": "4e901618-0a8d-4d46-861c-28fad2df7a8c",
"provider": "octavia", "vip_subnet_id":
"6cfcd316-6060-42e3-95a7-fe5dd7ba6f46", "id":
"c28cf436-f201-4c4f-be63-ecbd092aae63", "operating_status": "OFFLINE",
"name": ""}}

Created a new loadbalancer:
+---------------------+--------------------------------------+
| Field               | Value                                |
+---------------------+--------------------------------------+
| admin_state_up      | True                                 |
| description         | vipul-test                           |
| id                  | c28cf436-f201-4c4f-be63-ecbd092aae63 |
| listeners           |                                      |
| name                |                                      |
| operating_status    | OFFLINE                              |
| provider            | octavia                              |
| provisioning_status | PENDING_CREATE                       |
| tenant_id           | 4c45f9757fce480c875e096fba3e254e     |
| vip_address         | 10.0.2.31                            |
| vip_port_id         | 4e901618-0a8d-4d46-861c-28fad2df7a8c |
| vip_subnet_id       | 6cfcd316-6060-42e3-95a7-fe5dd7ba6f46 |
+---------------------+———————————————————+"}}'"

### CODE REVIEW

**Comment by jrperritt** [comment]
Per [the style guide](https://github.com/gophercloud/gophercloud/blob/master/STYLEGUIDE.md#on-pull-requests), please provide a link to the source where this can be verified. I can see the field in the curl output, but seeing it in the source will be useful for future reference.

**Comment by dagnello** [comment]
@jrperritt the link to the specific vip_port_id in lbaas v2 is:
https://github.com/openstack/neutron-lbaas/blob/master/neutron_lbaas/extensions/loadbalancerv2.py#L207

a link to this doc is already included here:
https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/extensions/lbaas_v2/doc.go

**Comment by jrperritt** [comment]
It looks like the source is saying `vip_port_id` isn't allowed for `create` nor `update` operations, but you've added it as a field to the `create` operation. Am I misinterpreting the OpenStack source code?

**Comment by dagnello** [comment]
@jrperritt including it in the create is a typo.

**Comment by jrperritt** [comment]
+2

**Comment by dagnello** [comment]
@jrperritt thanks!

**Comment by jrperritt** [comment]
@dagnello do you still need the `rackspace/gophercloud` PR merged?

**Pull request merged**
