### PR TITLE
Feature/filestorage sharetype getdefault

### PR DESCRIPTION
**Pull request by ehdou**
Add support for Share Type Get Default
For #140

### CODE REVIEW

**Comment by ehdou** [comment]
[Get default function](https://github.com/openstack/manila/blob/16c522bf5e5c3d37018caef11dd7852462193327/manila/api/v2/share_types.py#L79) for share type

**Comment by ehdou** [comment]
@jrperritt This PR is ready for review. It's based on [PR#143](https://github.com/gophercloud/gophercloud/pull/143) and adds support for share type Get Default

**Comment by ehdou** [comment]
@jrperritt This PR has been rebased and is ready for review

**Comment by jrperritt** [comment]
+2

**Pull request merged**
