### PR TITLE
blockstorage/v3: Add support for list qos

### PR DESCRIPTION
**Pull request by nikParasyr**
For #2139 

[docs](https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=list-qos-specifications-detail#quality-of-service-qos-specifications-qos-specs)

[code](https://github.com/openstack/cinder/blob/393c2e4ad90c05ebf28cc3a2c65811d7e1e0bc18/cinder/api/contrib/qos_specs_manage.py#L58) [code](https://github.com/openstack/cinder/blob/393c2e4ad90c05ebf28cc3a2c65811d7e1e0bc18/cinder/volume/qos_specs.py#L233)

### CODE REVIEW

**Comment by jtopjian** [comment]
@nikParasyr Thanks! I'm working on getting OpenLab fixed

**Review by jtopjian — COMMENTED** [review]
@nikParasyr Thanks! I've left one non-blocking comment.

If you can confirm that the acceptance tests pass, I can merge this while we're waiting for the OpenLab test issues to resolve.

**Comment by nikParasyr** [comment]
@jtopjian I cannot see the non-blocking comment :thinking: 

> If you can confirm that the acceptance tests pass, I can merge this while we're waiting for the OpenLab test issues to resolve

From my side it's ok to wait for the fix. I'll be off for the coming 10 days for vacation and other things. When i get back if OpenLab is not fixed yet ill make a devstack environment and provide the output.

**Comment by nikParasyr** [comment]
@jtopjian Ive rebased with all the latest and greatest from master but openlab still fails. It seems a bit unrelated with my addition.
I ran the tests on a train cluster. Results:
Acceptane:
```
gophercloudtest TestQoS blockstorage/v3                                                                                                                                                                                                                                                                                  7.16G   100% 🔋  10087  17:16:01  
~/go/src/github.com/gophercloud/gophercloud ~
=== RUN   TestQoS
    TestQoS: blockstorage.go:281: Attempting to create QoS: ACPTTESTPjXBbX0wT5Il0628
    TestQoS: tools.go:80: {
          "name": "ACPTTESTPjXBbX0wT5Il0628",
          "id": "9d3a1f49-b855-4bea-91a1-80db6008f7c2",
          "consumer": "front-end",
          "specs": {
            "read_iops_sec": "20000"
          }
        }
    TestQoS: blockstorage.go:301: Successfully created QoS: 9d3a1f49-b855-4bea-91a1-80db6008f7c2
    TestQoS: blockstorage.go:281: Attempting to create QoS: ACPTTESTpLcdJVmlgMPKtw5U
    TestQoS: tools.go:80: {
          "name": "ACPTTESTpLcdJVmlgMPKtw5U",
          "id": "083b77a8-a383-4061-86d4-241455e07766",
          "consumer": "front-end",
          "specs": {
            "read_iops_sec": "20000"
          }
        }
    TestQoS: blockstorage.go:301: Successfully created QoS: 083b77a8-a383-4061-86d4-241455e07766
    TestQoS: blockstorage.go:309: Attempting to delete QoS: 083b77a8-a383-4061-86d4-241455e07766
    TestQoS: blockstorage.go:320: Successfully deleted QoS: 083b77a8-a383-4061-86d4-241455e07766
    TestQoS: blockstorage.go:309: Attempting to delete QoS: 9d3a1f49-b855-4bea-91a1-80db6008f7c2
    TestQoS: blockstorage.go:320: Successfully deleted QoS: 9d3a1f49-b855-4bea-91a1-80db6008f7c2
--- PASS: TestQoS (0.96s)
PASS
ok  	github.com/gophercloud/gophercloud/acceptance/openstack/blockstorage/v3	0.962s
```

Unit:
```
go test -v -tags fixtures ./...                                                                                                                                                                                                                                                                                                               7.12G   100% 🔋  10092  17:22:08  
?   	github.com/gophercloud/gophercloud/openstack/blockstorage/v3/qos	[no test files]
=== RUN   TestCreate
--- PASS: TestCreate (0.00s)
=== RUN   TestDelete
--- PASS: TestDelete (0.00s)
=== RUN   TestList
--- PASS: TestList (0.00s)
PASS
ok  	github.com/gophercloud/gophercloud/openstack/blockstorage/v3/qos/testing	0.005s
```

**Review by jtopjian — APPROVED** [review]
LGTM - thank you!

**Pull request merged**
