### PR TITLE
Acceptance test job definition cleanup

### LINKED ISSUE #994: openlab CI job config cleanup
For historical reasons, the acceptance job only covers partial of the acceptance test
Now the job is moved to gophercloud repo,
.zuul/playbooks/gophercloud-acceptance-test/run.yaml
so we can do some cleanup and enable more acceptance tests as needed.

Currently enabled tests:
              # Only enable these successful test cases
              go test -v -tags "fixtures acceptance" ./acceptance/openstack/identity/v3/
              go test -v -tags "fixtures acceptance" ./acceptance/openstack/networking/v2/
              go test -v -tags "fixtures acceptance" ./acceptance/openstack/blockstorage/v2/
              go test -v -tags "fixtures acceptance" -run "SecGroup|Flavor" ./acceptance/openstack/compute/v2/
              # To enable more after the fix of https://github.com/gophercloud/gophercloud/issues/608
              # go test -v -tags "fixtures acceptance" ./acceptance/openstack/imageservice/v2/
              # go test -v -tags "fixtures acceptance" ./acceptance/openstack/identity/v2/
              # go test -v -tags "fixtures acceptance" ./acceptance/openstack/compute/v2/
              } 2>&1 | tee $TEST_RESULTS_TXT

### PR DESCRIPTION
**Pull request by yongfengdu**
Remove the unused theopenlab/gophercloud branches.
Put env variables setup for accp test into script/stackenv.
Move the test case enable/disable to script/acceptancetest.

Closed #994

### CODE REVIEW

**Comment by yongfengdu** [comment]
@jtopjian After this PR merged, I'm done with the CI job definition clean up.
In the future, you can modify script/acceptancetest for test job adjustment.

Usually you don't need to modify the job definitions under .zuul/playbooks, unless you require more services running on devstack.

**Comment by jtopjian** [comment]
> Usually you don't need to modify the job definitions under .zuul/playbooks, unless you require more services running on devstack.

Ah, I didn't realize we would be able to control the services that ran, too. This will be useful.

Are we able to create new job definitions, such as the various "recheck/x" jobs that are configured?

**Comment by yongfengdu** [comment]
@jtopjian Yes, you can create new job. Take a look at .zuul.yaml file, where have the "project" and "job" definitions.

**Comment by jtopjian** [comment]
Got it - thank you :)

Is this PR ready to merge?

**Comment by yongfengdu** [comment]
Yes, it's ready to merge.

**Comment by jtopjian** [comment]
Thank you for you and your teams help with this. This integration is really appreciated as is the help and support provided :)

**Pull request merged**
