### PR TITLE
Acc Tests: Temporarily disabling octavia/lbaas

### PR DESCRIPTION
**Pull request by jtopjian**
For #818 
For https://github.com/theopenlab/openlab/issues/192

### CODE REVIEW

**Comment by hongbin** [comment]
There are several failure in the acceptance test. One of the failure in the capsule test might be fixed by: https://github.com/gophercloud/gophercloud/pull/1456

**Comment by jtopjian** [comment]
ah - interesting. Enabling Octavia in devstack also enabled Barbican.

@hongbin Yeah, once I can get the test failures down to just zun, I'll merge this and then you can rebase and we'll see if everything works :)

**Comment by hongbin** [comment]
@jtopjian sure

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
@hongbin You're good to go with the rebase.

**Pull request merged**
