### PR TITLE
feat: update Messaging v2 API to support _enable_encrypt_messages field

### PR DESCRIPTION
**Pull request by galuszkak**
Prior to starting a PR, please make sure you have read our
[contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial).

Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #2015 

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:
https://docs.openstack.org/api-ref/message/?expanded=show-queue-details-detail

### CODE REVIEW

**Comment by jtopjian** [comment]
@galuszkak Thank you for submitting this.

Per the contributor tutorial linked above, API doc references aren't enough to determine if this is a valid OpenStack feature. Please see [Step 3](https://github.com/gophercloud/gophercloud/blob/master/docs/contributor-tutorial/step-03-code-hunting.md) specifically and let me know if you have any questions.

**Comment by galuszkak** [comment]
Hi @jtopjian ,

If I understand your ask correctly does below proofs are enough, or there is something still needed?
https://github.com/openstack/zaqar/blob/master/zaqar/transport/validation.py#L344-L347
https://github.com/openstack/zaqar/commit/e12c65a369825ea5469bdb31f5c7151268d7926b

Thanks for helping!

**Comment by jtopjian** [comment]
@galuszkak Yes, that's perfect 🙂 

One extra thing to consider here is that you have a combination of `bool` and `omitempty`. This means that a value of false will _never_ be sent in the JSON request. According to the service-side code (https://github.com/openstack/zaqar/blob/master/zaqar/transport/validation.py#L344), the default value is false, so this combination should be fine. However, if you want the ability to explicitly send a value of false, this will need changed to `*bool`.

There's also some `ListOpts` fields you've added in this PR. We'll need to dig up the code references for those, too. Alternatively, you can leave them out of this PR and submit them in a new PR.

**Comment by galuszkak** [comment]
@jtopjian thanks for feedback.

I've applied it. I will sent `name` and `with_count` in separate PR  as it makes more sense to seperate those changes.

**Review by jtopjian — APPROVED** [review]
LGTM - thank you!

**Pull request merged**
