### PR TITLE
Add AvailabilityZone field to DBaaS instance

### PR DESCRIPTION
**Pull request by pawcykca**
Fixes https://github.com/gophercloud/gophercloud/issues/2483

Openstack API Ref:
https://docs.openstack.org/api-ref/database/?expanded=create-database-instance-detail#create-database-instance

### CODE REVIEW

**Comment by mandre** [comment]
Thanks for the PR.
Ideally we should have a CI for DBaaS before merging this change so that we're sure we don't break anything.
Also, since we modify the CreateOpts struct, it's also a breaking change so adding the `semver:major` label.

**Comment by mandre** [comment]
> Thanks for the PR. Ideally we should have a CI for DBaaS before merging this change so that we're sure we don't break anything. Also, since we modify the CreateOpts struct, it's also a breaking change so adding the `semver:major` label.

I talked to @pierreprinetti and we decided to relax this rule so that we don't categorize changes as breaking changes when you're not impacted with a normal usage of the library. We'll rely on `gorelease` to let us know if changes are to be considered backward-compatible or not.

In this case:
```
# github.com/gophercloud/gophercloud/openstack/db/v1/instances
## compatible changes
CreateOpts.AvailabilityZone: added
```

**Comment by EmilienM** [comment]
@mandre I'll be fine merging as is, even if we don't have CI. I don't think any of us currently has the time to add CI for DBaaS.

**Review by EmilienM — APPROVED** [review]

**Comment by EmilienM** [comment]
Please rebase

**Comment by pawcykca** [comment]
@EmilienM what about this PR?

**Comment by pawcykca** [comment]
@mandre @EmilienM 
Can we go on with this PR?

**Comment by pawcykca** [comment]
@mandre @EmilienM 
Once again, can we go on with this PR?

**Comment by EmilienM** [comment]
@pawcykca sorry we have been fixing a few CI things and produced a release. Could you please rebase on master. Thanks

**Comment by pawcykca** [comment]
Can by closed. Done in PR #2871

**Pull request closed without merging**
