### PR TITLE
[WIP] Support showing Magnum bays

### PR DESCRIPTION
**Pull request by carolynvs**
For #10

- [x] GET /bays
- [x] Unit tests
- [ ] Acceptance tests

### CODE REVIEW

**Comment by carolynvs** [comment]
Should I leave off writing the acceptance tests until I go do a full CRUD test, e.g. create, list, get, update, delete?

**Comment by jrperritt** [comment]
Let's add each acceptance test to its PR (`Get` for this one). They don't run at build (yet) like the unit tests do.

**Comment by jrperritt** [comment]
Also note that currently this PR is against `master` instead of `magnum`.

**Comment by carolynvs** [comment]
Drat, I'll kill this and make another that points to the `magnum` branch.

**Comment by jrperritt** [comment]
I'll try to keep `magnum` in parity with `master`

**Pull request closed without merging**
