### PR TITLE
Fix the CI report issue

### PR DESCRIPTION
**Pull request by yongfengdu**
CI report SUCCESS when some test cases fails.

For theopenlab/openlab-zuul-jobs#219

### CODE REVIEW

**Comment by yongfengdu** [comment]
recheck

**Comment by jtopjian** [comment]
@yongfengdu I apologize for the delay. This looks good to me. Is this ready to be merged?

**Comment by yongfengdu** [comment]
@jtopjian Yes, this is ready to merge :)

**Comment by jtopjian** [comment]
Sounds good. Thank you! :)

**Pull request merged**
