### PR TITLE
Blockstorage service list support

### PR DESCRIPTION
**Pull request by ildarsv**
For #732 

API reference:
https://developer.openstack.org/api-ref/block-storage/v3/index.html#list-all-cinder-services

Implementation:
https://github.com/openstack/cinder/blob/stable/ocata/cinder/api/contrib/services.py#L46-L102

### CODE REVIEW

**Comment by jrperritt** [comment]
@ildarsv Thank you for the PR, but we need the exact line number(s) of the implementation; just giving the link to an entire file usually isn't enough. The references need to be to the function, the request parameters, and the response parameters.

**Comment by ildarsv** [comment]
@jrperritt I'm sorry, my bad. I've updated the link.

**Comment by jtopjian** [comment]
@ildarsv No problem and thanks :)

Overall this is good, but it looks like there are some `ListOps` for this action:

https://github.com/openstack/cinder/blob/stable/ocata/cinder/api/contrib/services.py#L58-L61

Would you be able to implement that? Using the `ListOpts` from another blockstorage package as an example should be fine - I don't see anything out of the ordinary happening here. Let me know if you need help, though.

**Comment by ildarsv** [comment]
@jtopjian yes, sure! Please review :)

**Comment by jtopjian** [comment]
@ildarsv This looks good to me. Thanks :)

**Pull request merged**
