### PR TITLE
baremetal: add API to set maintenance and maintenance reason

### LINKED ISSUE #2383: Missing maintenance API for baremetal Node
For very historical reasons, Ironic requires a special API to set maintenance and maintenance_reason.
While the maintenance itself can be set directly (for even more historical reasons), the reason cannot.

### PR DESCRIPTION
**Pull request by dtantsur**
Fixes #2383

See https://docs.openstack.org/api-ref/baremetal/?expanded=set-maintenance-flag-detail,clear-maintenance-flag-detail#set-maintenance-flag for API reference.

### CODE REVIEW

**Comment by EmilienM** [comment]
@dtantsur thanks for your PR :-)
Would you be able to add tests (fixtures and acceptance) if possible?

**Comment by dtantsur** [comment]
Yep, working on exactly that (struggling to even compile anything locally, meh)

**Comment by dtantsur** [comment]
Okay, this has acceptance tests (that I couldn't verify locally, so may not even compile). I'll look into fixtures tomorrow, need to understand what they are.

**Comment by EmilienM** [comment]
LGTM

**Pull request merged**
