### PR TITLE
Added missing Octavia fields to Member

### PR DESCRIPTION
**Pull request by JackKuei**
For #[1254 [Bug Octavia: Missing fields for load balancer's pool member]](https://github.com/gophercloud/gophercloud/issues/1254)

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[[octavia:member]](https://github.com/openstack/octavia/blob/master/octavia/api/v2/types/member.py#L27)

### CODE REVIEW

**Comment by JackKuei** [comment]
@jtopjian Not sure if this is the proper way to make the fix since there was a discussion earlier https://github.com/gophercloud/gophercloud/issues/1149. But this will populate the Member with Octavia values.

**Comment by jtopjian** [comment]
@JackKuei Are you sure you wanted to modify the LBaaS Pool package rather than the [Octavia one](https://github.com/gophercloud/gophercloud/tree/master/openstack/loadbalancer/v2/pools)?

**Comment by JackKuei** [comment]
@jtopjian Now that you mentioned it, let me take a look at the octavia one.

**Comment by JackKuei** [comment]
Possibly invalid. Will reopen if it is an actual issue.

**Comment by JackKuei** [comment]
@jtopjian This is ready to be reviewed. The missing octavia pool member fields were moved into loadbalancer package from networking extensions

**Comment by jtopjian** [comment]
@kiwik @yongfengdu @liu-sheng Hi all - looks like OpenLab has been stuck for a few days.

**Comment by mrhillsman** [comment]
@jtopjian not sure what happened but things were fine the other day; i believe some maintenance on various clouds could be the issue, we are checking things

**Comment by mrhillsman** [comment]
recheck

**Comment by jtopjian** [comment]
@mrhillsman Awesome - thank you, Melvin!

**Comment by mrhillsman** [comment]
recheck

**Comment by jtopjian** [comment]
recheck

**Comment by jtopjian** [comment]
@mrhillsman Thank you again for your help with the OpenLab tests.

**Pull request merged**
