### PR TITLE
feat: add name and with_count params into listing queues

### PR DESCRIPTION
**Pull request by galuszkak**
For #2017 

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

https://github.com/openstack/zaqar/blob/e12c65a369825ea5469bdb31f5c7151268d7926b/zaqar/transport/wsgi/v2_0/queues.py#L300-L301
https://github.com/openstack/zaqar/blob/e12c65a369825ea5469bdb31f5c7151268d7926b/zaqar/transport/wsgi/v2_0/queues.py#L260-L270

### CODE REVIEW

**Comment by galuszkak** [comment]
I've looked on failing test in acceptance testing but it's related to OAuth. I'm not sure if that error is related to my changes. @jtopjian could you maybe help me understand a little bit how I should read those logs?

**Comment by jtopjian** [comment]
@galuszkak Sorry - I looked at this yesterday but forgot to comment.

It's not related to this PR, so it can be ignored. I'm quite sure I fixed this test already, so if you wanted to, do a git fetch on the upstream Gophercloud master branch into your fork, rebase your branch, and then force-push. You don't need to do that for this PR, but might be a good idea for future PRs.

**Comment by galuszkak** [comment]
@jtopjian but this is up to date master branch. So I think something is broken on master.

```
➜  gophercloud git:(feature/messaging-filter-update) git fetch
➜  gophercloud git:(feature/messaging-filter-update) git rebase origin/master
Current branch feature/messaging-filter-update is up to date.
➜  gophercloud git:(feature/messaging-filter-update) git remote -v
galuszkak	git@github.com:galuszkak/gophercloud.git (fetch)
galuszkak	git@github.com:galuszkak/gophercloud.git (push)
origin	git@github.com:gophercloud/gophercloud.git (fetch)
origin	git@github.com:gophercloud/gophercloud.git (push)
```

**Comment by jtopjian** [comment]
arg. You're right. _I_ was on an outdated branch when I looked at this.

Yeah, that test in general needs cleaned up. Please ignore it.

**Comment by jtopjian** [comment]
@galuszkak Ignoring the test failures, is this ready to be reviewed/merged?

**Comment by galuszkak** [comment]
@jtopjian yes. I was concerned only with failing tests.

**Review by jtopjian — APPROVED** [review]
LGTM - thank you!

**Pull request merged**
