### PR TITLE
Enable Octavia and run its acceptance tests

### PR DESCRIPTION
**Pull request by hongbin**
https://github.com/theopenlab/openlab-zuul-jobs/issues/143

For #818

### CODE REVIEW

**Comment by hongbin** [comment]
Awaiting for the depending PR https://github.com/theopenlab/openlab-zuul-jobs/pull/227 to be merged in order to remove the [WIP]

**Comment by hongbin** [comment]
recheck

**Comment by hongbin** [comment]
recheck

**Comment by hongbin** [comment]
recheck

**Comment by hongbin** [comment]
@jtopjian  ping for review

**Comment by jtopjian** [comment]
> It is possibly due to the fact that creating an octavia loadbalancer needs to spin up a VM inside a VM. 

The Octavia tests are taking 700 seconds, which isn't bad:

```
2018-07-02 19:20:16.862800 | ubuntu-xenial | ok  	github.com/gophercloud/gophercloud/acceptance/openstack/loadbalancer/v2	731.944s
```

Total time to run all tests is only 28 minutes:

```
2018-07-02 19:20:23.247969 | ubuntu-xenial | ok: Runtime: 0:27:54.283785
```

The bulk of the time taken is setting up the environment

**Pull request merged**
