### PR TITLE
Magnum: Manage Clusters Delete

### PR DESCRIPTION
**Pull request by JackKuei**
Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #[1062 [Migrate Magnum Branch Onto Master]](https://github.com/gophercloud/gophercloud/issues/1062)

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[[clusters:delete]](https://github.com/openstack/magnum/blob/master/magnum/api/controllers/v1/cluster.py#L560)

### CODE REVIEW

**Comment by JackKuei** [comment]
@jtopjian made the change, but currently I don't have an environment to test it on.

**Comment by jtopjian** [comment]
@JackKuei Just to confirm, this is ready for merge? I realize I did the review early, while this is still marked as `[WIP]`, but this all looks good to me.

**Comment by JackKuei** [comment]
@jtopjian Removed [WIP], ready to be merged.

**Comment by JackKuei** [comment]
@ozerovandrei After this is merged, magnum clusters will be complete.

**Comment by ozerovandrei** [comment]
@JackKuei that’s amazing. Thanks for the hard work!
I will start implementing cluster resource in the terraform provider right after it merged.

**Comment by jtopjian** [comment]
> @JackKuei that’s amazing. Thanks for the hard work!

+1

Thank you for your hard work on this series.

**Comment by JackKuei** [comment]
@jtopjian @ozerovandrei Thanks for the reviews and testing. And thanks for letting me to help you to help me....or something like that...:)  Looking forward to see the terraform-provider-openstack support.

**Pull request merged**
