### PR TITLE
Feature/filestorage sharetype addaccess

### PR DESCRIPTION
**Pull request by ehdou**
Add support for Share Type Add Access
For #140

### CODE REVIEW

**Comment by ehdou** [comment]
[Add access function](https://github.com/openstack/manila/blob/16c522bf5e5c3d37018caef11dd7852462193327/manila/api/v2/share_types.py#L239) for share type

**Comment by ehdou** [comment]
@jrperritt This PR is ready for review. It's based on [PR#149](https://github.com/gophercloud/gophercloud/pull/149) and adds support for share type Add Access

**Comment by ehdou** [comment]
@jrperritt This PR is ready for review

**Comment by jtopjian** [comment]
This looks good to me. I ran into the same problem where the acceptance test changes were required here, too, but I did a test merge and everything worked out. Thanks for this!

**Pull request merged**
