### PR TITLE
AllPages() - Do not fetch twice the first page

### PR DESCRIPTION
**Pull request by garbage-collector**
For #1054

This is the quickest way I found to fix the issue. Other ways I found generate a bigger rewriting.

The goal is to change the "testPage" as a "firstPage". Once it has been already fetched, there is no need to fetch it again.

It avoids N+1 calls on each usage of AllPages()

### CODE REVIEW

**Comment by jtopjian** [comment]
@garbage-collector Nice! :)

@jrperritt Thoughts on this?

**Comment by Dexus** [comment]
Looks good. Do what you want and definitely save a request! If I look at some of our tests, that's 30k requests a day less!

**Comment by garbage-collector** [comment]
On our side, we are thinking to move our codebase from some homemade code to gophercloud, and this patch will save around 8.000.000 calls per day on our OpenStack infrastructure, so thanks for approving, we can continue to rewrite stuff on our codebase :)

**Comment by jrperritt** [comment]
Seems fine to me

**Comment by jtopjian** [comment]
@garbage-collector Thank you for digging into this and submitting a fix :)

Quick side note about saving calls: if you want to minimize the amount of communication traffic, I recommend using `EachPage` instead of `AllPages`. Most of the documentation will use `AllPages` because it's more succinct, but for greater control and the least amount of calls, `EachPage` is the way to go.

**Comment by jtopjian** [comment]
Looks like go tip is not liking this patch for some reason... it might be a temporary issue or some new feature in Go within the past few days:

https://travis-ci.org/gophercloud/gophercloud/jobs/398304237

**Comment by Dexus** [comment]
The GO tests never run there...
So it looks like a temp failure

Von meinem iPhone gesendet

**Comment by jtopjian** [comment]
> The GO tests never run there...

The test ran before and passed.

> So it looks like a temp failure

It's possible or it's possible it's a new change in Go that will be permanent and we'll need to figure out what's different

Go 1.10 tests are still passing, so it's something specific in tip.

**Comment by jtopjian** [comment]
I don't think the Travis error is due to this merge. I think it's coincidental that Travis began failing after this was merged.

While the error in question is due to a miscount of the actual number of pages, I think it's due to the actual test fixture itself. I'm going to open a PR to confirm this.

**Pull request merged**
