### PR TITLE
keystone: add v3 limits update operation

### LINKED ISSUE #2289: Add support for identity v3 limits
As part of the `unified limits` keystone has added a `limits` api.
Add support for it.

[docs](https://docs.openstack.org/api-ref/identity/v3/?expanded=list-projects-detail#unified-limits)
[code](https://github.com/openstack/keystone/blob/34a37772e866074f0bc5413c18bb446ac8c1d17e/keystone/api/limits.py)

TO-DO:
- [x] List Limits
- [x] Create Limit
- [x] Show Limit
- [x] Delete Limit
- [x] Update Limits
- [x] Get Enforcement Model

### PR DESCRIPTION
**Pull request by emilmaruszczak**
For #2289

[docs](https://docs.openstack.org/api-ref/identity/v3/#update-limit)
[code](https://github.com/openstack/keystone/blob/stable/yoga/keystone/api/limits.py#L115)

This is a base for detail and delete operations code I prepared.

### CODE REVIEW

**Comment by mandre** [comment]
Hi @emilmaruszczak, thanks for your work on https://github.com/gophercloud/gophercloud/issues/2289. Just so that we know, do you have more PRs in stock for identity v3 limits?
I already mentioned it in your other PR, it would be really nice if you could add acceptance tests. This way we can ensure the code works for all supported versions of openstack. Thanks.

**Comment by emilmaruszczak** [comment]
> Hi @emilmaruszczak, thanks for your work on #2289. Just so that we know, do you have more PRs in stock for identity v3 limits? I already mentioned it in your other PR, it would be really nice if you could add acceptance tests. This way we can ensure the code works for all supported versions of openstack. Thanks.

Hey, yes, I do have all the other operations implemented - I am not pushing them out because they depend on these operations models and so I think it's easier for the merging and reviwing.

I'll add the acceptance tests to all operations as well.

**Comment by emilmaruszczak** [comment]
@mandre this is ready to be merged in.

**Review by mandre — APPROVED** [review]
If I kept count correctly, the last remaining thing for https://github.com/gophercloud/gophercloud/issues/2289 is the delete call?

**Comment by emilmaruszczak** [comment]
> If I kept count correctly, the last remaining thing for #2289 is the delete call?

You are right, #2618 is ready, waiting for actions to pass.

**Pull request merged**
