### PR TITLE
Feature/filestorage securityservices update

### PR DESCRIPTION
**Pull request by ehdou**
Add support for Security Service Update
For #131

### CODE REVIEW

**Comment by ehdou** [comment]
[Update function](https://github.com/openstack/manila/blob/16c522bf5e5c3d37018caef11dd7852462193327/manila/api/v1/security_service.py#L157) for security services

**Comment by ehdou** [comment]
@jrperritt This PR is ready for review. It's based on [PR#135](https://github.com/gophercloud/gophercloud/pull/135) and adds support for security service Update

**Comment by jtopjian** [comment]
@ehdou This probably needs a quick rebase. Ping when ready for review :)

**Comment by ehdou** [comment]
@jtopjian I rebased this PR, it's ready for review

**Comment by jtopjian** [comment]
LGTM! Thanks.

**Pull request merged**
