### PR TITLE
Add resource provider allocations API for placement

### PR DESCRIPTION
**Pull request by abnvanand**
For #526

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

API doc:
https://docs.openstack.org/api-ref/placement/?expanded=list-resource-provider-usages-detail#list-resource-provider-allocations

API code:
https://github.com/openstack/placement/blob/2150dbf6880c379b52035b604c51048743c446a5/placement/handlers/allocation.py#L271

### CODE REVIEW

**Comment by abnvanand** [comment]
Hi @jtopjian. This PR adds API to get allocations for a resource provider.
Can you please review? 

Thanks

**Comment by jtopjian** [comment]
I think this is the best representation of the schema: https://github.com/openstack/placement/blob/6f00ba5f685183539d0ebf62a4741f2f6930e051/placement/schemas/allocation.py#L75-L126

It also details a `project_id` and `user_id`, however, from looking at the acceptance test output, those are not used in the final response.

**Comment by jtopjian** [comment]
@abnvanand Looks like this needs `gofmt` run on it. Other than that, this looks good to me and I can merge once that's fixed.

**Comment by abnvanand** [comment]
Fixed formatting.

**Review by jtopjian — APPROVED** [review]
LGTM - Thank you!

**Comment by jtopjian** [comment]
@abnvanand Thanks so much for working on this.

**Pull request merged**
