### PR TITLE
Feature/filestorage sharetype delete

### PR DESCRIPTION
**Pull request by ehdou**
Add support for Share Type Delete
For #140

### CODE REVIEW

**Comment by ehdou** [comment]
[Delete function](https://github.com/openstack/manila/blob/16c522bf5e5c3d37018caef11dd7852462193327/manila/api/v2/share_types.py#L189) for the share types

**Comment by ehdou** [comment]
@jrperritt This PR is ready for review. It's based on [PR#141](https://github.com/gophercloud/gophercloud/pull/141) and adds support for share type Delete

**Comment by ehdou** [comment]
@jrperritt This PR has been rebased and is ready for review

**Comment by jrperritt** [comment]
+2

**Pull request merged**
