### PR TITLE
CI/semver: only run on master

### PR DESCRIPTION
**Pull request by EmilienM**
We don't want these workflows to run on other branches than master.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
> We don't want these workflows to run on other branches than master.

Why not? I think they should run on all branches

**Comment by pierreprinetti** [comment]
The corollary, of course, is that we should also set up a bot that applies the semver label.

**Comment by EmilienM** [comment]
> > We don't want these workflows to run on other branches than master.
> 
> Why not? I think they should run on all branches

I'm not sure why we would run it on a stable branch.

**Comment by EmilienM** [comment]
I don't have a strong opinion on this one, I'll let @mandre give his opinion as well and then we can make a decision.

**Comment by mandre** [comment]
I think it's still useful to check for API changes on the v1 branch in case someone submits a PR directly to v1. It could be a direct fix for code that is no longer in master, or a backport that does not apply cleanly for example. In these cases, we would still want to ensure we're not breaking the API compatibility in the stable branch.

**Comment by mandre** [comment]
I believe we should close this PR in favor of https://github.com/gophercloud/gophercloud/pull/2674.

**Review by mandre — CHANGES_REQUESTED** [review]
I believe we should close this PR in favor of https://github.com/gophercloud/gophercloud/pull/2674.

**Comment by pierreprinetti** [comment]
>I think it's still useful to check for API changes on the v1 branch in case someone submits a PR directly to v1

Also once the branches diverge, there is a chance that a PR that is "patch" on main becomes "minor" or "major" on v1

**Pull request closed without merging**
