### PR TITLE
Feature/filestorage sharetype list

### PR DESCRIPTION
**Pull request by ehdou**
Add support for Share Type List
For #140

### CODE REVIEW

**Comment by ehdou** [comment]
[List function](https://github.com/openstack/manila/blob/16c522bf5e5c3d37018caef11dd7852462193327/manila/api/v2/share_types.py#L96) for share types

**Comment by ehdou** [comment]
@jrperritt This PR is ready for review. It's based on [PR#142](https://github.com/gophercloud/gophercloud/pull/142) and adds support for share type List

**Comment by ehdou** [comment]
@jrperritt This PR has been rebased and is ready for review. I didn't find any mention of `limit` nor `offset` in the code so I chose to use `SinglePageBase`. If you think another type would be more appropriate let me know.

**Comment by jrperritt** [comment]
+2

**Pull request merged**
