### PR TITLE
Senlin: Nodes List

### PR DESCRIPTION
**Pull request by JackKuei**
Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #[823 [Add support for Senlin clustering]](https://github.com/gophercloud/gophercloud/issues/823)

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[[nodes:list]](https://github.com/openstack/senlin/blob/e5bc16b3fea2f10dead365f983c5a937f23d72b0/senlin/api/openstack/v1/nodes.py#L91)

### CODE REVIEW

**Comment by JackKuei** [comment]
Format errors seems to be from /openstack/networking/v2/extensions/vpnaas/ikepolicies/testing/requests_test.go and not from this PR

**Comment by jtopjian** [comment]
@JackKuei Yeah, it's been fixed in https://github.com/gophercloud/gophercloud/pull/892

**Comment by JackKuei** [comment]
recheck

**Comment by JackKuei** [comment]
recheck

**Comment by JackKuei** [comment]
recheck

**Pull request closed without merging**
