### PR TITLE
Compute V2: add tags Check call

### PR DESCRIPTION
**Pull request by ozerovandrei**
Add Check method for tags extension.
Update docs and inline comments.

Provide unit tests.

For #1669

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

https://github.com/openstack/nova/blob/stable/stein/nova/api/openstack/compute/server_tags.py#L66
https://github.com/openstack/nova/blob/stable/stein/nova/objects/tag.py#L50

### CODE REVIEW

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
```
2019-08-15 06:39:44.327845 | ubuntu-xenial | === RUN   TestVolumeActionsAttachCreateDestroy
2019-08-15 06:41:08.691806 | ubuntu-xenial | --- FAIL: TestVolumeActionsAttachCreateDestroy (84.37s)
2019-08-15 06:41:08.691943 | ubuntu-xenial |     compute.go:446: Attempting to create server: ACPTTESTLqQtGEPagoMI7DLB
2019-08-15 06:41:08.692103 | ubuntu-xenial |     convenience.go:35: [1;31mFailure in volumeactions_test.go, line 46: unexpected error [0m[1;33m"Instance in ERROR state"[0m[1;31m[0m
```

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
recheck

**Comment by huangtianhua** [comment]
recheck

**Pull request merged**
