### PR TITLE
Update capsule data model

### PR DESCRIPTION
**Pull request by hongbin**
We are going to update the capsule data model in server side [1].
This is the corresponding change in gophercloud.

[1] https://review.openstack.org/#/c/636070/

Prior to starting a PR, please make sure you have read our
[contributor tutorial](https://github.com/gophercloud/gophercloud/tree/master/docs/contributor-tutorial).

Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #[PUT ISSUE NUMBER HERE]

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[PUT URLS HERE]

### CODE REVIEW

**Comment by hongbin** [comment]
recheck

**Comment by hongbin** [comment]
@jtopjian It looks the CI failed from Octavia devstack plugin. Is anyone looking into the issue?

**Comment by jtopjian** [comment]
Yes, I've opened an issue about it: https://github.com/theopenlab/openlab/issues/192

**Comment by hongbin** [comment]
@jtopjian ping for review

**Comment by jtopjian** [comment]
@hongbin This looks like a pretty big breaking change.Some of the field names are having their JSON tags renamed, which helps. But will the removal of certain fields cause problems with anyone using this in any OpenStack version prior to the upcoming release?

**Comment by hongbin** [comment]
@jtopjian this does look like a really big change but it is unavoidable because we are consolidating the data model: https://review.openstack.org/#/c/636070/ . It is pretty much merge two database table into one so the change is big. It is very hard to maintain backward-compatibility while rolling out the change.

As far as I know, the only one who are using this API via gophercloud is: https://github.com/virtual-kubelet/virtual-kubelet/pull/239 . The PR is still open and I will patch that PR once we finish the data model merging.

**Comment by hongbin** [comment]
@kevin-zhaoshuai FYI

**Comment by jtopjian** [comment]
> As far as I know, the only one who are using this API via gophercloud is: [virtual-kubelet/virtual-kubelet#239](https://github.com/virtual-kubelet/virtual-kubelet/pull/239) 

Right, but wouldn't this put a limitation on anyone who uses `virtual-kubelet` to have to be running Zun master in production?

Similarly, if anyone wanted to make Terraform resources for Zun, only those running master+ would be able to use them. And if we already had Terraform resources, they would now be broke.

But maybe I'm not fully understanding the changes. If someone running Zun Stein were to use Gophercloud to obtain the information of a capsule, would they get any unmarshalling errors?

**Comment by jtopjian** [comment]
Sorry, not Stein - Rocky.

**Comment by hongbin** [comment]
We bump an API version for this series of change. So, a potential improvement is to add a check for the API version and process the response differently. If you prefer this approach, I need your help to show me some examples of how other projects are doing this.

**Comment by jtopjian** [comment]
Ahh, OK, so is this part of a microversion update or a standard major version update?

**Comment by hongbin** [comment]
It is part of a microversion update

**Comment by jtopjian** [comment]
OK, cool. We have some general guidelines on how to implement microversions here: https://github.com/gophercloud/gophercloud/blob/master/docs/MICROVERSIONS.md.

Unfortunately this change feels like it falls under "Modified Response Fields" which is the most difficult to implement in Go (or any typed language). Let me think on this one for a day.

**Comment by hongbin** [comment]
@jtopjian would you consider branching the gophercloud to match the openstack branching. For example, we could have gophercloud stable/rocky branch that matches to the corresponding openstack release.

**Comment by jtopjian** [comment]
> would you consider branching the gophercloud to match the openstack branching

That's a topic which has been discussed but it doesn't seem like it's practical to do. There are still lots of unimplemented API calls in Gophercloud, so the branches would be incomplete and put a lot of responsibility on backporting releveant API calls.

Since we already have separate packages for each major version, it helps Gophercloud support actions across multiple releases.

Microversions, while admirable for what they're trying to do, help with handling breaking changes within a major version, but they are not type friendly. They rely on being able to dynamically change an API response and have that API response be able to dynamically parse it.

The Microversions doc I linked to is the current set of best practices we've come up with for handling them.

**Comment by hongbin** [comment]
@jtopjian ACK, I will find a time to go through the Microversion doc.

Another thing I can offer is to add those removed fields back with placeholder value. Then, gophercloud can parse the response without error. What do you think?

**Comment by jtopjian** [comment]
> Another thing I can offer is to add those removed fields back with placeholder value. Then, gophercloud can parse the response without error. What do you think?

I think that would be a last resort. Thinking about this in a larger context, if we had to do the same thing for other services, things would get a little messy.

I have an idea that I'm going to work on - I'll post a link when it's ready.

**Comment by jtopjian** [comment]
@hongbin I have a possible solution here: https://github.com/gophercloud/gophercloud/compare/master...jtopjian:zun-capsule-microversion

The idea is that the application will either be hard-coded or somehow detect that the new microversion should be used and then do the following:

```go
client, err := openstack.NewContainerV1(providerClient, endpointOptions)
client.Microversion = "X.Y"

allPages, err := capsules.List(client, nil)
allCapsules, err := capsules.ExtractCapsulesVXY(allPages)
```

VXY will, obviously, need replaced with whatever microversion is the minimum required for this new model.

Let me know what you think.

**Comment by hongbin** [comment]
Thanks, I will try that approach later.

**Comment by hongbin** [comment]
@jtopjian ,

You approach should work. What would make it perfect is going one step further:

* In ExtractCapsules, read the API version header from the response
* Perform legacy or new capsule extraction based on the API version above
* If above extract a legacy capsule object, manually convert it to a up-to-date capsule object
* Return the up-to-date capsule object

If above is done, in theory, users should be able to use the same code to consume different API version without being aware of the differences.

**Comment by jtopjian** [comment]
@hongbin That kind of functionality would be great, but unfortunately not possible in Go. The reason is because the function can only return one type of Capsule - not multiple types. I spent a long time trying to figure out clever ways around this, but wasn't able to find anything.

If you're having problems falling asleep, this very long thread will help: https://github.com/gophercloud/gophercloud/issues/441 :)

So at the moment, there unfortunately needs to be some kind of either/or situation: Either `ExtractCapsules` is called or `ExtractCapsulesVXY`. 

Thank you for taking a look. If you'd like, I can finish off this work and have it merged. The only remaining piece is to replace "VXY" with the actual microversion - do you know what the version will be?

**Comment by hongbin** [comment]
Sure. The version is 1.32. Thanks for figuring this out.

**Comment by jtopjian** [comment]
Thanks! I'll make the appropriate changes (including acceptance tests) tomorrow. 🙂

**Comment by hongbin** [comment]
No problem. Just let me know if anything I can help.

**Comment by hongbin** [comment]
In flavor of https://github.com/gophercloud/gophercloud/pull/1469

**Pull request closed without merging**
