### PR TITLE
Acc Tests: Fixing subnet creation and re-enabling sharedfilesystem

### PR DESCRIPTION
**Pull request by jtopjian**
For https://github.com/theopenlab/openlab/issues/360

### CODE REVIEW

**Comment by huangtianhua** [comment]
recheck

**Comment by jtopjian** [comment]
Looking good! Going to run one or two more times.

**Comment by jtopjian** [comment]
recheck

**Comment by huangtianhua** [comment]
recheck

**Comment by huangtianhua** [comment]
recheck

**Comment by huangtianhua** [comment]
recheck

**Comment by jtopjian** [comment]
I think we're good to go! @huangtianhua Thanks so much :)

**Pull request merged**
