### PR TITLE
[WIP] Add L7 load balancing functionality support

### PR DESCRIPTION
**Pull request by lingxiankong**
For #832

- octavia l7 policy api: <https://github.com/openstack/octavia/blob/master/octavia/api/v2/controllers/l7policy.py>
- octavia l7 rule api: <https://github.com/openstack/octavia/blob/master/octavia/api/v2/controllers/l7rule.py>

### CODE REVIEW

**Comment by jtopjian** [comment]
@lingxiankong I know this is marked as WIP but I wanted to make a few comments:

* This is really impressive. It's clean, well-formatted, and follows all of our normal conventions. Really nice work on this :)
* However, it'll need split up into a few different PRs. A single PR should implement one action (such as create, update, list, etc). See #723 (and the related PRs) for examples of how to create a series of PRs like this and let me know if you have any questions. I realize that'll cause some extra work for you since you have everything complete and I apologize about that.
* I noticed `int32` being used in some areas. Can you change this to `int`?
* Would it be possible to add acceptance tests for this?

Again - this is a really good implementation - thank you! Let me know if you have any questions.

**Comment by lingxiankong** [comment]
@jtopjian sure, i will update the PR, because i am a Gerrit user, i'm not sure how to submit dependent PRs in Github appropriately, or i just need to submit and merge the patch one by one? Could you please give me some hints about the best practice? Thanks!

**Comment by jtopjian** [comment]
@lingxiankong There are a few methods - you're free to pick whichever you feel more comfortable with:

Option 1:

1. Start on the master branch
2. Create a new branch
3. Implement "Create" with unit tests, etc
4. Commit and push
5. Go back to the master branch
6. Create a new branch.
7. Implement "Get" with unit tests, etc
8. Commit and push

Pros: PRs are distinct and can be merged in any order.
Cons: You will most likely have to rebase and resolve merge conflicts after each PR is merged. Additionally, you will most likely have duplicated code in each branch.

Option 2:

1. Start on the master branch
2. Create a new branch.
3. Implement "Create" with unit tests, etc
4. Commit and push
5. Create a new branch.
6. Implement "Get" with unit tests, etc
7. Commit and push

Pros: You're only adding new code to each new branch.
Cons: If you have to make changes to the "Create" branch, you'll need to rebase the "Get" branch (and any other child branch). Also, PRs must be merged in a certain order.

Neither option is great - both have their quirks.

Personally I use Option 2 but we've had equal use of both 1 and 2 here.

With either option, it's helpful to pick one PR that you'd like us to focus reviews on and tag all other PRs with `[PENDING #nnn]`.

Let me know if you have any questions :)

**Comment by lingxiankong** [comment]
thanks @jtopjian for the very detailed instruction, i will go for option 2 as it is much like what i do with Gerrit

**Comment by jtopjian** [comment]
@lingxiankong sounds good! When your other PRs are ready for review, just make a comment that says "ready for review" or similar. Either myself, @jrperritt, or @dklyle will do a code review.

Even if the PR doesn't have a `[wip]` tag, it's still best to request a review anyway.

**Pull request closed without merging**
