### PR TITLE
ci/functional: fix ubuntu version & add antelope

### LINKED ISSUE #2756: Add CI jobs for new branches of OpenStack
New versions of OpenStack were released since Zed, we need to add CI jobs.

### PR DESCRIPTION
**Pull request by EmilienM**
- add `antelope` release in the matrix
- switch master jobs to run on ubuntu 22.04
- switch tests to use `lioadm` (supported and stable) and not `tgtd` (broken)

Fixes #2756

### CODE REVIEW

**Comment by EmilienM** [comment]
The failures seems to be related to volume attachment on the Ubuntu 22.04, we didn't have these issues before I think and this PR bumps the Ubuntu version.

I'll dig that out.

**Comment by EmilienM** [comment]
The error seems to happen when running `iscsiadm --login` against the target which prevents the volume to be attached to the server, therefore all the tests related to volumes fail.

https://paste.opendev.org/show/bZpwmV242HFL1GwNDwbK/

**Comment by pierreprinetti** [comment]
Do you think we'd get fewer failures by spinning off the Ubuntu bump to another PR?

**Comment by EmilienM** [comment]
> Do you think we'd get fewer failures by spinning off the Ubuntu bump to another PR?

The issue will be the same on Antelope and Master; so I'll use this PR.

**Review by mandre — APPROVED** [review]
LGTM
Let's merge what we have know and fix the remaining failures in subsequent commits.

**Pull request merged**
