### PR TITLE
[CI-v2] Add container job with Github Action

### PR DESCRIPTION
**Pull request by mandre**
- Deploy Zun with Devstack
- Run messaging acceptance tests
- Logs failures if any

### CODE REVIEW

**Comment by mandre** [comment]
Seems like zun-compute is not able to connect to the docker socket:
```
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: CRITICAL zun [-] Unhandled error: requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'EACCES'))
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun Traceback (most recent call last):
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun     httplib_response = self._make_request(
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun   File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 398, in _make_request
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun     conn.request(method, url, **httplib_request_kw)
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun   File "/usr/lib/python3.8/http/client.py", line 1256, in request
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun     self._send_request(method, url, body, headers, encode_chunked)
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun   File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun     self.endheaders(body, encode_chunked=encode_chunked)
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun   File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun     self._send_output(message_body, encode_chunked=encode_chunked)
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun   File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun     self.send(msg)
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun   File "/usr/lib/python3.8/http/client.py", line 951, in send
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun     self.connect()
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun   File "/usr/local/lib/python3.8/dist-packages/docker/transport/unixconn.py", line 30, in connect
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun     sock.connect(self.unix_socket)
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun   File "/usr/local/lib/python3.8/dist-packages/eventlet/greenio/base.py", line 260, in connect
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun     if socket_connect(fd, address):
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun   File "/usr/local/lib/python3.8/dist-packages/eventlet/greenio/base.py", line 47, in socket_connect
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun     raise socket.error(err, errno.errorcode[err])
Apr 08 16:07:05.964591 fv-az129-611 zun-compute[88123]: ERROR zun PermissionError: [Errno 13] EACCES
```

I can't tell why... The devstack config is not very different from the [old openlab config](https://github.com/theopenlab/openlab-zuul-jobs/blob/c2f76fe/roles/create-devstack-local-conf/tasks/main.yml#L239-L251), or [zun's CI config](https://github.com/openstack/zun/blob/23d2e3f/.zuul.yaml#L143-L157) either. I wonder what I missed. Could it be a bug in [devstack-plugin-container](https://github.com/openstack/devstack-plugin-container)?

**Comment by mandre** [comment]
I believe the problem comes from wrong user/group:
```
STACK_GROUP=docker
STACK_USER=runner
```
I'm not sure when the docker STACK_GROUP is coming from. Using a plain Ubuntu focal, I was able to get the devstack install to completion with:
```
STACK_GROUP=ubuntu                                                                                        
STACK_USER=ubuntu  
```

**Comment by mandre** [comment]
Meh, still the same error:
```
Apr 25 09:40:47.727131 fv-az132-410 zun-compute[89442]: ERROR zun.compute.manager [None req-297562e5-84d9-4980-b187-b5d678a1b229 None None] Unexpected exception: <_InactiveRpcError of RPC that terminated with:
Apr 25 09:40:47.727131 fv-az132-410 zun-compute[89442]:         status = StatusCode.UNAVAILABLE
Apr 25 09:40:47.727131 fv-az132-410 zun-compute[89442]:         details = "failed to connect to all addresses"
Apr 25 09:40:47.727131 fv-az132-410 zun-compute[89442]:         debug_error_string = "{"created":"@1650879647.726163832","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3128,"referenced_errors":[{"created":"@1650879647.726162732","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
Apr 25 09:40:47.727131 fv-az132-410 zun-compute[89442]: >: grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
Apr 25 09:40:47.727131 fv-az132-410 zun-compute[89442]:         status = StatusCode.UNAVAILABLE
Apr 25 09:40:47.727131 fv-az132-410 zun-compute[89442]:         details = "failed to connect to all addresses"
Apr 25 09:40:47.727131 fv-az132-410 zun-compute[89442]:         debug_error_string = "{"created":"@1650879647.726163832","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3128,"referenced_errors":[{"created":"@1650879647.726162732","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
Apr 25 09:40:47.727131 fv-az132-410 zun-compute[89442]: >
Apr 25 09:40:47.727131 fv-az132-410 zun-compute[89442]: ERROR zun.compute.manager Traceback (most recent call last):
Apr 25 09:40:47.727131 fv-az132-410 zun-compute[89442]: ERROR zun.compute.manager   File "/opt/stack/zun/zun/compute/manager.py", line 370, in _do_container_create_base
Apr 25 09:40:47.727131 fv-az132-410 zun-compute[89442]: ERROR zun.compute.manager     container = self.capsule_driver.create_capsule(
Apr 25 09:40:47.727131 fv-az132-410 zun-compute[89442]: ERROR zun.compute.manager   File "/opt/stack/zun/zun/container/cri/driver.py", line 52, in create_capsule
Apr 25 09:40:47.727131 fv-az132-410 zun-compute[89442]: ERROR zun.compute.manager     self._create_pod_sandbox(context, capsule, requested_networks)
Apr 25 09:40:47.727131 fv-az132-410 zun-compute[89442]: ERROR zun.compute.manager   File "/opt/stack/zun/zun/container/cri/driver.py", line 80, in _create_pod_sandbox
Apr 25 09:40:47.727131 fv-az132-410 zun-compute[89442]: ERROR zun.compute.manager     sandbox_resp = self.runtime_stub.RunPodSandbox(
Apr 25 09:40:47.727131 fv-az132-410 zun-compute[89442]: ERROR zun.compute.manager   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 946, in __call__
Apr 25 09:40:47.727662 fv-az132-410 zun-compute[89442]: ERROR zun.compute.manager     return _end_unary_response_blocking(state, call, False, None)
Apr 25 09:40:47.727662 fv-az132-410 zun-compute[89442]: ERROR zun.compute.manager   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
Apr 25 09:40:47.727662 fv-az132-410 zun-compute[89442]: ERROR zun.compute.manager     raise _InactiveRpcError(state)
Apr 25 09:40:47.727662 fv-az132-410 zun-compute[89442]: ERROR zun.compute.manager grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
Apr 25 09:40:47.727662 fv-az132-410 zun-compute[89442]: ERROR zun.compute.manager         status = StatusCode.UNAVAILABLE
Apr 25 09:40:47.727662 fv-az132-410 zun-compute[89442]: ERROR zun.compute.manager         details = "failed to connect to all addresses"
Apr 25 09:40:47.727662 fv-az132-410 zun-compute[89442]: ERROR zun.compute.manager         debug_error_string = "{"created":"@1650879647.726163832","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3128,"referenced_errors":[{"created":"@1650879647.726162732","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
```

**Comment by pierreprinetti** [comment]
@mandre 
Is this still relevant?

**Pull request closed without merging**
