### PR TITLE
Fix bad required tags

### PR DESCRIPTION
**Pull request by jtopjian**
For #910

### CODE REVIEW

**Comment by jtopjian** [comment]
These are header opts :)

https://github.com/gophercloud/gophercloud/blob/master/params.go#L443

**Comment by jrperritt** [comment]
OK, then the treatment of required fields between headers and query parameters should be reconciled (i.e. they should match).

**Comment by jtopjian** [comment]
Sounds good to me. I was going to reconcile the behavior but saw that the current format (`tag,required`) was being tested in the unit test, so I figured that's how it was intended.

**Comment by jrperritt** [comment]
I'm fine with either being the format. The `tag,required` is more in agreement with the `json` package (and probably looks better), but then either the `required` label is position-dependent or you iterate over the comma-split slice looking for "required".

**Pull request closed without merging**
