### PR TITLE
baremetal: update inspection inventory with recent additions

### PR DESCRIPTION
**Pull request by dtantsur**
Closes: #2632

### CODE REVIEW

**Comment by dtantsur** [comment]
Older branches fail with
```
The following packages have unmet dependencies:
 docker.io : Depends: containerd (>= 1.2.6-0ubuntu1~)
E: Unable to correct problems, you have held broken packages.
```

**Comment by dtantsur** [comment]
I'm trying to get rid of docker in https://review.opendev.org/c/openstack/ironic/+/885243

**Comment by dtantsur** [comment]
@mandre hi, could you take a look? This is blocking some work on the Metal3 side.

The Xena job should be okay now, I'm just not sure how to retrigger it. I'm trying to fix Wallaby and Victoria, but they're so old that I'm not sure it's possible any more.

**Comment by mandre** [comment]
Sorry I hadn't realized this was ready for review - will take a look shortly.

**Review by mandre — APPROVED** [review]

**Comment by dtantsur** [comment]
@mandre hi, any plans for a release?

**Comment by kayrus** [comment]
@dtantsur it's a go module, you can just set the git commit of the master HEAD in your go.mod. Or is there anything that requires a new release?

**Comment by dtantsur** [comment]
Yeah, I'll probably go down the hash path.

**Pull request merged**
