### PR TITLE
Magnum: Manage Clusters Create

### PR DESCRIPTION
**Pull request by JackKuei**
Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #[1062 [Migrate Magnum Branch Onto Master]](https://github.com/gophercloud/gophercloud/issues/1062)

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[[clusters:create]](https://github.com/openstack/magnum/blob/master/magnum/api/controllers/v1/cluster.py#L432)

### CODE REVIEW

**Comment by JackKuei** [comment]
@jtopjian This one is ready to be reviewed.

**Comment by jtopjian** [comment]
@JackKuei I've had a busy schedule lately. It might take me another few days to get to this.

**Comment by JackKuei** [comment]
@jtopjian Sounds good. Whenever you get a chance. Thanks.

**Comment by JackKuei** [comment]
@ozerovandrei Sure thing. Will PR that next.

**Comment by JackKuei** [comment]
@jtopjian This one is ready.

**Pull request merged**
