### PR TITLE
Update loadbalancer/v2/l7policies create and update

### PR DESCRIPTION
**Pull request by nikParasyr**
Add REDIRECT_PREFIX and REDIRECT_HTTP_CODE to l7policy
CreateOpts and UpdateOpts.
Docs: https://docs.openstack.org/api-ref/load-balancer/v2/?expanded=create-an-l7-policy-detail,update-a-l7-policy-detail#create-an-l7-policy
Fixes: #2322

### CODE REVIEW

**Comment by nikParasyr** [comment]
recheck

**Comment by nikParasyr** [comment]
@EmilienM can you have a look? The failing tests seem to be "irrelevant" afaik, but maybe im missing something

**Review by mandre — CHANGES_REQUESTED** [review]
> @EmilienM can you have a look? The failing tests seem to be "irrelevant" afaik, but maybe im missing something

Correct, the failing tests are all in `acceptance/openstack/networking/v2/extensions/qos` and unrelated to your patch.

Could you just add the `redirect_prefix` and `redirect_http_code` fields to [results.go](https://github.com/gophercloud/gophercloud/blob/master/openstack/loadbalancer/v2/l7policies/results.go) as well?

**Comment by nikParasyr** [comment]
> Could you just add the redirect_prefix and redirect_http_code fields to results.go as well?

@mandre done! Thanks :)

**Comment by mandre** [comment]
Same 5 failures in qos acceptance tests, something's off with that job but it's not related to your PR.

**Pull request merged**
