### PR TITLE
Baremetal acceptance job

### PR DESCRIPTION
**Pull request by iurygregory**
For #1466 

This PR will depend on the Issue [theopenlab/openlab/issues/195](https://github.com/theopenlab/openlab/issues/195) that already have a PR to enable Ironic on DevStack [theopenlab/openlab-zuul-jobs#443](https://github.com/theopenlab/openlab-zuul-jobs/pull/443) 

In this PR we create a new job to enable ironic and run only the acceptance tests for baremetal v1
tests:
- Create a new job `gophercloud-acceptance-test-ironic`
- Create a playbook for the job
- Create a script to run only ironic acceptance

### CODE REVIEW

**Comment by iurygregory** [comment]
recheck

**Comment by iurygregory** [comment]
@jtopjian This is the PR for the acceptance job for Ironic, the PR in the OpenLab is merged already (https://github.com/theopenlab/openlab-zuul-jobs/pull/443) , but for some reason I don't see the job I've created running do you have any idea if I need something else? Thanks!

**Comment by iurygregory** [comment]
recheck

**Comment by iurygregory** [comment]
@jtopjian This is ready for review =)

**Comment by jtopjian** [comment]
@iurygregory Thank you for the work you've put in to get this working :)

This looks good to me, but just a heads up that once all of the Ironic work has finished, I will probably remove the job from being automatically run upon each PR. Meaning: users will have to manually trigger `recheck ironic` or something similar.

Given the amount of Ironic work going on at the moment I think having the tests run with each PR right now is useful, but once it's done, it might not make sense to have it run upon _every_ PR.

**Comment by iurygregory** [comment]
@jtopjian I totally agree! Thanks for the help =)

**Pull request merged**
