### PR TITLE
Acc Tests: Parse the key returned by Nova

### PR DESCRIPTION
**Pull request by jtopjian**
For #210

### CODE REVIEW

**Comment by jtopjian** [comment]
@liu-sheng job output looks good! Thank you!!

**Comment by jtopjian** [comment]
recheck mitaka

**Comment by jtopjian** [comment]
recheck/mitaka

**Comment by jtopjian** [comment]
recheck stable/mitaka

**Comment by jtopjian** [comment]
recheck stable/mitaka

**Comment by jtopjian** [comment]
recheck stable/mitaka

**Comment by liu-sheng** [comment]
recheck stable/mitaka

**Comment by liu-sheng** [comment]
recheck stable/mitaka

**Comment by jtopjian** [comment]
@liu-sheng I apologize for the late reply :frowning_face: 

Thank you for looking into this. I'd like to (eventually) get the failing tests ignored when testing against Mitaka (or any other older release). Is there an environment variable of some sort that I can use to skip certain tests? Similar to what's done here: https://github.com/gophercloud/gophercloud/blob/master/acceptance/clients/conditions.go

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by liu-sheng** [comment]
@jtopjian hah, it is never late at all :smile: 

That seems is possible, but need to modify the job definition, we can add a var in the job definition, just like the `os_branch: stable/mitaka` in [here](https://github.com/gophercloud/gophercloud/blob/master/.zuul.yaml#L53), e.g. 'skip_tests: xxx' the variable can be passed to the [playbook](https://github.com/gophercloud/gophercloud/blob/master/.zuul/playbooks/gophercloud-acceptance-test/run.yaml) and need to be handled in the [script](https://github.com/gophercloud/gophercloud/blob/master/script/acceptancetest)

**Comment by jtopjian** [comment]
@liu-sheng Rather than specifying individual tests in the job definition, is it possible to set `os_branch` in the environment? That way the acceptance tests can self-determine what release/branch is being run and skip dynamically. 

For example, in [`conditions.go`](https://github.com/gophercloud/gophercloud/blob/master/acceptance/clients/conditions.go), I could have:

```go
func SkipMitaka(t *testing.T) {
	if os.Getenv("OS_BRANCH") == "stable/mitaka" {
		t.Skip("this is not supported in mitaka")
	}
}

func SkipNewton(t *testing.T) {
	if os.Getenv("OS_BRANCH") == "stable/newton" {
		t.Skip("this is not supported in newton")
	}
}

```

And then for the breaking tests:

```go
func TestSomeNewFeature(t *testing.T) {
	clients.SkipMitaka(t)
	clients.SkipNewton(t)

        ...
}
```

**Comment by liu-sheng** [comment]
@jtopjian that sounds easy to implement, will have a try :)

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
The latest failing is caused by client init failing for Container API, that is not supported in Mitaka release yet, so we can ignore it, that do not block this PR merging. And OpenLab is trying to make test case know which OpenStack release will be used in testing, still be in WIP, see https://github.com/theopenlab/openlab/issues/67 . If it is ready, we can decide which test cases will be executed in which OpenStack release, like @jtopjian say https://github.com/gophercloud/gophercloud/pull/1013#issuecomment-395633308

**Comment by jtopjian** [comment]
recheck stable/mitaka

**Comment by jtopjian** [comment]
This is working as intended. The test passes in stable and fails in Mitaka (which is expected).

**Pull request merged**
