### PR TITLE
Messaging Message Delete Message

### PR DESCRIPTION
**Pull request by problemv**
For #836

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

https://github.com/openstack/zaqar/blob/8e0dd9763aba67bb7094cf92312daeba8d087866/zaqar/transport/wsgi/v2_0/messages.py#L375

### CODE REVIEW

**Comment by problemv** [comment]
@jtopjian Ready for review and then Messages are done! :)

**Comment by animationzl** [comment]
recheck

**Comment by problemv** [comment]
@jtopjian fixed.

**Comment by jtopjian** [comment]
LGTM - thanks :)

**Pull request merged**
