### PR TITLE
Networking Acceptance Test Cleanup

### PR DESCRIPTION
**Pull request by jtopjian**
for #78

### CODE REVIEW

**Comment by jtopjian** [comment]
@jrperritt ping for review

Also included is a second devstack script to bring up a keystone v3 and lbaas v2 environment. The existing devstack script can be used for keystone v2 and lbaas v1. If there's an opportunity to run automated acceptance tests, I'm not sure how best to run the tests separately in an automated fashion -- maybe an extra build tag?

**Comment by jrperritt** [comment]
> I'm not sure how best to run the tests separately in an automated fashion

Which tests specifically? 
`go test github.com/gophercloud/gophercloud/acceptance/openstack/networking/v2/...` should run just the networking v2 acceptance tests.

**Comment by jtopjian** [comment]
Right, but, specifically for networking, lbaas and lbaasv2 can't be run on the same OpenStack environment. Given that lbaas is deprecated, it's probably ignorable altogether.

In that case, the only other combination would be keystone v2 and v3.

**Comment by jrperritt** [comment]
Ah, I see. Off the top of my head, one alternative to leaving it as is and letting users run the tests the want to run: 
In the relevant test packages (maybe in `init` functions), check the user's catalog for the service version, set a global flag, and, in the `Test*` functions, run or skip based on the flag.

**Comment by jtopjian** [comment]
Good ideas :)

**Comment by jrperritt** [comment]
Did you want to make any more changes to this or is it still ready to merge?

**Comment by jtopjian** [comment]
Oh, sorry - I meant to follow up this morning to say that the automated test ideas discussed are probably best suited for another PR.

IMO, this is ready to go. Let me know if you'd like to see anything fixed up, though.

**Comment by jrperritt** [comment]
+2

**Pull request merged**
