### PR TITLE
Feature/filestorage sharenetworks remove securityservice

### PR DESCRIPTION
**Pull request by ehdou**
Add support for Share Network Remove security service
For #130

### CODE REVIEW

**Comment by ehdou** [comment]
[Remove security service function](https://github.com/openstack/manila/blob/16c522bf5e5c3d37018caef11dd7852462193327/manila/api/v1/share_networks.py#L328) for share network

**Comment by ehdou** [comment]
@jrperritt This PR is ready for review. It's based on [PR#137](https://github.com/gophercloud/gophercloud/pull/137) and adds support for share network Add security service

**Comment by ehdou** [comment]
@jtopjian I rebased this PR and it's now ready for review

**Comment by jtopjian** [comment]
This looks good to me - thanks!

**Pull request merged**
