### PR TITLE
Move CI job definition to gophercloud repo

### PR DESCRIPTION
**Pull request by yongfengdu**
Add the jobs definition to .zuul.yaml, and the ansible playbooks.

For #974

### CODE REVIEW

**Comment by yongfengdu** [comment]
@jtopjian Would you please take a look at the change? The openlab ci check failed because of duplicate job definition, so we need to coordinate with theopenlab repo.
First remove the openlab jobs from theopenlab repo, then add this one here.
We'll do this switch after review completed.

**Comment by yongfengdu** [comment]
I've changed the playbooks to sub-directory .zuul/
Also tried change the test name to xxx-testTTT, to verify that everything works as expected.
Please review the current version, and if the change is ok, I'll need to notify openlab teams to merge the changes there at the same time for a smooth switch.

The changes in openlab:
https://github.com/theopenlab/openlab-zuul-jobs/pull/201

**Comment by jtopjian** [comment]
LGTM - thank you!

I can merge this at any time starting tomorrow (MST time). Just let me know when :)

**Comment by yongfengdu** [comment]
@jtopjian Thanks, I have synced with openlab team, they will merge openlab changes after you merge this one. But since this is Friday, I prefer to do this at your next Monday, like 6:00PM or later?

**Comment by jtopjian** [comment]
@yongfengdu Sounds good to me. I'll merge this at around 730pm (GMT-6) on Monday.

**Comment by animationzl** [comment]
recheck

**Pull request merged**
