### PR TITLE
LBaaS_v2: Listener's default_pool_id should not be omitted during update

### LINKED ISSUE #1355: LBaaS_v2: don't omit IDs during the update
Similar to #1350.

Listener field should be `null` if it is empty:
* default_pool_id [ref](https://github.com/openstack/neutron-lbaas/blob/mitaka-eol/neutron_lbaas/extensions/sharedpools.py#L55)

### PR DESCRIPTION
**Pull request by kayrus**
Resolves #1355
Missed this field.

### CODE REVIEW

**Comment by jtopjian** [comment]
@kayrus After looking at this, I made a mistake with approving #1351.

The changes here and changes in #1351 will require the user to have to set the fields to their current value unless they want the value to be removed. This isn't what we want.

Instead, look at how `gateway_ip` is handled in Neutron subnets: https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/subnets/requests.go#L203-L205

So #1351 will need reverted/modified and the changes here will need reverted, too, and then a special case in the `UpdateMap` will need to be added. I apologize about this - it's my fault for not catching it earlier.

**Comment by kayrus** [comment]
Maybe I got you wrong, but last time (sorry, cannot find the evidence, too many messages, give me some time, maybe I'll find it) you told me that gophercloud should not implement logic on input data, that is why I already prepared a commit for terraform, but not for gophercloud:

```diff
        if d.HasChange("default_pool_id") {
                defaultPoolID := d.Get("default_pool_id").(string)
-               updateOpts.DefaultPoolID = &defaultPoolID
+               if defaultPoolID != "" {
+                       updateOpts.DefaultPoolID = &defaultPoolID
+               }
        }
```

**Comment by jtopjian** [comment]
Yes, in #1343, I was saying that we should not mask that Manila has `name` and `display_name`.

In this case, this is a limitation of Go. If someone were to pass an empty `UpdateOpts`, they would end up removing their `redirect_pool_id` et al, possibly unintentionally. That's Gophercloud and Go causing that - not Neutron / Octavia.

There are two ways to get around this:

1. The user _must_ specify `RedirectPoolID` et al regardless of if they are updating it or not. 
2. Have Gophercloud use an empty string as a way of saying "The user wants to pass `null`".

> UPD: In addition, unlike https://github.com/gophercloud/gophercloud/blob/master/openstack/networking/v2/subnets/requests.go#L203-L205, redirect_pool_id, redirect_url and key are not accepted by neutron API as an empty string, but only as null.

We're using an empty string to trigger a null value:

```go
// If `gateway_ip` is an empty string
if m := b["subnet"].(map[string]interface{}); m["gateway_ip"] == "" {
  // Then change it from an empty string to `nil` which will be sent as `null` in JSON form.
  m["gateway_ip"] = nil
}
```


Please let me know if this clarifies things.

**Comment by kayrus** [comment]
Ok, I'll prepare an update. Do I need to create a new issue and a new PR for each component?

**Comment by jtopjian** [comment]
Since this is my mistake for not catching it before, I'll go ahead and do a PR for #1351. This way you only need to re-do this PR.

**Comment by kayrus** [comment]
This is not your mistake, I just got you wrong on [this comment](https://github.com/gophercloud/gophercloud/pull/1343#discussion_r240014764) and I explicitly didn't put additional logic. Nevertheless, thank you a lot for your effort helping me.

**Comment by kayrus** [comment]
> Coverage decreased (-0.01%)

How come?

**Comment by jtopjian** [comment]
Coveralls can act weird a lot of times - it's safe to ignore. :)

**Comment by kayrus** [comment]
Fixed test. Forgot to explicitly set an empty string for the `DefaultPoolID`.

**Pull request merged**
