### PR TITLE
Networking V2: add Agent Get request

### PR DESCRIPTION
**Pull request by ozerovandrei**
Add Get method for the "networking/v2/extensions/agents" package.
Provide unit test and documentation.
Add TestAgentsRead for testing reading of real Networking V2 agents.

For #1389

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[Code reference(API)](https://github.com/openstack/neutron-lib/blob/stable/rocky/neutron_lib/api/definitions/agent.py)
[Code reference(DB)](https://github.com/openstack/neutron/blob/stable/rocky/neutron/db/agents_db.py#L341)

### CODE REVIEW

**Comment by ozerovandrei** [comment]
recheck

**Comment by jtopjian** [comment]
Both List and Get LGTM, except that `AdminStateUP` needs to be `AdminStateUp`.

**Comment by ozerovandrei** [comment]
It failed on loadbalancers:
```
2019-01-11 09:37:33.517982 | ubuntu-xenial |     loadbalancer.go:80: Waiting for loadbalancer TESTACCT-rSzD1Crm to become active
2019-01-11 09:37:33.523336 | ubuntu-xenial |     convenience.go:35: [1;31mFailure in loadbalancers_test.go, line 50: unexpected error [0m[1;33m"A timeout occurred"[0m[1;31m[0m
```

**Comment by ozerovandrei** [comment]
recheck

**Comment by ozerovandrei** [comment]
@jtopjian both PRs are ready.

**Pull request merged**
