### PR TITLE
Identity V3: Update Policy

### PR DESCRIPTION
**Pull request by zhangzujian**
For #972 

Depend on PR #1000

### CODE REVIEW

**Comment by zhangzujian** [comment]
Ready for review.

**Comment by jtopjian** [comment]
This looks good to me. Will merge after #1000 

Nice work with this -- thank you for adding it.

**Comment by jtopjian** [comment]
@zhangzujian Do you mind rebasing this?

**Comment by zhangzujian** [comment]
recheck

**Comment by zhangzujian** [comment]
@jtopjian Sorry for the delay. Please review.

**Comment by jtopjian** [comment]
@zhangzujian No problem at all :)

**Pull request merged**
