### PR TITLE
Add missing `Deleted` and `DeletedAt` fields

### PR DESCRIPTION
**Pull request by dstdfx**
For #738

### CODE REVIEW

**Comment by dstdfx** [comment]
recheck

**Comment by dstdfx** [comment]
@jtopjian Is there some problem with OpenLab?

**Comment by jtopjian** [comment]
@dstdfx Yes, looks like there might be. @liu-sheng ?

**Comment by jtopjian** [comment]
Looks like it was either a temporary issue or it has been fixed :)

I think I understand why these two fields are marked as deprecated in the Nova code: they will never return any other value besides their zero-value. This is because it's not possible to see _all_ aggregates, including those that have been deleted. And if you're only seeing aggregates that aren't deleted, then `deleted` will be false and `deleted_at` won't have a value 😄 

However, Nova _is_ returning these fields:

```json
{
    "aggregates": [
        {
            "availability_zone": null,
            "created_at": "2018-01-31T19:36:59.000000",
            "deleted": false,
            "deleted_at": null,
            "hosts": [],
            "id": 5,
            "metadata": {},
            "name": "foo",
            "updated_at": null,
            "uuid": "7a3cf5e8-0709-41f4-826e-8b2a0e49a4fa"
        }
    ]
}
```

Because of that, I'm OK with adding these fields. It's also possible that prior versions of Nova provided the ability to see old aggregates.

@dstdfx Thank you for adding these.

/cc @dklyle

**Pull request merged**
