### PR TITLE
Manila: add share snapshot support (tests)

### PR DESCRIPTION
**Pull request by kayrus**
Part of the  #1380

### CODE REVIEW

**Comment by kayrus** [comment]
@jtopjian ready for review

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
recheck

**Comment by jtopjian** [comment]
@kayrus This needs rebased. In addition, it's combining Create, Update, and Delete into a single PR. This needs to be three separate PRs.

Having Get and List are fine because Gophercloud's policy is 1 PR per "method" and both Get and List use `GET`. But POST, PUT/PATCH, and DELETE are three separate methods.

**Comment by kayrus** [comment]
@jtopjian I'm not sure why do I need to split PRs, but ok.

**Comment by jtopjian** [comment]
> I'm not sure why do I need to split PRs, but ok.

In general, a patch/PR should always be an atomic unit. `POST` can exist without `DELETE`. It can be tested, both with unit tests and acceptance tests, and not require any other methods. 

Additionally, it's part of the [rules](https://github.com/gophercloud/gophercloud/blob/master/docs/STYLEGUIDE.md) of this project, which I bend as far as I can go to make it easier for contributors.

If I merge PRs that blatantly disregard the project rules, I'll have my merge rights removed and then we're all screwed :)

**Comment by kayrus** [comment]
@jtopjian I saw PRs, which introduced everything at once, like https://github.com/gophercloud/gophercloud/pull/1338. This added a confusion. Besides I didn't want to wait for each PR to be merged, then rebase and again and again.
But now I see that there were independent PRs and one combined PR like this.

**Comment by jtopjian** [comment]
> Besides I didn't want to wait for each PR to be merged, then rebase and again and again.

Sometimes this is unavoidable, but I try to minimize this and fast-track as much as I can.

**Pull request merged**
