### PR TITLE
Cleanup: fix formatting

### PR DESCRIPTION
**Pull request by Fedosin**
Generated by `gofmt -s -w .`

For #2071

### CODE REVIEW

**Comment by Fedosin** [comment]
recheck

**Comment by jtopjian** [comment]
@Fedosin Thanks for doing this. This looks good to me. Let me know if you're ready to have this merged or if you were going to do any other work.

**Comment by pierreprinetti** [comment]
LGTM! :goat:

@jtopjian What about adding gofmt to the CI? And speaking of CI, do you have plans already for [the after-Travis](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)?

**Comment by jtopjian** [comment]
@pierreprinetti regarding `gofmt`, see my comments here: https://github.com/gophercloud/utils/pull/133 

This repo is currently using `goimports` to check for both code formatting and "import" statement stuff. The only area it's lacking is the `-s` flag for code simplification. For that, I'm on the fence. If someone wants to put the work into modifying the current script to do both `goimports` and `gofmt`, I'm happy to merge it. Otherwise, the basic formatting support that already exists is sufficient, IMO.

Regarding Travis... ugh. This is news to me. I'll have to look into it and see what options are available. Thank you for the heads-up.

**Comment by Fedosin** [comment]
@jtopjian yeah, the work (at least for this PR) is complete. we can merge it.

**Review by jtopjian — APPROVED** [review]
LGTM - thank you!

**Pull request merged**
