### PR TITLE
 Vpnaas: Get Endpoint Group

### PR DESCRIPTION
**Pull request by simonre**
For #723 

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

https://github.com/openstack/neutron-vpnaas/blob/058469e1b99b647537a5228c6a384d93df5484df/neutron_vpnaas/db/vpn/vpn_db.py#L621

### CODE REVIEW

**Comment by simonre** [comment]
@jtopjian Other than needing a rebase as soon as #794 is merged I think this is ready for review

**Comment by jtopjian** [comment]
@simonre This looks good. Can you also implement that small doc fix mentioned here:

https://github.com/gophercloud/gophercloud/pull/794#discussion_r171310766

**Comment by simonre** [comment]
@jtopjian I implemented the doc fix and rebased.

**Comment by jtopjian** [comment]
LGTM!

**Pull request merged**
