### PR TITLE
Feature/filestorage sharetype removeaccess

### PR DESCRIPTION
**Pull request by ehdou**
Add support for Share Type Remove Access
For #140

### CODE REVIEW

**Comment by ehdou** [comment]
[Remove access function](https://github.com/openstack/manila/blob/16c522bf5e5c3d37018caef11dd7852462193327/manila/api/v2/share_types.py#L255) for share type

**Comment by ehdou** [comment]
@jrperritt This PR is ready for review. It's based on [PR#150](https://github.com/gophercloud/gophercloud/pull/150) and adds support for share type Remove Access

**Comment by jtopjian** [comment]
@ehdou Can you rebase and ping when ready?

**Comment by ehdou** [comment]
@jtopjian I rebased this PR and it's now ready for review

**Comment by jtopjian** [comment]
LGTM! Thanks.

**Pull request merged**
