### PR TITLE
Fixing occurrences of incorrect required field tags

### PR DESCRIPTION
**Pull request by jtopjian**
For #400

### CODE REVIEW

**Comment by jtopjian** [comment]
@jrperritt Is there a reason that `omitempty` is shared with the JSON tag while the others (`required`, `xor`) have their own?

Although it would be a rather large change, would it make sense to have `omitempty:"true"` to better be able to spot incorrect tagging?

Doing a `grep -R ,required`, I see three similar occurrences of `,required`:

```
testing/params_test.go:         R  string    `q:"r,required"`
testing/params_test.go:         R  string    `q:"r,required"`
testing/params_test.go:         Num    int    `h:"Number,required"`
```

Should these be fixed as well?

**Comment by jtopjian** [comment]
Oh, nevermind. `omitempty` is a Go feature. I did not know that :)

**Comment by jrperritt** [comment]
> omitempty is a Go feature

Right. It _would_ make sense for Go to have something akin to a `required` tag, and I think there is an open issue about it. But yes, as of right now, anything other than `<FIELDNAME>,omitempty` in the `json` struct tag should be changed, since it's not being recognized.

**Comment by jrperritt** [comment]
Thanks for catching these others as well.

**Pull request merged**
