### PR TITLE
Set reauth func to nil before making a new request

### PR DESCRIPTION
**Pull request by garbage-collector**
For #1182 

This patch avoids infinite loop on reauthentication process in case of component is always answering 401.

### CODE REVIEW

**Comment by jtopjian** [comment]
@garbage-collector Thank you for working on this. You can ignore the test failure for now - I need to fix that in a separate PR.

Forgive my ignorance, but I want to make sure I understand the effects of this implementation (I'm cautious about changing the Reauth stuff in case it creates unintended side effects):

You're setting `client.ReauthFunc` to nil before making the post-reauth request in order to stem the `ReauthFunc` from being triggered again, effectively making the reauthentication system a flat system that has no possibility of calling itself, right?

**Comment by garbage-collector** [comment]
@jtopjian yes, this patch aims to avoid the ReauthFunc being triggered again and again on the same call, while keeping the provider client clean for another call to another API (this is why the ReauthFunc is set again after the call).
By setting the ReauthFunc to nil, we ensure that the code will not go through the Reauth process a second time.

**Comment by jtopjian** [comment]
This makes sense to me.

Would it be possible to include a unit test (sans-Gock, though that's only due to the external dependency)? This will help prevent any regressions in the future.

**Comment by garbage-collector** [comment]
For sure. I'll add some unit tests asap :)

**Comment by jtopjian** [comment]
@garbage-collector Thank you! 😄 

@jrperritt Any thoughts/concerns on this PR?

**Comment by garbage-collector** [comment]
Tests have been added !

**Pull request merged**
