### PR TITLE
Auth: Allow TokenID passthrough when the scope is not set

### LINKED ISSUE #1566: Auth: introduce token auth
gophercloud should handle token auth

requirements:
* scope should be set in order to fetch catalog
* add support to `AuthOptionsFromEnv` func
* add `OS_AUTH_TYPE` env support

### PR DESCRIPTION
**Pull request by kayrus**
Resolves #1566

Reference:
https://github.com/terraform-providers/terraform-provider-openstack/pull/861#issuecomment-531261745

### CODE REVIEW

**Comment by kayrus** [comment]
recheck

**Comment by jtopjian** [comment]
I think there's an issue with OpenLab building the ironic environment. I think I've pinned it down - just need to find a minute to review and open an issue :)

**Comment by kayrus** [comment]
recheck

**Comment by kayrus** [comment]
@jtopjian ready for review

**Comment by jtopjian** [comment]
@kayrus Thank you for looking into this.

**Pull request merged**
