### PR TITLE
[Do Not Merge]change unittest

### PR DESCRIPTION
**Pull request by yongfengdu**
To verify the whether the CI is testing this PR branch.

### CODE REVIEW

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
Hi @yongfengdu thanks for pointing that, that is a mistake made during the zuul CI upgrade a few days ago, sorry :(  just fixed in the PR: https://github.com/theopenlab/openlab-zuul-jobs/pull/214

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by yongfengdu** [comment]
@liu-sheng Cool, I'll closed this PR

**Comment by jtopjian** [comment]
@yongfengdu @liu-sheng Thank you both for looking into this :)

**Pull request closed without merging**
